Enterprise-CMCS/eAPD

.circleci/config.yml, .codeclimate.yml, .gitignore, CONTRIBUTING.md, LICENSE.md, README.md, docker-compose.yml, web/.eslintignore, web/.eslintrc.json, web/.gitignore, web/Dockerfile, web/package-lock.json, web/package.json, web/polyfills.test.js, web/setup.test.js, web/src/__snapshots__/hello.test.js.snap, web/src/app.js, web/src/hello.js, web/src/hello.test.js, web/webpack.config.js
Initialize the repo with some stuff:
- Standard 18F files
- Continuous integration config
- Web app setup
- Docker
=> Initialize repo

web/package.json, web/src/app.js, web/src/index.html
=> add index.html

web/package-lock.json, web/package.json, web/src/components/App.js, web/src/components/Counter.js, web/src/containers/Home.js, web/src/index.html
This approach leans on a more modern, React-friendly approach to handling styling via CSS-in-JS ([background](https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660)).
It leverages `styled-components` and a library build on top called `Rebass` which consists of a large collection of functional UI components.
Instead of something like `<div className='card card--profile'><div className='header'>...</div></div>`, we can use visual primitive components that have styles baked into them: `<Card><Header>...</Header></Card>`
The library does the work of extracting the needed styles, creating the stylesheets, avoiding duplication, etc. And it's easy to add global theming as well as extend / compose new UI components. 
I recommend scanning through the …
=> initialize css architecture

api/main.js, api/package-lock.json, api/package.json
For now, added "Simple Usage" (Enable All CORS Requests)
Down the road, we may want to whitelist origins and routes?
Resolves #48
=> enable CORS

README.md, docs/api-authentication.md, docs/api-authorization.md, docs/api-configuration.md, docs/index.md
Starts to add some technical documentation.
=> Technical documentation

web/src/components/App.js, web/src/components/Demo.js
An example / demo page containing some UI components / patterns that I envision us using down the road :)
Preview:
=> add page with example UI components

api/auth/authenticate.test.js, api/auth/index.test.js, api/auth/middleware.test.js, api/auth/serialization.test.js, api/auth/session.test.js, api/db.test.js, api/env.test.js, api/package.json, api/routes/index.test.js, api/routes/users/get.test.js, api/routes/users/index.test.js, api/routes/users/post.test.js
This PR puts the API test files next to their corresponding source files, like with the frontend.
=> Move API test files around

api/_setup.test.js
Part B of https://github.com/18F/cms-hitech-apd/issues/52
=> api test setup (for reliable code coverage stats)

ISSUE_TEMPLATE.md
Created a standard issue template so that all of our issues are consistent.
=> Create a standard issue template

web/.eslintrc.json, web/package-lock.json, web/package.json, web/src/components/App.js, web/src/components/Form1.js, web/src/components/__snapshots__/App.test.js.snap, web/src/containers/StateStart.js, web/src/reducers/index.js, web/src/reducers/index.test.js
This PR adds [redux-form](https://github.com/erikras/redux-form), a library that helps manage a lot of the intricacies of working with forms. A few highlights:
* stores form values in our redux store (and abstracts away all the action creators / reducers to add and update those values
* real-time client side validation (upon submission and/or per keystroke)
* customizable input format / styles
There are two other libraries I considered: [react-redux-form](https://github.com/davidkpiano/react-redux-form), which is similar to `redux-form` and quite flexible (i.e., you create your own reducers for form values) but has lower adoption; and [formik](https://github.com/jaredpalmer/formik) which by design does not use redux (says it's unnecessary) and simply focuses on keeping track of your …
=> Our first form

web/src/components/FormStateContacts.js, web/src/components/FormStateStart.js, web/src/containers/StateContacts.js
This is an iteration of the form content and design of the state contacts page.
Preview:
=> state contacts iterate

web/package-lock.json, web/src/components/App.js, web/src/components/NoMatch.js, web/src/components/__snapshots__/App.test.js.snap
Displays a 404 / No Match component when there is no matching front-end route (as documented at https://reacttraining.com/react-router/web/example/no-match).
Preview:
=> add 404 component

web/src/components/App.js, web/src/components/__snapshots__/App.test.js.snap, web/src/containers/ActivitiesList.js, web/src/containers/ActivitiesStart.js
This is a intermediary page that serves to show user the activities they've identified as relevant and provides them with links to go and add details (or edit details) about that activity. For now, this is all static content; in the future, this list (and start/edit status) will be dynamic.
Preview:
=> Basic activities list

web/src/components/App.js, web/src/components/FormGoalsAndObjectives.js, web/src/components/__snapshots__/App.test.js.snap, web/src/containers/GoalsAndObjectives.js, web/src/util/formLogger.js
Adds a form for getting project goals and objectives.
- ~~Tests have been updated (and all tests are passing)~~ N/A
- ~~The change has been documented~~ N/A
- ~~Design has approved the experience~~ N/A - your time will come!
- ~~Product has approved the experience~~ samesies
=> Add "goals and objectives" form page

web/src/components/App.js, web/src/components/FormApproach.js, web/src/components/__snapshots__/App.test.js.snap, web/src/containers/Approach.js
Adds the approaches page to the UX prototype.
=> Add approaches page

web/src/components/App.js, web/src/components/FormActivitySchedule.js, web/src/components/__snapshots__/App.test.js.snap, web/src/containers/ActivitySchedule.js
Adds the milestone schedule page to the form UX prototype.
=> Add milestone schedule form page

web/src/components/FormActivityApproach.js, web/src/components/FormActivityGoals.js, web/src/components/FormStateContacts.js, web/src/components/FormStateStart.js, web/src/components/SectionHeader.js
small layout and style refinements
Preview:
=> prototype refinement

web/.eslintrc.json, web/src/components/FormActivityGoals.js, web/src/components/FormStateContacts.js, web/src/components/FormStateStart.js, web/src/components/PageNavButtons.js, web/src/containers/ActivitiesList.js, web/src/containers/ActivityApproach.js, web/src/containers/ActivitySchedule.js, web/src/styles/ButtonOutline.js
Fixes and tweaks based on walkthrough with @nkkl last night.
* "continue" button takes you back to activity list on approaches page
* removed example PII
* fixed hover/active color bug on `ButtonOutline`
=> prototype tweaks

web/src/components/FormActivitiesStart.js
Adds ability to fill in additional activities.
Closes: https://github.com/18F/cms-hitech-apd/issues/148
Preview:
=> add ability to add new activities

web/package-lock.json, web/package.json, web/src/components/__snapshots__/App.test.js.snap, web/src/components/__snapshots__/Counter.test.js.snap, web/src/components/__snapshots__/Demo.test.js.snap, web/src/components/__snapshots__/DevProvider.test.js.snap, web/src/components/__snapshots__/Hello.test.js.snap
upgrades `styled-components` and `rebass` to latest releases (which fixes some bugs and improves performance).
while we're using these libraries (which may not be for too too much longer ;)), we should at least use the latest and greatest...
=> upgrade styled-components, rebass

web/package-lock.json, web/package.json, web/src/components/__snapshots__/App.test.js.snap, web/src/components/__snapshots__/Counter.test.js.snap, web/src/components/__snapshots__/Demo.test.js.snap, web/src/components/__snapshots__/DevProvider.test.js.snap, web/src/components/__snapshots__/Hello.test.js.snap
for some reason, the newer `rebass` / `styled-components` is failing on the production build (though working fine on dev...) i can't figure out exactly why, so let's go back to the versions we were using before 🙄
=> unwind rebass / styled-components upgrade

api/.eslintrc.json, api/package-lock.json, api/package.json, docs/index.md, web/.eslintrc.json, web/package-lock.json, web/package.json
Adds `eslint-config-prettier`; removes now unnecessary rule overrides; updates docs
=> add eslint-config-prettier

web/src/actions/auth.js, web/src/actions/auth.test.js, web/src/containers/Login.js
Closes: https://github.com/18F/cms-hitech-apd/issues/219
=> wires up logout

api/auth/middleware.js, api/auth/serialization.test.js, api/db/authorization.test.js, api/endpoint-tests/roles/post.js, api/routes/activities/index.js, api/routes/activities/openAPI.js, api/routes/index.test.js, api/routes/roles/get.js, api/routes/roles/get.test.js, api/routes/roles/openAPI.js, api/routes/roles/post.js, api/routes/roles/post.test.js, api/routes/roles/put.js, api/routes/roles/put.test.js
Ran prettier on API code and removed [a pointless filter](https://github.com/18F/cms-hitech-apd/pull/223#discussion_r169963499).
- ~~Tests have been updated (and all tests are passing)~~
- ~~The change has been documented~~
- ~~Associated OpenAPI documentation has been updated~~
=> Run prettier on API code

api/endpoint-tests/users/put.js, api/routes/users/put.js, api/routes/users/put.test.js, web/src/actions/user.js, web/src/actions/user.test.js, web/src/components/App.js, web/src/components/FormStateStart.js, web/src/components/PageNavButtons.js, web/src/components/__snapshots__/App.test.js.snap, web/src/containers/StateStart.js, web/src/reducers/auth.js, web/src/reducers/index.js, web/src/reducers/index.test.js, web/src/reducers/user.js, web/src/reducers/user.test.js
Alright, this isn't close to perfect, but it's working and probably good enough for initial review. It fetches user (profile) data from api, populates form, and updates info upon form submission.
(FYI, the user reducer is especially raw.)
=> state profile w/ real data

bin/deploy-ux-testing.sh, bin/deploy.sh
Currently, the development and testing database seed files are pushed to both staging and UX testing.  That's potentially dangerous because those seed files will create admin user accounts with weak credentials.  If someone accidentally ran them, the system would be very easy to compromise.  This PR updates our deploy scripts to delete those files before deploying the app.
For the UX testing environment, deployments currently do not erase any data from the database.  This could create an unexpected UX testing situation where today's user is seeing yesterday's user's inputs.  To help prevent that, this PR now completely deletes the database service from the UX testing environment and re-adds it before deploying the app.  It then runs migrations and seeds as normal, building a fresh and …
=> Safer staging deploy, cleaner UX testing deploy

api/db/user.js, api/db/user.test.js
Not 100% I did this properly 😬
=> add user-state relation in bookshelf model

package-lock.json, web/package-lock.json, web/package.json, web/src/components/App.js, web/src/components/Container.js, web/src/components/Routes.js, web/src/components/Sidebar.js, web/src/components/Wrapper.js, web/src/components/__snapshots__/App.test.js.snap, web/src/components/withSidebar.js, web/src/containers/AuthChecker.js, web/src/containers/Login.js, web/src/containers/TopNav.js, web/src/styles/app/border.css, web/src/styles/app/layout.css, web/src/styles/index.css
This is a quick iteration on improving sidebar stylez (a la https://github.com/18F/cms-hitech-apd/issues/188#issuecomment-370439011)
It's not pixel perfect, but it's a lot better than it was.
Also removed `react-xray` (which wasn't proving to be useful although it was pretty).
Preview:
=> sidebar stylez

api/db/apd.js, api/db/apd.test.js, api/migrations/20180307075942_add-apd-model.js
Adds migration and bookshelf model
=> add apd model

api/db/activity.js, api/db/activity.test.js, api/db/index.js, api/migrations/20180307122428_add-activities-model.js
=> add activity model

web/package-lock.json, web/package.json, web/webpack.config.js
Putting bundle.js on a diet. (https://webpack.js.org/guides/tree-shaking/)
The kbs are now melting away (2.4MB to 864kB when run on dev, which doesn't include other "production" build optimizations)
=> add UglifyJS

web/src/components/Hello.js, web/src/components/Hello.test.js, web/src/components/__snapshots__/Hello.test.js.snap
Uses `Container` wrapper which includes a wonderfully minimal header
=> add Container to homepage

api/db/apd.js, api/db/apd.test.js, api/db/state.js, api/db/state.test.js, api/routes/apds/get.js, api/routes/apds/get.test.js, api/routes/apds/index.js, api/routes/apds/index.test.js, api/routes/apds/openAPI.js, api/routes/index.js, api/routes/index.test.js, api/routes/openAPI/index.js
Adds `/apds` GET request; updates relationship between APDs and states
=> start APD endpoints

api/auth/serialization.js, api/auth/serialization.test.js, api/db/user.js, api/db/user.test.js, api/routes/apds/get.js, api/routes/apds/get.test.js
* Adds state to `req.user`
* Adds `apds` method to user model (will come in handy soon)
* Refactors related code
=> augment req.user and user model

api/routes/states/put.js, api/routes/states/put.test.js, web/src/components/FormApdOverview.js, web/src/containers/ApdOverview.js, web/src/containers/ApdOverview.test.js, web/src/containers/__snapshots__/ApdOverview.test.js.snap
Allows user to add/edit/save their program vision and benefits.
=> wire up apd overview front-end

docs/index.md
Add a little paragraph around a11y testing (cc: @nkkl)
=> docs update around a11y

api/migrations/20180319105352_add-expenses.js
`expenses` and `activity_expenses`
=> add expense table(s)

api/db/activity.js, api/db/activity.test.js, api/migrations/20180319105352_add-expenses.js, api/package.json
Adds `apdActivityExpense` to `db/activity`
=> add expenses to db/activity

api/db/expense.js, api/db/expense.test.js, api/package.json
=> adds expense bookshelf model

api/db/activity.js, api/endpoint-tests/activities/put.js, api/endpoint-tests/apds/get.js, api/routes/apds/activities/expenses/openAPI.js, api/routes/apds/activities/expenses/put.js, api/routes/apds/activities/index.js, api/routes/apds/activities/index.test.js
Endpoint for adding expenses and expense entries
Needs tests...
=> add expense endpoint

api/db/activity.js, api/db/activity.test.js, api/migrations/20180330162800_add-activity-schedule.js
Adds a DB migration and updates the activity model.
=> Adds the DB components to support activity schedules

web/src/components/PoC.js
Changed "activity type" from radio (select 1) to checkboxes (select 1+)
Preview:
=> activity type -- radio to checkboxes

web/src/components/FormActivityApproach.js, web/src/components/FormActivitySchedule.js, web/src/components/PoC.js, web/src/styles/app/layout.css
* consolidates short summary and long description
* simplifies alternative considerations (and moves into description card
* adds "years covered" question (which will drive personnel, contractors, expense by-year columns)
=> refine poc

web/src/components/Collapsible.js, web/src/components/PoC.js
mainly just adds some tables for state and contractor people per activity
=> add personnel tables

web/src/components/Collapsible.js, web/src/components/PoC.js, web/src/styles/app/type.css
Adds remaining section shells for state submission page
Preview:
=> add more sections

api/db/activity/activity.js, api/endpoint-tests/activities/put.js, api/migrations/20180420140208_other-funding-sources.js, api/routes/openAPI/index.js
* Creates a database migration to add `other_funding_sources_description` and `other_funding_sources_amount` columns to the activities table.
* Updates the activity model to accept an `otherFundingSources` object for inserts/updates
* adds a `format` method to map the `otherFundingSources` object to the column names
* updates the `toJSON` method to map the table data into the `otherFundingSources` object
* Updates the OpenAPI definition of the activity object to include the `otherFundingSources` object
Closes #374.
=> Add "other funding sources" to the activity data model

web/src/actions/activities.js, web/src/containers/ActivityDetailAll.js, web/src/containers/ActivityDetailExpenses.js, web/src/reducers/activities.js
Adds reduxified expenses form to the app
Closes #438
- the `/activities` page now includes an "Expenses" subsection
=> "reduxify" expenses

web/src/components/ActivityDescription.js, web/src/components/CostAllocation.js, web/src/components/FormActivityApproach.js, web/src/components/Inputs2.js, web/src/components/ProgramSummary.js, web/src/containers/ActivityDetailAll.js, web/src/containers/ActivityDetailCostAllocate.js, web/src/containers/ActivityDetailDescription.js, web/src/containers/ActivityDetailSchedule.js, web/src/containers/ActivityDetailStandardsAndConditions.js, web/src/i18n/locales/en.json, web/src/reducers/activities.js, web/src/util/editor.js, web/src/util/index.js
- adds state management for cost allocation and other funding section
- consolidates editor data conversion helpers
- improves naming of optional css class applied to wrapping div of inputs
=> reduxify cost allocation

web/src/actions/activities.js, web/src/containers/ActivityDetailAll.js, web/src/containers/ActivityDetailContractorResources.js, web/src/containers/ActivityDetailStatePersonnel.js, web/src/i18n/locales/en.json, web/src/reducers/activities.js
- reduxifies state personnel section
=> reduxify state personnel

web/src/containers/ActivityDetailContractorResources.js, web/src/containers/ActivityDetailStatePersonnel.js, web/src/i18n/locales/en.json
- updated styles for contractor resource table (it was very close, just needed a `flex-auto` class
=> fix contractor table styles

web/src/components/AssurancesAndCompliance.js, web/src/components/CertifyAndSubmit.js, web/src/components/ExecutiveSummary.js, web/src/components/PoC.js, web/src/components/PreviousActivities.js, web/src/components/ProposedBudget.js, web/src/components/Section.js, web/src/components/Sidebar.js, web/src/components/SidebarLink.js, web/src/containers/Activities.js, web/src/containers/ApdSummary.js, web/src/styles/app/layout.css
- sidebar is now sticky, and scrolls independently of main content
- sidebar links now take you to relevant section when clicked 
Also closes https://github.com/18F/cms-hitech-apd/issues/397
=> sidebar iteration

web/src/components/Section.js, web/src/components/SidebarLink.js, web/src/containers/Sidebar.js
- on sidebar link click, active state triggered (blue underline)
- doesn't currently handle moving the active state on scroll (yet)
=> sidebar active state

.circleci/config.yml, api/Dockerfile, bin/deploy-storybook.sh, bin/deploy-ux-testing.sh, bin/deploy.sh, web/Dockerfile
Updates dev and CI environment to use npm version 6.x.  This allows us to take advantage of the `npm ci` command immediately, which produces a deterministic dependency install.  In the future, we will also be able to benefit from npm's soon-to-be built-in security checking, as an additional check alongside the static dependency analysis we're currently getting from [Gemnasium](https://gemnasium.com/github.com/18F/cms-hitech-apd).
Closes #453 #454
- …
=> Update build to npm@6

web/src/containers/ApdSummary.js, web/src/i18n/locales/en.json
- fixes: https://github.com/18F/cms-hitech-apd/issues/484
- fixes: https://github.com/18F/cms-hitech-apd/issues/319
=> small fixes

web/src/actions/activities.js, web/src/containers/ActivityDetailGoals.js, web/src/reducers/activities.js
- prefills activity list
- ability to remove goals (if you add more than 1)
cc: @NAretakis
=> usability testing prep

web/src/i18n/locales/en.json
=> Some content changes

web/src/components/Budget.js, web/src/styles/app/spacing.css, web/src/styles/app/table.css
- allows you to toggle visibility of budget row details
Preview:
https://cl.ly/rWUR
=> add expandability to budget rows

.circleci/config.yml, bin/deploy-pr.sh, bin/nightly.sh
Deploys the web app for each pull request, if the web content has changed.  These per-PR deploys will be available online at https://hitech-apd-pr{number}.app.cloud.gov where `{number}`.
Also adds a script that runs nightly to delete any deployments associated with PRs that have been closed or merged.
=> Deploy web app for each pull request

web/src/i18n/locales/en.json
Added text to summary subsection titles, other content changes including additional help text. Removed meeps.
=> Content changes

web/src/components/BudgetSummary.js, web/src/components/QuarterlyBudget.js, web/src/components/Wrapper.js, web/src/components/temp/BudgetPage.js, web/src/styles/app/table.css
This code is a hot mess but its purpose is humble -- to get the ball rolling with this quarterly table so we can see and play around with it on the page with the goal to inform future design/dev iterations of it.
Preview:
=> quarterly budget start

web/src/components/HelpText.js, web/src/containers/ActivityDetailContractorResources.js, web/src/containers/ActivityDetailGoals.js, web/src/containers/ActivityDetailSchedule.js, web/src/containers/ActivityDetailStandardsAndConditions.js, web/src/containers/ActivityDetailStatePersonnel.js
fixes https://github.com/18F/cms-hitech-apd/issues/564
=> subheaders

web/src/containers/ApdSummary.js
resolves https://github.com/18F/cms-hitech-apd/issues/587
=> program summary tweaks

web/src/i18n/locales/en.json
Content changes to reflect tone and voice guidelines, mostly.
=> Voice updates

web/src/components/ProposedBudget.js
Changes the proposed budget collapsible title to better reflect content within this section. Based on IA document changes.
- _Collapsible title="Short Activity Summary Budget"_ changed to _Collapsible title="Proposed Detailed Budget Table"_
=> Change Proposed Budget collapsible title

web/src/i18n/locales/en.yaml
This is just assurances help text. Minor change.
=> Assurances help text

web/src/containers/Login.js, web/src/containers/TopNav.js, web/src/i18n/locales/en.yaml, web/src/index.html, web/src/styles/app/color.css
- adds analytics scripts
- fixes top nav if place is not known
- better styling for login page
resolves https://github.com/18F/cms-hitech-apd/issues/620
preview:
https://cl.ly/rxoS
=> add analytics, etc

web/src/actions/apd.js, web/src/containers/ActivityDetailAll.js, web/src/containers/ActivityListEntry.js, web/src/containers/BudgetSummary.js, web/src/reducers/activities.js, web/src/util/index.js
- one funding source per activity (checkboxes to radio buttons)
resolves https://github.com/18F/cms-hitech-apd/issues/624
=> one funding source per activity

web/src/i18n/locales/en.yaml
- Made changes to copy to ensure consistency and clarity, consistent with style guidelines.
=> Content edits

web/src/components/ApdApplication.js, web/src/components/ProposedBudget.js, web/src/components/temp/MiscPage.js, web/src/containers/ActivityDetailAll.js, web/src/containers/BudgetSummary.js, web/src/containers/IncentivePayments.js, web/src/containers/Login.js, web/src/i18n/locales/en.yaml, web/src/reducers/apd.js, web/src/reducers/apd.test.js, web/src/styles/app/color.css, web/src/util/formats.js, web/src/util/index.js
preview:
https://cl.ly/s9VY
Closes https://github.com/18F/cms-hitech-apd/issues/532
=> incentive payments table

web/src/actions/activities.test.js, web/src/actions/apd.js, web/src/actions/apd.test.js, web/src/actions/user.test.js, web/src/containers/Activities.js, web/src/containers/Activities.test.js, web/src/containers/__snapshots__/Activities.test.js.snap, web/src/i18n/index.test.js, web/src/reducers/activities.test.js, web/src/reducers/apd.test.js, web/src/reducers/budget.test.js, web/src/reducers/user.test.js, web/src/util/api.test.js, web/src/util/editor.test.js, web/src/util/formats.test.js, web/src/util/index.test.js, web/src/util/masks.test.js
Now that the frontend is settling into a pattern with repeatable chunks of code, it seems like a good time to re-add all those tests we've been skipping.  😬  This PR aims to do that.
Still much to cover, but this is already enormous, so maybe let's not wait...
=> Frontend tests

bin/deploy-pr.sh, web/src/components/temp/MiscPage.js
for those times where you make a change and there are no user facing changes and you want to bypass the pr deployment step, now you can add `[skip deploy]` to the PR title and it **should** do just that 🤞
=> conditional pr deploy; will it work? [skip deploy]

web/src/components/ApdApplication.js, web/src/components/__snapshots__/ApdApplication.test.js.snap, web/src/containers/ScheduleSummary.js, web/src/i18n/locales/en.yaml, web/src/styles/app/table.css
- adds new activity schedule summary section and table (table is not sortable at this time)
resolves https://github.com/18F/cms-hitech-apd/issues/683, https://github.com/18F/cms-hitech-apd/issues/646
=> schedule summary section

web/src/components/temp/MiscPage.js, web/src/containers/ExecutiveSummary.js, web/src/containers/ExecutiveSummaryBudget.js, web/src/i18n/locales/en.yaml, web/src/reducers/activities.js, web/src/reducers/budget.js, web/src/reducers/budget.test.js
- adds executive summary budget tables
resolves: https://github.com/18F/cms-hitech-apd/issues/626
preview:
https://cl.ly/sOqV
=> executive summary budget

api/db/activity/costAllocation.js, api/db/activity/costAllocation.test.js, api/migrations/20180620105436_update-cost-allocation-cols.js, api/routes/openAPI/index.js, web/src/actions/apd.js, web/src/reducers/activities.js, web/src/reducers/activities.test.js
Resolves: https://github.com/18F/cms-hitech-apd/issues/693
=> update names of cost allocation fields

web/src/containers/ApdPreviousActivityTable.js, web/src/containers/PreviousActivities.js, web/src/i18n/locales/en.yaml, web/src/reducers/apd.js, web/src/reducers/apd.test.js, web/src/styles/app/color.css
- previous activity table will exist
- data model for collecting previous activity approved/actual data (#694)
=> Previous activity table

web/src/containers/Landing.js, web/src/styles/app/button.css, web/src/styles/index.css
resolves: https://github.com/18F/cms-hitech-apd/issues/703, https://github.com/18F/cms-hitech-apd/issues/704
preview:
=> better blanding page

web/src/components/ApdApplication.js, web/src/components/Collapsible.js, web/src/components/SectionTitle.js, web/src/components/__snapshots__/ApdApplication.test.js.snap, web/src/components/__snapshots__/Collapsible.test.js.snap, web/src/components/__snapshots__/SectionTitle.test.js.snap, web/src/containers/ActivityDetailAll.js, web/src/containers/Sidebar.js, web/src/containers/TopNav.js, web/src/index.html, web/src/styles/app/button.css, web/src/styles/app/color.css, web/src/styles/app/layout.css, web/src/styles/app/type.css, web/src/styles/index.css
instead of a big, long PR that will take awhile to include everything and be perfect, i'm incrementally incorporating the new styles from latest sketch file; this PR starts with new colors, typography, and font sizes
preview:
=> design re-skin start

web/src/components/HelpText.js, web/src/components/__snapshots__/HelpText.test.js.snap, web/src/components/temp/MiscPage.js, web/src/containers/ApdPreviousActivityTable.js, web/src/containers/AssurancesAndCompliance.js, web/src/containers/BudgetSummary.js, web/src/containers/ExecutiveSummaryBudget.js, web/src/containers/IncentivePayments.js, web/src/containers/QuarterlyBudgetSummary.js, web/src/containers/ScheduleSummary.js, web/src/i18n/locales/en.yaml, web/src/styles/app/base.css, web/src/styles/app/form.css, web/src/styles/app/misc.css, web/src/styles/app/table.css
continuation of design refinement; this one has some misc touchups and tweaks, and starts the work on upgrading our table styles.
there is still more to do and refine with our tables (primarily supporting multiple colors), but they're already looking a lot better so it felt like a good breakpoint to get stuff merged.
preview:
=> table (start) and touchups

web/src/data/assurancesAndCompliance.yaml
Adding reference to 45 CFR 75.326 which is the proper procurement regulation.
=> Updating assurance to 45 CFR 75.326

web/package.json
Credit where credit is due :1st_place_medal:  Updating the contributor list to reflect the changes to the team + without forgetting the contributions from our early teammates.
Updated the contributor list to include new 18F team members (long overdue) + the CMS folks.
- package.json will contain the new team members
- no visual changes
=> Update package.json to reflect the changes to the team

web/src/containers/ExecutiveSummary.js
addresses and closes: https://github.com/18F/cms-hitech-apd/issues/757
not much else to say :)
=> add activity links in Exec Sum

web/src/components/Inputs.js, web/src/components/Section.js, web/src/containers/ActivityDetailGoals.js
addresses and closes https://github.com/18F/cms-hitech-apd/issues/751
=> activity goals: textarea -> richtext

web/src/containers/ActivityListEntry.js, web/src/containers/ExecutiveSummary.js, web/src/i18n/locales/en.yaml
closes: https://github.com/18F/cms-hitech-apd/issues/739
closes: https://github.com/18F/cms-hitech-apd/issues/759
=> add delete activity btn, add total to exec summary entries

web/src/components/HelpText.js, web/src/components/__snapshots__/HelpText.test.js.snap
=> nicer reminder stylez

.circleci/config.yml, api/routes/apds/openAPI.js
There was a bug in the OpenAPI that made it invalid.  This PR fixes that bug, and adds a CI/CD step to validate the OpenAPI so we'll know about problems in the future!
=> OpenAPI fix

web/src/components/SidebarLink.js, web/src/components/__snapshots__/SidebarLink.test.js.snap, web/src/containers/ApdPreviousActivityTableMMIS.js, web/src/containers/Sidebar.js, web/src/styles/app/sidebar.css
* adds a react child key that was missing in one of the tables
* tweaks sidebar
=> sidebar tweaks, fix react child key error [skip deploy]

web/src/containers/__snapshots__/ActivityDetailContractorResources.test.js.snap, web/src/i18n/locales/en.yaml
First part of #734
- Made changes to contract copy to provide consistency with other parts of the application
=> Contract content

web/src/i18n/locales/en.yaml
- #776 Made changes to key cost allocation section
=> Key Cost Allocation content

web/src/components/Collapsible.js, web/src/components/__snapshots__/Collapsible.test.js.snap, web/src/components/__snapshots__/Section.test.js.snap, web/src/containers/ActivityDetailAll.js, web/src/containers/__snapshots__/ActivityDetailAll.test.js.snap, web/src/styles/app/color.css
closes https://github.com/18F/cms-hitech-apd/issues/754
preview:
would tag @lauraponce for a review, but i know she's out of town and there's not much to this :)
=> activity section colorz

web/src/reducers/activities.js, web/src/reducers/activities.test.js
- the "Program Administration" activity will be expanded by default
=> Default program admin activity to open

api/auth/authenticate.js, api/auth/authenticate.test.js, api/endpoint-tests/auth/login.js
fixes: https://github.com/18F/cms-hitech-apd/issues/808
email is now case insensitive when logging in; password remains case-sensitive (as it should)
=> fix email case-ness for auth

web/src/i18n/locales/en.yaml
- Small change of Certify and Submit header
=> Submission content fix

web/src/components/DeleteConfirm.js, web/src/components/Select.js, web/src/components/__snapshots__/Select.test.js.snap, web/src/containers/ActivityDetailContractorResources.js, web/src/containers/__snapshots__/ActivityDetailContractorResources.test.js.snap, web/src/i18n/locales/en.yaml, web/src/styles/app/confirm.css
* adds accompanying document type for each uploaded file (right now options are "Contract" or "RFP")
* adds ability to remove an uploaded file
Addresses and closes https://github.com/18F/cms-hitech-apd/issues/840
=> add doc category, remove functionality

web/src/components/StateDash.js
Changes state dashboard statuses placeholder button from _Respond_ to _View_
closes #841
=> Dash Statuses Button Change to `View`

web/src/components/SidebarLink.js, web/src/components/__snapshots__/SidebarLink.test.js.snap, web/src/containers/ActivityDetailContractorResources.js, web/src/containers/Login.js, web/src/containers/QuarterlyBudgetSummary.js, web/src/containers/Sidebar.js
finally used our cool `tota11y` tool and fixed the flagged issues. there were not nearly as many issues as i expected, which was a fun surprise.
=> fix 508 issues

web/src/actions/apd.js, web/src/actions/apd.test.js, web/src/containers/IncentivePayments.js, web/src/util/serialization/activities.js, web/src/util/serialization/activities.test.js
The contractor hourly data was improperly being initialized / set.
=> fix contractor hourly data error

.github/ISSUE_TEMPLATE.md
Updated issue template to reflect our current process for adding labels, milestones, and project.
=> Updated Issue Template to Match Process

.github/ISSUE_TEMPLATE.md
Didn't like how the formatting worked/looked for issues. This fixes it.
=> Issue template readability fix

web/src/components/Collapsible.js, web/src/components/__snapshots__/Collapsible.test.js.snap, web/src/containers/ActivityDetailContractorResources.js, web/src/containers/ActivityDetailCostAllocateFFP.js, web/src/containers/ActivityDetailDescription.js, web/src/containers/ActivityDetailExpenses.js, web/src/containers/ActivityListEntry.js, web/src/containers/IncentivePayments.js, web/src/containers/__snapshots__/ActivityDetailContractorResources.test.js.snap, web/src/containers/__snapshots__/ActivityDetailCostAllocateFFP.test.js.snap, web/src/styles/app/table.css
Fixed all of the errors identified by HTML_CodeSniffer except the ones related to td/header relationship.  It's not that they're not fixable - it's that a bug in HTML_CodeSniffer identifies false positives after I fix them.  Will have another PR for them later.
=> More accessibility fixes

web/src/components/StateDash.js
Updating Fake Dashboard Data with more Realistic Fake Data. Let's see how this works.
- Status Updates in "My Tasks" is more in alignment with options
- "Current Statuses" show a little more variety in content
=> Update StateDash.js with better fake data

web/src/components/Collapsible.js, web/src/components/__snapshots__/Collapsible.test.js.snap, web/src/styles/app/misc.css
addresses and closes: https://github.com/18F/cms-hitech-apd/issues/909
=> tweak collapsible focus state

web/src/components/HelpText.js, web/src/components/__snapshots__/HelpText.test.js.snap
allows for line breaks in helptext by utilizing markdown conversion
resolves: https://github.com/18F/cms-hitech-apd/pull/921
cc: @quarterback
=> markdowns the helptexts

web/src/components/SidebarLink.js, web/src/components/__snapshots__/SidebarLink.test.js.snap, web/src/styles/app/sidebar.css
the sidebar was looking wonky on small screens and now it doesn't.
before:
after:
=> fix sidebar sm screen wonkiness

web/src/i18n/locales/en.yaml
This just changes the spacing (in theory) for the various sections with globs of content. Also, fixes some of the numbering. 
- References issue (#921)
=> Paragraph spacing

web/src/containers/activity/StandardsAndConditions.js, web/src/i18n/locales/en.yaml, web/src/styles/app/base.css
This just changes the spacing (in theory) for the various sections with globs of content. Also, fixes some of the numbering. 
- References issue (#921)
=> Paragraphs

api/routes/apds/versions/post.js, api/routes/apds/versions/post.test.js
=> Save activities when submitting an APD

web/src/containers/ScheduleSummary.js, web/src/reducers/activities.js, web/src/reducers/activities.test.js
this fixes the activity milestone (name related) issues that @NAretakis identified yesterday.
=> fix activity milestone / schedule names

web/src/i18n/locales/en.yaml
=> Legacy microcopy cleanup

web/src/containers/AssurancesAndCompliance.js, web/src/i18n/locales/en.yaml
* change radios to yes/no buttons, adds help text
* for now, i kept with the black/white pattern of our existing yes/no buttons, but happy to change those all to a different color scheme in another PR
addresses and closes: https://github.com/18F/cms-hitech-apd/issues/911
=> citation tweaks

web/src/reducers/budget.js, web/src/reducers/budget.test.js
Per discussion on Slack, this unit test corrects the Unit Test for the FFY Budget Table Totals column
- FFY totals by quarter should now add up to the correct value (instead of double their correct value)
=> Updates unit test for FFY Budget Table

web/src/containers/activity/StatePersonnel.js, web/src/util/formats.js
very similar to what was done with expenses
preview:
=> state personnel - small entries

web/src/components/StateDash.js, web/src/components/temp/MiscPage.js, web/src/containers/activity/CostAllocateFFP.js, web/src/containers/activity/Costs.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/Expenses.js, web/src/containers/activity/StatePersonnel.js, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/i18n/locales/en.yaml, web/src/reducers/budget.js, web/src/reducers/budget.test.js, web/src/styles/app/type.css, web/src/util/formats.js
closes: https://github.com/18F/cms-hitech-apd/issues/970
=> combines personnel, expenses into 1 section

web/src/util/serialization/activities.js, web/src/util/serialization/activities.test.js
fixes FTE percent -> number math related to changes made in https://github.com/18F/cms-hitech-apd/pull/983
=> fix fte math

web/src/i18n/locales/en.yaml
Removed redundancies and legacy copy from latest edition of text.
- Solves issue #986
=> Help text revisions

web/src/components/ApdStateProfile.js, web/src/components/Collapsible.js, web/src/components/HelpText.js, web/src/components/SidebarLink.js, web/src/components/__snapshots__/Collapsible.test.js.snap, web/src/components/__snapshots__/HelpText.test.js.snap, web/src/components/__snapshots__/SidebarLink.test.js.snap, web/src/containers/Sidebar.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/reducers/sidebar.js, web/src/reducers/sidebar.test.js, web/src/styles/app/alert.css, web/src/styles/index.css
Addresses and closes: https://github.com/18F/cms-hitech-apd/issues/861
Re: sidebar, now when you click on a top-level section, it brings you to that content section AND auto-expands the dropdown.
=> small ui refinements

web/src/components/MiniHeader.js, web/src/containers/activity/ContractorResources.js, web/src/containers/activity/Expenses.js, web/src/containers/activity/Goals.js, web/src/containers/activity/StatePersonnel.js, web/src/containers/activity/__snapshots__/ContractorResources.test.js.snap, web/src/i18n/locales/en.yaml
Closes #988 
- The goals and objectives under the "Performance Measures and Benchmarks" section are under the happy little blue collapsible sections just like personnel/non-personnel/contractor expenses.
=> Put goals and objectives under little collapsible sections too!

web/src/containers/QuarterlyBudgetSummary.js
We had some legacy stuff in quarterly budget that's no longer used / needed (and it was also through a props error in console) -- this resolves that :)
=> fix quarterly budget console error

.circleci/config.yml, bin/deploy-pr.sh, web/src/components/Icons.js, web/src/components/SidebarLink.js, web/src/components/StateDash.js, web/src/components/StateDashboard.js, web/src/components/__snapshots__/Routes.test.js.snap, web/src/components/__snapshots__/SidebarLink.test.js.snap, web/src/constants.js, web/src/containers/StateDashboardCurrentDocuments.js, web/src/containers/StateDashboardSidebar.js, web/src/containers/TopBtns.js, web/src/routes.js
Addresses #722.
- updates the dashboard
- hooks up the dashboard to the real list of APDs, at least nominally
=> Implement state dashboard refinements

web/src/actions/apd.js, web/src/actions/apd.test.js, web/src/components/submission/AlreadySubmitted.js, web/src/components/submission/Submit.js, web/src/components/submission/Withdraw.js, web/src/containers/CertifyAndSubmit.js, web/src/i18n/locales/en.yaml, web/src/reducers/apd.js, web/src/reducers/apd.test.js
Closes #849 
- adds the APD submission withdrawal experience
=> APD submission withdrawal frontend

web/src/i18n/locales/en/activities/overview.yaml, web/src/reducers/activities.test.js, web/src/reducers/apd.test.js
Carried over from #1022.  It was easier to do this than to "fix" the other branch.  😄
- Adds help text id and help text (tbd) to the brief activity summary subsection.
=> Update content (from #1022)

README.md
The documentation doesn't say anything about creating or seeding the database when using Docker.  That's an important step.  It also doesn't list the dev username/password.
- both of ☝️ those things
=> Update documentation for dev in Docker

web/src/i18n/locales/en/activities/contractorResources.yaml, web/src/i18n/locales/en/activities/costAllocate.yaml, web/src/i18n/locales/en/activities/overview.yaml, web/src/i18n/locales/en/activities/standardsAndConditions.yaml, web/src/i18n/locales/en/apd/apd.yaml, web/src/i18n/locales/en/apd/stateProfile.yaml, web/src/i18n/locales/en/certifyAndSubmit.yaml
This pull request addresses #1023
These indentations are leading to improper line breaks. Removing them lets the text break at its natural point instead.
=> Remove hanging indentations in copy from yaml

web/package.json
Credit where credit is due. Updating our team member listing (I think I got everyone). Small update, but important to remember who's been a part of this journey.
- No visual changes. This updates the contributor list to the package.json file.
=> Updates Contributors with new team members!

README.md, docs/deployment.md, docs/frontend-build.md, docs/index.md, docs/testing.md, web/webpack.config.js
Refreshed some documentation
- mainly the README
- just some code formatting changes in some of the other files
=> Documentation updates

bin/cleanup-pr-deploys.sh
Fixes the PR deploy cleanup
- nothing visible
=> Really really big pull request that will take a long, long time to review, but should hopefully fix our broken PR deploy cleanup

bin/deploy.sh
Don't push staging to S3 for now, we're not ready for that
- deployments will work again
=> Deploy fix

web/src/containers/__snapshots__/Sidebar.test.js.snap, web/src/i18n/locales/en/activities/costAllocate.yaml, web/src/i18n/locales/en/apd/stateProfile.yaml, web/src/i18n/locales/en/executiveSummary.yaml
These are very small style compliance things that jumped out at me after I merged my last PR into master.
=> A few fixes I should have caught earlier

docs/frontend-build.md, docs/index.md
Fills in more information about our build and updates the overview in the index.
- fixes up documentation
=> Update documentation about our build

api/package.json, web/package.json
Update contributor lists to include @austinhernandez! 🎉
- Everything. Absolutely everything.
- it literally _is_ documentation
=> Add Austin to contributors lists

.github/ISSUE_TEMPLATE.md
Modifying the issue template to reflect our Zenhub processes.
=> Update to issue template for Zenhub

web/src/components/Header.js, web/src/components/PasswordWithMeter.js, web/src/components/PasswordWithMeter.test.js, web/src/components/__snapshots__/PasswordWithMeter.test.js.snap, web/src/containers/Login.js, web/src/containers/Login.test.js, web/src/containers/__snapshots__/Login.test.js.snap, web/src/containers/admin/MyAccount.js, web/src/containers/admin/__snapshots__/MyAccount.test.js.snap, web/src/styles/app/base.css, web/src/styles/index.scss, web/src/styles/scss/card.scss, web/src/styles/scss/password-meter.scss, web/src/styles/scss/section.scss
Closes #1376.
- Tweaks card layout format
- Factors header into its own component
- Makes password strength meter optional in password component
=> Switch login page to design system

web/src/containers/ApdStateProfileMedicaidOffice.js, web/src/containers/ApdStateProfileMedicaidOffice.test.js, web/src/containers/__snapshots__/ApdStateProfileMedicaidOffice.test.js.snap, web/src/i18n/locales/en/apd/stateProfile.yaml, web/src/styles/scss/forms.scss
Implements #1331 
- switches from custom input types to CMS DS `<TextField>`
- switches "state" from text box to dropdown box
- removes ace-css classes
=> Implement design system for Medicaid director/office section

web/src/components/Dollars.test.js, web/src/components/PasswordWithMeter.test.js, web/src/components/__snapshots__/PasswordWithMeter.test.js.snap, web/src/containers/ApdApplication.test.js, web/src/containers/BudgetSummary.test.js, web/src/containers/__snapshots__/ApdApplication.test.js.snap, web/src/containers/__snapshots__/BudgetSummary.test.js.snap, web/src/containers/activity/All.js, web/src/containers/activity/CostAllocateFFPQuarterly.js, web/src/containers/activity/__snapshots__/All.test.js.snap, web/src/containers/admin/EditAccount.js, web/src/containers/admin/MyAccount.test.js, web/src/lazy/__mocks__/zxcvbn.js, web/src/reducers/navigation.js, web/src/reducers/navigation.test.js, web/src/util/editor.test.js
This PR addresses some runtime warnings from React as well as some tests that were causing minor problems (that would eventually become breaking issues).
=> Minor fixes

web/src/containers/SaveButton.js, web/src/containers/__snapshots__/SaveButton.test.js.snap, web/src/styles/scss/save-button.scss
Just a few tweaks to the div structure for #1467.
=> Patch for #1467

web/src/containers/AssurancesAndCompliance.js, web/src/containers/AssurancesAndCompliance.test.js, web/src/containers/__snapshots__/AssurancesAndCompliance.test.js.snap, web/src/i18n/locales/en/assurancesAndCompliance.yaml, web/src/util/serialization/apd.js
=> Update section 7 (assurances and compliance) to use design system

web/src/containers/ApdPreviousActivityTable.js, web/src/containers/ApdPreviousActivityTableMMIS.js, web/src/containers/ApdPreviousActivityTableTotal.js, web/src/containers/PreviousActivities.js, web/src/containers/__snapshots__/ApdPreviousActivityTable.test.js.snap, web/src/containers/__snapshots__/ApdPreviousActivityTableMMIS.test.js.snap, web/src/containers/__snapshots__/ApdPreviousActivityTableTotal.test.js.snap, web/src/containers/__snapshots__/PreviousActivities.test.js.snap, web/src/styles/scss/forms.scss
Closes #1445. 
- Makes headings in this section the right semantic level + style
- Removes a bunch of old atomic styles + markup we don't need
- RTE border
=> Update previous activities headings

web/src/components/Wrapper.js, web/src/components/__snapshots__/Wrapper.test.js.snap, web/src/containers/admin/AdminDashboard.js, web/src/styles/app/layout.css, web/src/styles/scss/card.scss, web/src/styles/scss/layout.scss
All the pages have footers now! yay!
- Adds the footer to the `Wrapper` element so all pages inherit it
- Removes footer from files it previously existed in.
=> Add footer to wrapper

web/src/containers/ScheduleSummary.js, web/src/containers/ScheduleSummary.test.js, web/src/containers/__snapshots__/ScheduleSummary.test.js.snap, web/src/reducers/activities.selectors.js
- Switches the activity schedule summary table to a regular table
- Groups milestones under activities
- Sorts milestones by end date
- closes #1446
=> Restructure activity schedule table

web/src/containers/SaveButton.js, web/src/containers/__snapshots__/SaveButton.test.js.snap
=> Make save button only visible on screen, not in print

docker-compose.yml, web/package-lock.json, web/src/containers/ApdExport.js, web/src/containers/__snapshots__/ApdExport.test.js.snap
Closes #1256
The copy in the Export section. This covers the fact that exporting is the correct action for _both_ submission and any kind of printed or local review.
I’m going to put a screenshot in the next comment here of what it looks like, because I think the button is a little strong, but if other people are okay with it we are ready to go.
=> New export language

web/src/i18n/locales/en/activities/standardsAndConditions.yaml
- adds line breaks to standards and conditions yaml
=> Add line breaks to standards and conditions

web/src/containers/ScheduleSummary.js, web/src/containers/__snapshots__/ScheduleSummary.test.js.snap, web/src/styles/scss/tables.scss
=> Patch for #1597

web/src/components/Footer.js
Hides footer in print
- hides footer in print
=> Hide footer in print

web/src/styles/scss/print.scss
- removes border around rich text element
- removes min-height on rich text
=> Fix border and spacing on rich text fields

api/.snyk, web/.snyk
- instruct snyk to temporarily ignore lodash vuln
=> Ignore lodash prototype pollution for now

web/src/styles/scss/print.scss
=> Make numbered sections readable in print

web/src/components/Review.js, web/src/components/__snapshots__/Review.test.js.snap, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/styles/scss/forms.scss, web/src/styles/scss/print.scss
Just a couple changes to tweak label margin and move around a print-hidden thing.
=> Tiny print tweaks

.circleci/config.yml, bin/preview-deploy/aws.cleanup.sh, bin/preview-deploy/aws.sh, bin/prod-deploy/aws.sh, bin/prod-deploy/aws.user-data.sh
- commits to master deploy to the `staging` environment
- tags on master deploy to the `production` environment
- deployments tag themselves in AWS with their environment to find them more easily
- renames environment variables to hopefully make them make semantic sense
- `{ENVIRONMENT}_{TARGET}_{NAME}`
- where `ENVIRONMENT` is `PRODUCTION`, `STAGING`, etc.
- where `TARGET` is `API` or `WEB`
- variable names related to AWS config start with `AWS_`
- eg:
- `PRODUCTION_API_AWS_AMI`
- `PRODUCTION_API_PORT`
- `STAGING_WEB_API_URL`
Remove these environment variables from CircleCI config:
=> Deployment switcharoo

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
- Adds a `CHANGELOG.md`
- Updates the PR template to include a checkmark for updating the changelog
=> Add a changelog and update the PR template

CHANGELOG.md, web/src/reducers/activities.js, web/src/reducers/activities.test.js
- when you add a new contractor, the contractor form is expanded
- closes #1710
=> Expand new contractors

CHANGELOG.md, web/src/styles/scss/layout.scss
- sets a max height on the navigation bar and makes it scrollable
- closes #1475
=> Make the navigation sidebar scrollable

CHANGELOG.md, web/src/containers/AriaAnnounce.js, web/src/containers/__snapshots__/AriaAnnounce.test.js.snap
@mgwalker discovered I forgot to actually hide the ARIA region from #1731 from sighted users. This does that.
=> ARIA region announcement shouldn't be visible

CHANGELOG.md, web/src/components/RichText.js
- just what it says on the tin
- closes #1769
=> Enable spellcheck for rich text editor

api/migrations/20190924152054_ensure-key-personnel-costs-exist.js, docker-compose.yml, web/package-lock.json, web/package.json, web/src/actions/editApd.js, web/src/actions/editApd.test.js, web/src/containers/ApdKeyPerson/ApdKeyPersonForm.js, web/src/containers/ApdKeyPerson/ApdKeyPersonForm.test.js, web/src/containers/ApdKeyPerson/__snapshots__/ApdKeyPersonForm.test.js.snap, web/src/containers/ApdStateKeyPersonnel.js, web/src/containers/ApdStateKeyPersonnel.test.js, web/src/containers/ApdStateProfileMedicaidOffice.js, web/src/containers/ApdStateProfileMedicaidOffice.test.js, web/src/containers/__snapshots__/ApdStateKeyPersonnel.test.js.snap, web/src/containers/__snapshots__/ApdStateProfileMedicaidOffice.test.js.snap, web/src/reducers/apd.js, web/src/reducers/apd.test.js, web/src/reducers/index.js, web/src/reducers/index.test.js, web/src/reducers/patch.js, web/src/reducers/patch.test.js, web/src/util/serialization/apd.js, web/src/util/serialization/apd.test.js
This one builds on #1831, so there's stuff here that's also there. Hopefully the overlapping parts will go away after that one is merged and I rebase. 🤞
- closes #1832
=> Build JSON patch for APD key personnel

api/routes/apds/__snapshots__/post.endpoint.js.snap, web/src/actions/editActivity/index.js, web/src/actions/editActivity/overview.js, web/src/actions/editActivity/overview.test.js, web/src/actions/editActivity/symbols.js, web/src/containers/ExecutiveSummary.test.js, web/src/containers/ScheduleSummary.test.js, web/src/containers/Sidebar.test.js, web/src/containers/__snapshots__/ApdApplication.test.js.snap, web/src/containers/activity/ActivityContext.js, web/src/containers/activity/All.js, web/src/containers/activity/All.test.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/EntryDetails.test.js, web/src/containers/activity/NameAndFundingSource/NameAndFundingSourceForm.js, web/src/containers/activity/NameAndFundingSource/NameAndFundingSourceForm.test.js, web/src/containers/activity/NameAndFundingSource/__snapshots__/NameAndFundingSourceForm.test.js.snap, web/src/containers/activity/Overview.js, web/src/containers/activity/__snapshots__/All.test.js.snap, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/reducers/activities.js, web/src/reducers/activities.selectors.js, web/src/reducers/apd.js, web/src/reducers/budget.js, web/src/reducers/budget.selectors.js, web/src/reducers/budget.test.js
- begins migrating the application state from using key-based activities to index-based activities
- introduces a context for tracking which activity a component is tied to, rather than passing that information down over and over and over again
- JSON-patchifies adding and removing activities, as well as updating their names and funding sources
- closes #1835
=> JSON patch the activity list

web/src/actions/editActivity/contractorResources.js, web/src/actions/editActivity/contractorResources.test.js, web/src/actions/editActivity/index.js, web/src/containers/activity/ActivityContext.js, web/src/containers/activity/ContractorResource/ContractorResourceForm.js, web/src/containers/activity/ContractorResource/ContractorResourceForm.test.js, web/src/containers/activity/ContractorResource/__snapshots__/ContractorResourceForm.test.js.snap, web/src/containers/activity/ContractorResources.js, web/src/containers/activity/ContractorResources.test.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/Overview.js, web/src/containers/activity/__snapshots__/ContractorResources.test.js.snap, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/reducers/activities.js, web/src/reducers/activities.selectors.js, web/src/reducers/apd.js
=> JSON patch activity contractor resources

web/src/actions/editActivity/contractorResources.js, web/src/actions/editActivity/overview.js, web/src/actions/editApd/incentivePayments.js, web/src/actions/editApd/keyPersonnel.js, web/src/actions/editApd/overview.js, web/src/actions/editApd/previousActivities.js, web/src/actions/editApd/stateProfile.js
To make the actions easier to use, add JSDoc comments to them.
=> Add JSDoc to new actions

web/src/actions/editActivity/activityList.js, web/src/actions/editActivity/activityList.test.js, web/src/actions/editActivity/index.js, web/src/actions/editActivity/overview.js, web/src/actions/editActivity/overview.test.js, web/src/containers/activity/Overview.js, web/src/containers/activity/Overview.test.js, web/src/containers/activity/__snapshots__/Overview.test.js.snap
Another section down!
- closes #1836
=> JSON patchify activity overview/summary section

api/schemas/apd.json, web/src/actions/editActivity/index.js, web/src/actions/editActivity/scheduleAndMilestones.js, web/src/actions/editActivity/scheduleAndMilestones.test.js, web/src/components/DateField.js, web/src/components/DateField.test.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/Milestone/MilestoneForm.js, web/src/containers/activity/Milestone/MilestoneForm.test.js, web/src/containers/activity/Schedule.js, web/src/containers/activity/Schedule.test.js, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/containers/activity/__snapshots__/Schedule.test.js.snap, web/src/reducers/activities.js, web/src/reducers/apd.js, web/src/reducers/apd.test.js
=> JSON patchify activity schedule and milestones

api/schemas/apd.json, web/src/actions/editActivity/index.js, web/src/actions/editActivity/statePersonnel.js, web/src/actions/editActivity/statePersonnel.test.js, web/src/containers/activity/Costs.js, web/src/containers/activity/Costs.test.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/StatePerson/StatePersonForm.js, web/src/containers/activity/StatePerson/StatePersonForm.test.js, web/src/containers/activity/StatePersonnel.js, web/src/containers/activity/StatePersonnel.test.js, web/src/containers/activity/__snapshots__/Costs.test.js.snap, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/containers/activity/__snapshots__/StatePersonnel.test.js.snap, web/src/reducers/activities.js, web/src/reducers/activities.selectors.js, web/src/reducers/apd.js, web/src/reducers/apd.test.js
=> JSON patchify the state personnel section

web/src/actions/editActivity/index.js, web/src/actions/editActivity/nonPersonnelCosts.js, web/src/actions/editActivity/nonPersonnelCosts.test.js, web/src/containers/activity/Costs.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/NonPersonnelCost/NonPersonnelCostForm.js, web/src/containers/activity/NonPersonnelCost/NonPersonnelCostForm.test.js, web/src/containers/activity/NonPersonnelCosts.js, web/src/containers/activity/NonPersonnelCosts.test.js, web/src/containers/activity/__snapshots__/Costs.test.js.snap, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/containers/activity/__snapshots__/NonPersonnelCosts.test.js.snap, web/src/reducers/activities.js, web/src/reducers/activities.selectors.js, web/src/reducers/apd.js, web/src/reducers/apd.test.js
=> JSON-patchify non-personnel costs

web/src/actions/editActivity/index.js, web/src/actions/editActivity/standardsAndConditions.js, web/src/actions/editActivity/standardsAndConditions.test.js, web/src/containers/activity/EntryDetails.js, web/src/containers/activity/StandardsAndConditions.js, web/src/containers/activity/StandardsAndConditions.test.js, web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap, web/src/containers/activity/__snapshots__/StandardsAndConditions.test.js.snap
=> JSON patchify activity standards and conditions

web/src/actions/editActivity/costAllocate.js, web/src/actions/editActivity/costAllocate.test.js, web/src/containers/activity/CostAllocate.js, web/src/containers/activity/CostAllocateFFP.js, web/src/containers/activity/CostAllocateFFP.test.js, web/src/containers/activity/__snapshots__/CostAllocate.test.js.snap, web/src/containers/activity/__snapshots__/CostAllocateFFP.test.js.snap, web/src/reducers/activities.selectors.js
=> JSON patch cost allocation FFP

api/schemas/apd.json, web/src/actions/editActivity/costAllocate.js, web/src/actions/editActivity/costAllocate.test.js, web/src/containers/activity/CostAllocateFFP.js, web/src/containers/activity/CostAllocateFFPQuarterly.js, web/src/containers/activity/CostAllocateFFPQuarterly.test.js, web/src/containers/activity/CostAllocateFFPYearTotal.js, web/src/containers/activity/__snapshots__/CostAllocateFFP.test.js.snap, web/src/containers/activity/__snapshots__/CostAllocateFFPQuarterly.test.js.snap, web/src/containers/activity/__snapshots__/CostAllocateFFPYearTotal.test.js.snap
=> JSON patchify quarterly FFP table

CHANGELOG.md, api/docker-compose.endpoint-tests.yml, api/package-lock.json, docker-compose.yml, web/package-lock.json
The vulnerable dependencies are blocking a new production deployment. 😬
- updates vulnerable dependencies
=> Update vulnerable dependencies

CHANGELOG.md
- gets changelog cleaned up for the next release
=> Prep changelog for next release

.circleci/config.yml
There's a typo in the CircleCI job script that does backend deployments, so it doesn't deploy.
- fixes the typo
- deploys
=> Fix deploy job

CHANGELOG.md
- marks 2.2.0 release and date
- makes space for the next release
=> Get changelog ready for next release

CHANGELOG.md, web/src/containers/activity/NameAndFundingSource/NameAndFundingSourceReview.js, web/src/containers/activity/NameAndFundingSource/NameAndFundingSourceReview.test.js, web/src/containers/activity/NameAndFundingSource/__snapshots__/NameAndFundingSourceReview.test.js.snap, web/src/containers/activity/__snapshots__/All.test.js.snap
- updates the activity list
- removes the "Remove" button
- the edit button still expands the form to edit the activity name and funding type; #1943 will rewire thee dit button to open the activity in the modal window
- closes #1942
- ~Associated OpenAPI documentation has been updated~ N/A
=> Update activity list

CHANGELOG.md
- added next release to the top of the changelog
- added anticipated release date
- tagged previous release with version and release date
=> Prepare changelog for next release

CHANGELOG.md, bin/headers-production.lambda.js, bin/headers-staging.lambda.js
These are the Lambda functions deployed for our staging and production environments to write browser security headers to the frontend.
- adds Lambda function code
- ~Tests have been updated (and all tests are passing)~ N/A
- ~Associated OpenAPI documentation has been updated~ N/A
=> Lambda functions for security headers

CHANGELOG.md, web/src/containers/activity/CostAllocateFFP.js, web/src/containers/activity/CostAllocateFFPYearTotal.js, web/src/containers/activity/__snapshots__/CostAllocateFFPYearTotal.test.js.snap, web/src/containers/viewOnly/Apd.js, web/src/containers/viewOnly/ApdStateProfile.js, web/src/containers/viewOnly/ApdSummary.js, web/src/containers/viewOnly/ExecutiveSummary.js, web/src/containers/viewOnly/PreviousActivities.js, web/src/containers/viewOnly/activities/Activity.js, web/src/containers/viewOnly/activities/All.js, web/src/styles/scss/print.scss
- adds consistent horizontal rules between sections and subsections and standardizes the spacing around them
- in the activity subsections, un-bolds the activity number and name and puts it in uppercase
- in the activity FFP subsection, puts the dollar totals on the same lines as their headings
- does the same for the FFP "all years" subsection
- closes #1961 
=> Update print/readonly view based on design lab feedback

web/src/containers/viewOnly/activities/Activity.js
For the print/export view, change goals to objectives so that it works again.
- fixes #2040 
- N/A ~Tests have been updated (and all tests are passing)~
- N/A - the bug was introduced and fixed within the same release, so nothing to document ~Changelog is updated as appropriate~
=> Fix the print/export view

CHANGELOG.md, web/src/i18n/locales/en/proposedBudget.yaml
- updates narrative explanation for the proposed budget table
- closes #2058
=> Update proposed budget narrative

CHANGELOG.md
=> Next release changelog

api/audit-resolve.json, web/audit-resolve.json
dependency vulnerability checks are failing
- fixed some dependency vulnerabilities
- ignored subset for a week while we wait to see if the developers fix the peer dependencies
=> fixed dependency vulnerabilities

CHANGELOG.md
Someone fell asleep at the changelog wheel this week. So here it is, updated and ready to go (pending #2123), just in time to clear it out again for next week! 😬
- updated changelog!
=> Get the changelog up to date

CHANGELOG.md, web/src/styles/scss/print.scss
- removes excess whitespace from the top and left when printing from a screen other than the export screen
- closes #2114
=> Remove excess whitespace in print

CHANGELOG.md, api/audit-resolve.json, api/package-lock.json, web/audit-resolve.json, web/package-lock.json, web/package.json
corrected date on the change log
- corrected date to May 4, 2020
- add pound signs to task numbers so they link correctly
~~- [ ] Tests have been updated (and all tests are passing)~~
=> change log updates

CHANGELOG.md
reset change log for May 18 release
- change log has been reset
~~- [ ] Tests have been updated (and all tests are passing)~~
=> Reset change log

web/package-lock.json
fixed dependency vulnerabilities
- fixed dependency vulnerabilities
~~- [ ] Changelog is updated as appropriate~~
=> dependency vulnerability patch

web/src/components/HeaderSaveMessage.js
Fixes a couple of lint failures. I let these two scrap through in a previous PR.
- fixes those things
- N/A ~Changelog is updated as appropriate~
=> Lint cleanup

bin/headers-staging.lambda.js
Update api url for staging in the bin/headers-staging.lambda.js file
- Update api url for staging in the bin/headers-staging.lambda.js file
~~- [ ] Changelog is updated as appropriate~~
=> updated api url for staging

CHANGELOG.md, web/src/containers/BudgetSummary.js, web/src/containers/__snapshots__/BudgetSummary.test.js.snap, web/src/i18n/locales/en/proposedBudget.yaml
Update the summary budget table based on the screenshot.  Closes #2290 
- Change header "totals" to have Medicaid Total Computable the right most table column
- Remove the term "Project" from this page".
- Replace Contracted Resources with Private Contractor.
- Replace Non-Personnel with Other State Expenses.
- In the instructions change Medicaid Share = Medicaid Total Computable
- In the table change Medicaid Total = Medicaid Total Computable
- sort by State Staff, Other State Expenses, and Private Contractor
=> Update Summary Budget Table

CHANGELOG.md, web/src/components/Section.js, web/src/components/Section.test.js, web/src/components/__snapshots__/Section.test.js.snap, web/src/i18n/locales/en/activities/schedule.yaml
Resolves #2313 
- Updates instruction detail for Activity Schedule
- Remove unused SectionHeading and SectionDesc components
- ~[ ] Associated OpenAPI documentation has been updated~
=> Update help text for Activities > Activity Overview > Activity Schedule

CHANGELOG.md, web/src/i18n/locales/en/activities/costAllocate.yaml
added federal-state split detail.  Closes #2311 
- added federal-state split detail
=> Update help text for the FFP/Federal-state split selection

CHANGELOG.md, api/audit.js, web/src/actions/admin.js, web/src/actions/app/symbols.js, web/src/actions/aria.js, web/src/actions/auth.js, web/src/actions/budget.js, web/src/actions/editApd/symbols.js
Resolves #2349 
- Changes redux actions from symbols to strings so that they are visible in ReduxDev Tools
=> [TechDebt] Change redux actions from symbols to strings

CHANGELOG.md, web/src/containers/viewOnly/ApdStateProfile.js, web/src/containers/viewOnly/ScheduleSummary.test.js, web/src/containers/viewOnly/activities/Activity.js, web/src/containers/viewOnly/activities/Activity.test.js
Resolves #2314 
- date format in export view
- ~[ ] Associated OpenAPI documentation has been updated~
=> Start/End Dates in Export View should be in MM/DD/YYYY format.

api/package.json, web/package.json
Adding Tiffany Forkner, our newest team member!
I hope I do this right.
-Web and API contributor list has been updated to include our newest team member!
=> Update Contributor List

CHANGELOG.md, README.md, api/package.json, api/routes/users/put.endpoint.js, bin/preview-deploy/aws.cleanup.sh, bin/preview-deploy/aws.user-data.sh, bin/preview-deploy/github-comment.sh, web/package.json, web/src/reducers/budget.test.js
Updates old repo URLs with new repo URLs.
- URLs are updated for the new repo
=> Migration update

web/audit-ci.json
Add two development-only packages to the `web/audit-ci.json` allowlist.
- see `web/audit-ci.json` and individual commit messages for changes.
- ~[ ] Tests have been updated (and all tests are passing)~
- ~[ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented~
- ~[ ] The change has been documented~
- ~[ ] Associated OpenAPI documentation has been updated~
- ~[ ] Changelog is updated as appropriate~
- ~[ ] Design has approved the experience~
- ~[ ] Product has approved the experience~
=> Address frontend audit issues

.circleci/config.yml
Updating the AWS S3 URI so CircleCI can appropriately deploy to staging.
- CircleCI test, build, and deploy can run to completion
=> Update S3 Uri

CHANGELOG.md, web/src/components/ArrowLeftIcon.js, web/src/components/ArrowRightIcon.js, web/src/components/ContinuePreviousButtons.js
Resolves #2213 
- adds SVG icons for Continue and Previous buttons
=> Use SVG arrow from CMSgov Design System

CHANGELOG.md, web/src/containers/viewOnly/ProposedBudget.js, web/src/containers/viewOnly/activities/Activity.js, web/src/containers/viewOnly/activities/ActivityList.js, web/src/containers/viewOnly/activities/All.test.js
Resolves #2387
- Updates copy in the export views to match the form input labels
=> Export views content edits

web/src/reducers/nav.items.js
=> Change "Objectives and key results" Nav Bar title to match contents of page

CHANGELOG.md, web/audit-ci.json, web/package-lock.json, web/package.json, web/src/containers/viewOnly/PreviousActivities.js
=> Results of previous activities fields are missing in export view

bin/preview-deploy/aws.sh, bin/prod-deploy/aws.sh
Forgot to add SSH key to staging build, left it in preview build
- SSH Key is deployed to staging
- SSH Key is removed from preview
=> Changed key from preview to staging

bin/prod-deploy/aws.user-data.sh
Fixed the link for rpm
- The link from arm64 to amd64
=> Fixing the rpm link

.circleci/config.yml
Added env awareness to Okta variables
- Added env awareness to Okta variables
=> Added Env Awareness to setting of kta variables

bin/headers-staging.lambda.js, owasp/api-scan.conf, web/src/containers/ApdApplication.test.js
changed the staging headers to include Okta as an allowed site
- okta is in connect-src
=> changed headers

bin/headers-staging.lambda.js
trying to update the CSP
- change the iframe options
~- [ ] This code has been reviewed by someone other than the original author~
=> added okta to frame options

bin/headers-staging.lambda.js
spent some more time looking into CSP and tried to hopefully get it right this time....? 
- changed CSP again
~- [ ] This code has been reviewed by someone other than the original author~
=> more changes to CSP

bin/headers-staging.lambda.js
added self to a few places that were complaining
- changes to CSP
~- [ ] This code has been reviewed by someone other than the original author~
=> adding a few more self options

api/migrations/20200921100859_change-role-names.js, bin/headers-staging.lambda.js
updated migration to remove foreign key restraint before running change role names; saved changes made to CSP
- dropping the foreign key restraint before changing the role names
- changing the CSP to what is in staging
~- [ ] This code has been reviewed by someone other than the original author~
=> migration and csp changes

CHANGELOG.md, api/logger/winston.js, api/migrations/20200921100859_change-role-names.js, api/package-lock.json, api/package.json, api/seeds/shared/roles-and-activities.js, api/seeds/shared/states.js, bin/headers-production.lambda.js, bin/prod-deploy/aws.sh, web/src/reducers/user.selector.js
updated the way states, roles, activities, and roles-activity-mapping are seeded; added seeding to build process
- adds seeding to the prod build process
- only sees states if there are no states
- deletes all of the activities before re-adding them
- deletes all of the roles-activities before re-adding them
- adds logging to states and roles seeding
=> seeding roles, activities and their map table

api/seeds/shared/roles-and-activities.js
Deleting the rows for auth_activities and auth_role_activity_mapping needed to be swapped due to foreign key constraints.
- pulled the deletes out of the methods and just into seed
- deleted the rows from auth_role_activity_mapping before auth_activities to prevent foreign key constraint errors
=> switch the order of deleting the rows

CHANGELOG.md, web/src/components/Header.js, web/src/components/__snapshots__/Header.test.js.snap, web/src/components/__snapshots__/Routes.test.js.snap, web/src/components/__snapshots__/Wrapper.test.js.snap, web/src/routes.js
The profile page is not longer relevant.
- remove the "Manage account" button from the navigation dropdown
- remove the route to go to the profile page
=> removed button and link to profile page

api/migrations/20201123161901_modify-users.js, api/routes/me/patch.endpoint.js, api/routes/me/patch.js, web/src/components/__snapshots__/Routes.test.js.snap, web/src/components/__snapshots__/Wrapper.test.js.snap, web/src/routes.js
Fixed issue with migrations removed route again
- update migration to set a default value for new uid field if none exists in the existing row
- removed the route to /me on the front end
=> fixed migration

bin/preview-deploy/aws.sh
- redirect output within associateElasticIP function to /dev/null
- add some shellcheck suggested changes (quoting, mostly)
=> [dev(ops)] Repair cms-eapd-bot

api/package-lock.json, api/package.json, web/audit-ci.json, web/package-lock.json, web/package.json, web/yaml-tests.js
=> Bump axios version, add ini 'vulnerabilities' to the audit-ci allowlist

CHANGELOG.md, web/src/components/Footer.js
Resolves #2353 
- Updates email address in footer
=> Updates email address in footer

CHANGELOG.md, web/src/components/Header.js, web/src/components/__snapshots__/Header.test.js.snap
Removed the Manage Account link which was accidentally added back in a merge
- Manage account link should be gone
=> removed manage account link

bin/prod-deploy/aws.user-data.sh
I accidentally removed too many lines when editing the flow of the directories being created and need to put it back.
- Adds back the /app directory
=> Adding back mkdir /app

web/src/util/oktaAuth.js
=> samesite none

api/auth/jwtUtils.js
trying setting the domain on the cookie
- cookie will be sent with images
=> cookie testing

api/auth/jwtUtils.js
Changed check to NODE_ENV instead of API_URL
- cookie should pass with images
=> image cookie fix

api/auth/jwtUtils.js
Change sameSite to lax and removed domain tag
- should send cookies to server
=> cookie change

.github/PULL_REQUEST_TEMPLATE.md
=> Update PULL_REQUEST_TEMPLATE.md to include QA

api/auth/jwtUtils.js
Forgot to switch another flag
- should read the correct cookie
=> forgot to update another flag

api/package.json, web/package.json
Adding new members for Feb 2021 - perhaps one of my most favorite things, expanding our team to do more awesome work.
Adding New contributors
=> Add New Team Members - Feb 2021

api/auth/jwtMiddleware.js, api/auth/jwtUtils.js, bin/headers-staging.lambda.js, web/package-lock.json, web/package.json, web/src/components/Root.js, web/src/components/__snapshots__/Root.test.js.snap, web/src/containers/Login.js, web/src/containers/Logout.js, web/src/containers/PrivateRoute.js
I changed the way I was setting the cookie to set it on the frontend instead
- cookie is sent to backend
~- [ ] QA has approved the experience~
=> image cookie

api/auth/jwtMiddleware.js, api/auth/jwtUtils.js, api/auth/jwtUtils.test.js, web/src/util/auth.js
The cookie is now being created client side. Resolved issue with creating the cookie client side so that it could be read server side. Adjusted the client side settings for creating the cookie. Changed the backend to always read from the frontend cookie.
resolves #2845 
- expected a value cookie to be sent with image requests
~- [ ] QA has approved the experience~
=> added client side cookie for loading images

bin/preview-deploy/aws.sh, bin/prod-deploy/aws.user-data.sh
Trying to get a build to work with watch
- It builds
- It watches
=> PM2 Watch Take 2

bin/prod-deploy/aws.sh
Added my key so I can SSH to staging and investigate why the watch flag is not working for pm2
- Add my SSH key
=> Added my key

bin/prod-deploy/aws.sh
Added a missing slash to the end of my prod/staging key line.
- Will build
- 
- ### This pull request is ready to merge when...
=> Added the missing slash

.circleci/config.yml
This PR removes the lines in the CircleCI config that remove the seed subdirectories.
- This PR removes the lines in the CircleCI config that remove the seed subdirectories.
=> Removed remove seed directories

bin/preview-deploy/aws.sh, bin/preview-deploy/aws.user-data.sh
This pull request is a part of our effort to align around a specific Postgres version, 10.15. Prod, Impl/Staging, and Dev are all using 10.15. This will make sure that 10.15 is what is installed in Test/Preview.
- Download and installs Postgresql 10 key from Postgres site
- Adds the official Postgres 10 repository to the machine
- Installs Postgres 10.15 server
=> Added PSQL 10 repo, repo key, and install postgresql 10.15 server

bin/preview-deploy/aws.user-data.sh
Updated the nginx logging level 
- changed nginx logging level to debug
~- [ ] QA has approved the experience~
=> changed logging to debug level

bin/preview-deploy/aws.sh, bin/prod-deploy/aws.sh
Adds health checks for the Front and Backend.
- 200 code for Frontend is received
- 204 code for Backend is received
=> Preview Deploy Front/Backend Health Checks

bin/prod-deploy/aws.sh
The tests in Prod/Staging did not work and caused the Pipeline to fail, this is my first attempt to resolve those issues.
- Staging will build successfully with the new frontend/backend tests.
=> Frontend & Backend Test Fixes to Staging/Prod

bin/prod-deploy/aws.sh
Second patch to try and address the failing new front/back end tests in Staging/Prod.
- New Front/Backend tests will run successfully in Staging/Prod
=> Switched Front/Backend Test Statements from Print to Echo

CHANGELOG.md, web/src/components/ApdList.js, web/src/components/HeaderSaveMessage.js, web/src/components/HeaderSaveMessage.test.js, web/src/components/SaveMessage.js, web/src/components/SaveMessage.test.js, web/src/components/Section.js, web/src/components/StateAffiliationStatus.js, web/src/components/StateAffiliationStatus.story.js, web/src/components/StateAffiliationStatus.test.js, web/src/containers/StateDashboard.js, web/src/containers/StateDashboard.test.js, web/src/containers/activity/OutcomesAndMetrics/OutcomeAndMetricForm.js, web/src/containers/activity/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricForm.test.js.snap, web/src/i18n/locales/en/activities/outcomes.yaml
Resolves #2950 
- Updates the copy for Outcomes description + form field
1. Login to PR build
2. Navigate to Outcomes and Metrics section
3. Verify new copy is in place (look at original ticket for exact copy)
=> Tbolt/2950 Update the text in Outcomes description

api/seeds/shared/roles-and-activities.js
The backend was failing because it was trying to insert an empty array, so I added a check so it only inserts if there is something to insert.
- added empty array testing
=> updated seeding script to handle no seeding needed

api/package-lock.json, api/package.json, web/package-lock.json, web/package.json
This PR fixes a security vulnerability in api and web that is blocking all of our PRs from building.
- adds script to call `npx npm-force-resolutions` preinstall
- adds a resolutions section to the package.json with the version of the dependency that fixes the vulnerability
=> update security issues

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md
- added environment to bug template
- changed Acceptance Criteria to be a table
=> updates to github templates

api/package-lock.json, web/audit-ci.json, web/package-lock.json, web/package.json
resolves #
Routine audit fixes in order to pass CI pipeline
- updates dependencies and audit exceptions
- none.  This should be non breaking changes only.
- test cases all still work
1. standard regression testing.
=> downgraded hosted-git-info, added 1755, removed 1745 and 1748

api/auth/jwtMiddleware.js, api/auth/jwtUtils.js, web/src/util/auth.js
related to #3180 
Investigating staging cookie issue
- reordered if statements for creating cookie configs
- added log statements
=> cookie investigation

api/auth/jwtMiddleware.js, api/auth/jwtUtils.js, api/auth/jwtUtils.test.js, api/routes/me/get.js, web/src/util/auth.js
related to #3180 
- how cookies are set
- some prettier formatting changes
1. login using em@il.com
2. open an APD
3. add an image to one of the rich text fields
4. make sure that the image displays
5. go back to the dashboard
6. open the same APD again
7. make sure that the image is still there
=> change the way cookies were being set

.circleci/config.yml, .github/workflows/storybook.yml
Updating master one last time before it gets deleted so that it's end state is the same as the start state as main and development.
=> Preparing for Gitflow changes (#3299)

web/audit-ci.json
=> adds cve 1770 and 1771 to allowlist

package-lock.json, package.json, web/audit-ci.json
resolves #3426
Because we got rid of the changelog from the project source, we needed an easier solution for documenting the work that was done. After some research I found this [module](https://github.com/lob/generate-changelog). It generates the changelog based on the commits since she last tag. In order for this to work, on squash and commit the developers need to format their commit messages like this:
```
type(category): description [#<issue number>]
```
Where `type` is one of the following:
* `breaking`
* `build`
* `chore`
* `ci`
* `docs`
* `feat`
* `fix`
* `other`
* `perf`
* `refactor`
* `revert`
* `style`
* `test`
- adds a package.json at the top level of the project
=> changelog generator

web/audit-ci.json
=> fixes frontend vulnerability

api/package-lock.json, api/package.json
Resolves swagger vulnerability
=> fixes swagger vulnerability

.circleci/config.yml
Resolves # https://app.circleci.com/pipelines/github/CMSgov/eAPD/7561/workflows/314c5e52-35e4-4a74-b17a-9fd5a8d8f0f7
The main/staging/prod artifact storage/deploy to S3 did not work, this will resolve that.
- Adds sudo in front of apt-get commands to elevate privileges to allow for the installation of required packages.
=> Added sudo to apt-get commands

api/package.json, integrationTests/package-lock.json, integrationTests/package.json, web/audit-ci.json, web/package.json
Resolves frontend vulnerability
=> resolve frontend vulnerability

api/audit-ci.json, web/audit-ci.json
npm changed their advisory numbers again
=> fixing vulnerabilities again

.github/workflows/storybook.yml
=> Tbolt/Storybook Deploy fix

api/package.json, api/yarn.lock, web/package.json, web/yarn.lock
=> vulnerability audit fix

web/package.json, web/yarn.lock
Resolves issue with node-forge
=> fixed node-forge vulnerability

bin/prod-deploy/aws.user-data.sh
=> change newrelic to install globally

web/package.json, web/yarn.lock
Resolves vulnerability with [async](https://github.com/advisories/GHSA-fwr7-v2mv-hh25)
=> fixes vulnerability

web/src/components/DateField.js, web/src/components/RichText.js, web/src/components/__snapshots__/RichText.test.js.snap, web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.js, web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.test.js, web/src/static/schemas/privateContractor.js
…eAPD into 3499/contractorResourceFormFixesResolves #
=> remove useReducer for state mgmt

.circleci/config.yml, api/routes/apds/openAPI.js, api/yarn.lock, integrationTests/yarn.lock, openapi.json, web/package.json, web/yarn.lock
=> updated yarn.locks and updated moment version

api/mongo-migrations/1647374289696-apd-schema.js
=> Update mongoose schema migration

api/mongo-migrations/1647374289696-apd-schema.js
=> changed migration

.github/ISSUE_TEMPLATE/design.md
Resolves #3949 
Update Design Template based on comments in 3949
- Updates language in Design Template
- Limited to Design Template
=> Update Design Template

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/maintenance.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/chromatic.yml
Updates to the github templates and uncomments chromatic
=> updates to templates; uncommenting chromatic

.github/PULL_REQUEST_TEMPLATE.md, .github/release.yml
Added reminder line to PR template
=> updated PR template to remind everyone to use labels in the PRs

web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceForm.js, web/src/pages/apd/activities/overview/Overview.js, web/src/pages/apd/activities/overview/Schedule.js, web/src/pages/apd/activities/overview/StandardsAndConditions.js
=> Tif updates

bin/preview-deploy/aws.sh, packer/preview-ami.pkr.hcl
Removing Pre from Pre-Preview (again)
=> Trying to remove pre from pre-preview

.circleci/config.yml, .gitignore, bin/preview-deploy/aws.sh, bin/preview-deploy/aws.user-data.sh, docker-compose.yml, web/src/redux/reducers/apd.js, web/src/util/analytics.js, web/webpack.config.dev.js, web/webpack.config.js
Resolves #4208 
Updated the tealium settings
=> tealium updates

.circleci/config.yml, .gitignore, bin/preview-deploy/aws.sh, bin/preview-deploy/aws.user-data.sh, bin/prod-deploy/aws.sh, docker-compose.yml, web/src/redux/reducers/apd.js, web/src/util/analytics.js, web/webpack.config.dev.js, web/webpack.config.js
Resolves #4208
still working on tealium
=> update tealium configs

e2e/cypress/helpers/apd/key-state-personnel.js, web/src/pages/apd/ApdReadOnly.test.js, web/src/redux/reducers/apd.js, web/src/redux/reducers/apd.test.js
Now that we have the adminCheck toggle, we need to make adminCheck default to false.
=> setting adminCheck to false by default

.github/PULL_REQUEST_TEMPLATE.md
=> Update PR Template for QA accessibility testing

bin/headers-production.lambda.js, bin/headers-staging.lambda.js, web/package.json, web/src/containers/ApdApplication.js, web/src/containers/Root.js, web/src/pages/dashboard/state-dashboard/StateDashboard.js, yarn.lock
removed google tag manager from application
1. open the application
2. verify that network panel doesn't show a call to analytics.js
=> removed google tag manager

.circleci/config.yml, audit-ci.json
Resolves # Pipeline failures
Address issues with the vulnerability scan and OWASP scan
1. Add the fix, be the fix
2.
3.
=> Fixes for pipeline builds

.circleci/config.yml, packer/preview-ami.pkr.hcl
Resolves # 4268
Automated AMI creation was not working, this fixes it
Breaks everything, it's the AMI
1. Look at the CircleCI workflow for weekly ami scan
2. Look at the AWS Instance URL to make sure that the AMI used to build the app/preview instance works
=> Fix Weekly AMI Scan

api/seeds/development/01-akAPD.js, e2e/cypress/integration/03-admin/04-admin-check.cy.js
Resolves #
Fixes small issue with the admin check  tests failing when checking the functionally Complete seed
| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
1. Tests pass on Circle
=> change seed name of complete APD to HITECH IAPD Complete

api/package.json, audit-ci.json, package.json, yarn.lock
Resolves vulnerability issue
Upgrades jsonwebtoken to 9.0.0
=> updated jsonwebtoken

web/src/i18n/locales/en/activities/contractorResources.yaml, web/src/pages/apd/activities/contractor-costs/ContractorResources.js, web/src/pages/apd/activities/contractor-costs/ContractorResources.test.js, web/src/pages/apd/activities/contractor-costs/__snapshots__/ContractorResources.test.js.snap
Resolves #4511 
Update the example help text for Private Contractor in MMIS APDs
1. Open MMIS APD
2. Verify example help text is updated when adding a new private contractor according to ticket
3. Verify HITECH APD example help text in private contractor costs remains the same
=> Tbolt/4511 Private Contractor Example Help Text Update

.circleci/config.yml
Resolves # Backend API Endpoint Test Segfault
Increasing resource class size of the container running the backend api endpoint test
| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
1.
2.
3.
=> Increasing resource class as a quick fix for potential build issue

web/package.json, yarn.lock
Fixes vulnerability with web pack by bumping version `5.75.0` -> `5.76.0`
=> resolve webpack vuln

api/db/apds.js, api/migrations/20230207224139_mongoose-adding-funding-category.js, api/migrations/20230327181241_update-budgets.js, api/models/index.js
Resolves issue with migrations
A previous migration didn't handle updating budgets correctly, so the budgets were messed up in mongo. Created a new migration to update all of the budgets
=> [maintenance] resolved migration issue
