- .gitignore
- web/package-lock.json
- web/package.json
- web/src/hello.js
- web/webpack.config.js
this PR adds [prettier](https://github.com/prettier/prettier), and subsequently runs prettier across all js files
prettier is a code formatter than ensures consistency and standardization around things like putting a semi-colon at the end of statements, proper indentation, maximum line width.
it can be run across all files via `npm run prettier`; you can also add a prettier extension to your code editor of choice (atom, sublime, etc) so that it auto-formats the file you're working on when you save (optional, though encouraged).
> add (and run) prettier

- manifest.yml
* Adds an app for the API to the cloud.gov manifest
* Lowers the memory quota for the frontend
> Add API app to cloud.gov manifest

- api/.eslintrc.json
- api/auth/authenticate.js
- api/auth/index.js
- api/auth/serialization.js
- api/auth/session.js
- api/env.js
- api/main.js
- api/package-lock.json
- api/package.json
- api/tests/auth/authenticate.js
- api/tests/auth/index.js
- api/tests/auth/serialization.js
- api/tests/auth/session.js
- api/tests/env.js
- fixes a bug in the way default environment variable values were being set
- adds Passport for authentication
- sets up a local strategy
- sets up a hard-coded username/password (`hello`/`world`) to get started
- stores serialized auth info in an encrypted client cookie
- deserializes auth info before processing API endpoint requests
- adds an API endpoint at `POST: /auth/login` that takes a username and password as form-encoded variables and returns the generated user ID
- **note**: this isn't strictly necessary; the status code should be sufficient. If the user is logged in, their session cookie will be set and there's no reason to send their ID.  This was mostly just for illustration
- adds a bunch of tests
closes #30
impacts #35 and #33
> Authentication scaffolding

- api/package.json
- bin/deploy.sh
Because our CircleCI config uses the official Node images, we don't need `sudo`.  The official images run as root and don't switch users, so there's no `sudo` installed.
Also adds a Node version to the package.json `engines` property.  Otherwise cloud.gov gives us 4.8, which just plain ol' doesn't work. 😆
> Remove sudo in deploy script

- api/knexfile.js
To support differing host values (i.e., if not using docker)
Example: `DEV_DB_HOST='localhost' npm run migrate`
> configurable db host field

- web/.eslintrc.json
- web/package-lock.json
- web/package.json
- web/src/components/Hello.js
- web/src/components/Hello.test.js
- web/src/components/__snapshots__/Hello.test.js.snap
- web/src/containers/Home.js
- web/src/styles/Alert.js
- web/src/styles/Alert.test.js
Added a new UI component -- an `Alert` box that extends Rebass's `Box` component.
It takes a `kind` parameter that can be `['success', 'warning', 'error', ...]`; these correspond with the USWDS alert names, and the output is a similarly styled element.
Preview:
> add example new UI component

- api/.eslintrc.json
- api/auth/authenticate.js
- api/auth/index.js
- api/auth/serialization.js
- api/auth/session.js
- api/db.js
- api/main.js
- api/migrations/20171218182739_initial.js
- api/seeds/development.js
- api/seeds/development/users.js
- api/seeds/test.js
- api/seeds/test/users.js
- api/tests/auth/authenticate.js
- api/tests/auth/index.js
- api/tests/auth/serialization.js
- api/tests/auth/session.js
- api/tests/db.js
- api/tests/env.js
Ensures consistent formatting across codebase
Two eslint rules affected: `function-paren-newline` and `arrow-parens` because they're unnecessary / conflict with prettier (i.e., function parens newlines are determined based on if maximum line length is crossed)
> run prettier on api directory

- api/Dockerfile
- api/auth/middleware.js
- api/main.js
- api/migrations/20171221233429_unique-email.js
- api/package-lock.json
- api/package.json
- api/routes/index.js
- api/routes/users/get.js
- api/routes/users/index.js
- api/routes/users/post.js
- api/tests/auth/middleware.js
- api/tests/routes/index.js
- api/tests/routes/users/get.js
- api/tests/routes/users/index.js
- api/tests/routes/users/post.js
An HTTP `POST` to `/user` allows an authenticated user to add a new user.  Expects a JSON body with an email address and password.  The password will be hashed with bcrypt before it is stored.  Sends an HTTP status 400 if the body is invalid or if the email address already exists in the database along with an error message token.  Otherwise it sends back an HTTP status 200 and an empty body.  Relies on the `loggedIn` middleware.
An HTTP `GET` to `/users` allows an authenticated user to get a list of all users.  Sends the results back as JSON.  Relies on the `loggedIn` middleware.
An HTTP `GET` to `/users/:id` allows an authenticated user to get the user specified by the `:id` parameter (e.g., `/users/57` would get the user whose ID is 57).  Sends an HTTP status 400 if the ID is invalid …
> Add endpoints for local user management

- api/endpoint-tests/auth/login.js
- api/endpoint-tests/users/get.js
- api/endpoint-tests/users/post.js
- api/endpoint-tests/utils.js
- api/routes/users/get.js
- api/routes/users/get.test.js
Adds a bunch of tests for this endpoint.  This should cover all of the endpoints we have right now.
Knex keeps database connections open indefinitely (probably all other database layers would do the same; doing otherwise would be silly), which is cool.  Tap (our testrunner) runs every test file in its own process, which is also cool (yay, test isolation!).  The problem here is that Tap expects the test processes to end on their own.  If they don't, it generates a timeout error and forcibly kills them, making it look like tests failed.
Tap has an event you can hook when it expects the test process to be finished - that is, all of the registered tests have been marked as done.  In that event handler, if you call `process.exit()`, that will move Tap along.  (It _should_ gracefully close the …
> /user POST endpoint tests

- api/auth/index.js
- api/auth/index.test.js
- api/endpoint-tests/auth/logout.js
Adds a `GET` endpoint at `/auth/logout` and associated tests.  This is in service to #32.
> Add logout endpoint

- api/auth/middleware.js
- api/auth/middleware.test.js
- api/auth/serialization.js
- api/auth/serialization.test.js
Using the authorization data model created in #126, this updates the user deserializer to populate the `req.user` object with an `activities` array, indicating which activities the user is authorized to perform.  It does that by pulling the user's role from the database and then getting the list of activities that are mapped to that role.
This deserialization happens at the beginning of each inbound request, and the `req.user` object is fully populated and available to all endpoints.
This also adds a new middleware that endpoints can opt into called `can`.  The `can` middleware takes an activity as an argument and will stop the response flow if the user is not logged in or does not have permission for that activity.  It piggy backs on the `loggedIn` middleware for the first half, so we …
> Add authorization middleware

- api/auth/authenticate.js
- api/auth/authenticate.test.js
- api/auth/index.test.js
- api/auth/middleware.test.js
- api/auth/serialization.js
- api/auth/serialization.test.js
- api/auth/session.test.js
- api/db.test.js
- api/endpoint-tests/auth/login.js
- api/endpoint-tests/auth/logout.js
- api/endpoint-tests/users/get.js
- api/endpoint-tests/users/post.js
- api/endpoint-tests/utils.js
- api/env.test.js
- api/migrations/20180117155746_add-authorization-models.js
- api/package-lock.json
- api/package.json
- api/routes/index.test.js
- api/routes/users/get.js
- api/routes/users/get.test.js
- api/routes/users/index.test.js
- api/routes/users/post.js
- api/routes/users/post.test.js
- api/seeds/00-delete-everything.js
- api/seeds/01-roles-and-activities.js
- api/seeds/10-development.js
- api/seeds/10-test.js
- api/seeds/development/users.js
- api/seeds/test/users.js
Switches from using promises directly, with the sometimes-gnarly `.then()` code, to using the `await` and `async` syntactic sugar.  There are a couple of things worth pointing out specifically:
- all tests are updated to use `async` methods, which always return a promise; this way, we rely on tap's native promise support instead of having to remember to manually call `done()` on the tests
- the `request-promise` library does something weird when I use it with `await`: it prints the response object to the console and doesn't resolve like it's supposed to; as a temporary workaround, I added async wrapper methods to the endpoint test utils class
There's also a CodeClimate error that I think is valid, but I recommend that we ignore it for now because it should be cleaned up when we pick a DB …
> Switch API to using await/async instead of promise syntax

- api/auth/index.test.js
When I added the `/auth/logout` endpoint, I didn't add tests to verify that the endpoint is hooked up and called correctly.  This PR corrects that.
I also added tests to make sure that no `PUT` or `DELETE` endpoints are added by the `auth/index` module.  That way if we _do_ those endpoints in the future, our tests will fail and remind us to update our tests and we won't have another one of these PRs.  😄
> Add missing tests

- Staticfile
- web/package.json
I __think__ this may fix our front-end bug where non-root paths are 404ing (instead of using index.html and letting SPA handle routing) based on:
* https://github.com/cloudfoundry/staticfile-buildpack/issues/77
* https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#pushstate
If this doesn't work, we'll have to muck around with `nginx.conf` but one step at a time...
> Add Staticfile w/ pushstate enabled

- web/package-lock.json
- web/package.json
- web/src/components/App.js
- web/src/components/Dollars.js
- web/src/components/FormPersonnel.js
- web/src/components/Inputs.js
- web/src/components/__snapshots__/App.test.js.snap
- web/src/containers/ApdOverview.js
- web/src/containers/StatePersonnel.js
- web/src/styles/base.js
Adds a form for entering state and contracting personnel and computes what those personnel will cost.  This closes #150.
* Adds the `/state-personnel` route
* Updates the APD overview page to go to the personnel page next
* Updates the `Input` component to add an option to turn labels off
- labels are pushed offscreen so screen readers will still read them
- we should discuss this approach more; are there cases where the labels should also be  hidden from screen readers?
* Adds a `<Dollars>` component for formatting numbers into dollars for display
This is pretty ugly, IMO, but it's a prototype...  Also a good excuse to play with redux-forms.  😄 
- foregoing ***new*** tests on the prototype UI components
- Design has approved the experience
- N/A - design will definitely not approve this …
> Adds a personnel form

- api/_setup.test.js
- api/endpoint-tests/log-form/index.js
- api/routes/index.js
- api/routes/index.test.js
- api/routes/logForm.js
- api/routes/logForm.test.js
- bin/deploy-ux-testing.sh
- bin/deploy.sh
- docker-compose.yml
- docs/deployment.md
- docs/frontend-build.md
- docs/index.md
- web/package-lock.json
- web/package.json
- web/src/components/FormActivitiesStart.js
- web/src/components/FormApdOverview.js
- web/src/components/FormStateContacts.js
- web/src/components/FormStateStart.js
- web/src/containers/ActivitiesStart.js
- web/src/containers/ApdOverview.js
- web/src/containers/StateContacts.js
- web/src/containers/StatePersonnel.js
- web/src/containers/StateStart.js
- web/src/util/formLogger.js
- web/webpack.config.js
Per @nkkl's request, record the form values as they're being entered by the user.  Some notes:
* the API stores the form values in memory, so if the API restarts for some reason, the collected values will be reset
* the form values are stored in a JSON object, keyed on the timestamp of when the user first began interacting with the form
* if the user reloads their browser session, they'll get a new timestamp and they'll be represented twice in the logged results (I tried to get around this by stashing a cookie but it refused to work and I didn't want to spend any more time on it)
* logging is enabled or disabled at ***build*** time, using the `LOG_FORM_INTERACTIONS` environment variable - by default this is `false`, but if it is set to `true`, form interactions will be logged
* the API …
> Log form values

- bin/deploy-ux-testing.sh
- bin/deploy.sh
`npm run` executes scripts in an isolated environment.  In order to get the constituent parts of an npm script to have the same environment variables, those variables must be exported to the parent environment.  We'll have to wait and see if this actually works, but it looks highly probable from my local testing.
This needs to be merged into master and then the UX deploy needs to be manually approved in order to fully test this.
> Fix deployment scripts

- web/src/components/App.js
- web/src/components/__snapshots__/App.test.js.snap
The HTML5 `main` element is not supported by Internet Explorer, which was throwing off the container width and auto margin.
This should fix :)
More details: https://stackoverflow.com/a/35820454
> main -> div

- api/seeds/01-roles-and-activities.js
The database was being seeded with activities and roles using known IDs.  The reason for that is so we could easily map the activities into roles.  The *problem* is that the ID is an autoincremented field, but when you set the ID yourself, the database does not set the "next autoincrement value" accordingly.  What that means in practice is if you try to insert another row without specifying an ID and the next autoincremented ID happens to be one of the manually set IDs, it will reject the insert.
So instead of setting the IDs manually, this PR allows them to be set by the database.  It then queries the database to find out what the IDs are, and uses that to setup the roles/activities mappings.
> Fix database seed bug

- api/auth/serialization.js
- api/auth/serialization.test.js
When a session cookie arrives at the API and it decrypts successfully, if it refers to a user ID that does not exist in the database, deserialization would fail.  When deserialization failed, the session cookie would not be unset or modified, meaning subsequent requests to the API would continue to fail.  Even logging out failed.
To fix that, deserializing a user from a nonexistent user ID will instead result in a null user, which indicates to the rest of the system that they are not logged in and have no permissions.
> Fix user deserialization bug

- web/package-lock.json
- web/package.json
- web/src/actions/auth.js
- web/src/actions/auth.test.js
- web/src/app.js
- web/src/components/App.js
- web/src/components/__snapshots__/App.test.js.snap
- web/src/containers/Login.js
- web/src/reducers/auth.js
- web/src/reducers/auth.test.js
- web/src/reducers/index.js
- web/src/reducers/index.test.js
This PR begins work to have users authenticate via our front-end site.
It follows the standard/vanilla redux patterns & organization, and adds `redux-thunk` to handle the async authentication request.
Next up (after this initial chunk is live):
* Adding `ProtectedRoute`(s) that redirect to `Login` if unauthenticated
* Better error handling messaging in UI
* Updating top navbar to have dynamic login / logout links
> user login beginnings

- web/src/components/App.js
- web/src/components/__snapshots__/App.test.js.snap
- web/src/containers/Login.js
- web/src/containers/TopNav.js
This adds a (connected) top navigation bar with dynamic login / logout links.
Next up: adding ProtectedRoutes so that when you log out and you're on a logged-in page, you can kicked from it. 
Preview:
> login / logout header

- web/.eslintrc.json
- web/src/components/App.js
- web/src/components/__snapshots__/App.test.js.snap
- web/src/containers/Login.js
- web/src/containers/PrivateRoute.js
This PR adds protected routes to the front-end. If a user tries to go to a "protected" page and they have not authenticated, it redirects to login page and upon successful login takes you back to that page.
In time, we may want to add some custom messaging when this happens (i.e., "You need to log in to see that page...")
> Add protected routes

- api/_setup.test.js
- api/auth/middleware.js
- api/db/authorization.js
- api/db/authorization.test.js
- api/docker-compose.endpoint-tests.yml
- api/endpoint-tests/roles/get.js
- api/routes/index.js
- api/routes/index.test.js
- api/routes/roles/get.js
- api/routes/roles/get.test.js
- api/routes/roles/index.js
- api/routes/roles/index.test.js
- api/seeds/01-roles-and-activities.js
- api/seeds/10-test.js
- api/seeds/test/roles.js
Adds a route for getting a list of roles.  By navigating to `https://{api-url}/roles`, you can get a list of roles in JSON format.  For each role, it returns its internal ID, its name, and a list of activities (by name) that are currently associated with that role.  It looks like this:
```json
[{
"id": 33,
"name": "admin",
"activities": [
"view-roles",
"create-roles",
"edit-roles"]
}, {
"id": 34,
"name": "cms-reviewer",
"activities": []
}, {
"id": 35,
"name": "state-submitter",
"activities": []
}]
```
> Role management GET route

- .github/PULL_REQUEST_TEMPLATE.md
- api/routes/index.js
- api/routes/index.test.js
- api/routes/openAPI/auth.js
- api/routes/openAPI/helpers.js
- api/routes/openAPI/index.js
- api/routes/users/openAPI.js
- docs/index.md
Adds [OpenAPI specification](https://www.openapis.org/) (formerly called Swagger) documentation for the existing API endpoints, and adds an additional endpoint at `/open-api` that returns the JSON document describing the endpoints.  OpenAPI is a machine-readable description of an API.  This is useful because you can use tools like [Swagger UI](http://petstore.swagger.io/) to build a pretty visualization that developers can use to understand what the API does and how to interact with it.
In a future PR, I would also like to add a step to endpoint testing that verifies that every API endpoint listed in our OpenAPI documentation is exercised during the tests.
I also updated the PR template to include a checkmark for updating OpenAPI documentation as necessary.
Closes #127.
- ~~The experience …
> Add OpenAPI spec documentation for existing endpoints

- web/src/components/App.js
- web/src/components/SubmissionSuccess.js
- web/src/components/__snapshots__/App.test.js.snap
- web/src/containers/ReviewAndSubmit.js
- web/src/styles/base.js
This adds two static pages based on the content exploration doc -- a "number/table summary review" page and a "submission received" page
Other bits:
* Adds basic table reset styles and two optional table classes to add additional styles (i.e., adding a light border around cells)
Preview:
> add review, success (static) pages

- api/endpoint-tests/roles/get.js
- api/routes/users/get.js
- api/routes/users/get.test.js
- api/routes/users/post.js
- api/routes/users/post.test.js
- api/seeds/01-roles-and-activities.js
- api/seeds/test/roles.js
Previously, any logged in user could view a list of all users and could create new users.  Not ideal.  😄 
> Add authorization to API calls for viewing and creating users

- api/endpoint-tests/roles/get.js
- api/endpoint-tests/roles/put.js
- api/endpoint-tests/users/get.js
- api/endpoint-tests/users/post.js
- api/endpoint-tests/utils.js
- api/routes/openAPI/index.js
- api/routes/roles/index.js
- api/routes/roles/index.test.js
- api/routes/roles/openAPI.js
- api/routes/roles/put.js
- api/routes/roles/put.test.js
Adds an API route for updating an existing role.  The route is at `/roles/:roleID` and it expects a JSON object body that looks like this:
```json
{
"activities": [ 0, 1, 2 ]
}
```
...where the values of the `activities` array must be numeric and must correspond to IDs of activities known to the system.  Will return a 400 if the body is invalid, 404 if the role ID from the route is not found, or 204 if the role is updated.
> Role management PUT route

- api/auth/serialization.js
- api/auth/serialization.test.js
- api/endpoint-tests/roles/delete.js
- api/endpoint-tests/roles/get.js
- api/endpoint-tests/utils.js
- api/routes/roles/delete.js
- api/routes/roles/delete.test.js
- api/routes/roles/index.js
- api/routes/roles/index.test.js
- api/routes/roles/openAPI.js
- api/seeds/01-roles-and-activities.js
- api/seeds/test/roles.js
Delete roles.  Sorry for the flood of these, @brendansudol.  They happen to all be pretty similar, which means I've been able to churn them out pretty fast.  There's really just one left (`PUT /users/:id`) which will give us all the user/role management API functionality we should need for a while.
> Role management DELETE endpoint

- api/logger.test.js
Adds tests for the API logger creator.
- ~~The change has been documented~~
- ~~Associated OpenAPI documentation has been updated~~
> Add tests for logger creator

- api/endpoint-tests/utils.js
Simplify the wrapper code around `request` for endpoint tests.  In some future state, this may enable us to compute a kind of "endpoint coverage" metric, so we'll know which endpoints aren't being tested.
- ~~Tests have been updated (and all tests are passing)~~
- ~~The change has been documented~~
- Associated OpenAPI documentation has been updated~~
> Refactor endpoint test request util

- api/endpoint-tests/activities/get.js
- api/endpoint-tests/roles/delete.js
- api/endpoint-tests/roles/get.js
- api/endpoint-tests/roles/post.js
- api/endpoint-tests/roles/put.js
- api/endpoint-tests/states/get.js
- api/endpoint-tests/users/get.js
- api/endpoint-tests/users/post.js
- api/endpoint-tests/users/put.js
- api/endpoint-tests/utils.js
- api/routes/openAPI/auth.js
- api/routes/users/get.js
- api/routes/users/get.test.js
- api/routes/users/openAPI.js
- api/seeds/test/users.js
Almost all of our endpoints have identical tests for unauthenticated cases, and no tests for unauthorized cases.  This PR creates a pair of generic methods to do those tests for every endpoint which simultaneously increases our endpoint coverage and reduces the amount of code we have to support.
The PR also fixes some of the OpenAPI documentation that was outdated, which was revealed after #272 was merged.  :tada:
> Standardize some endpoint tests

- bin/deploy-ux-testing.sh
The UX deploy was hanging on the step to delete the database because it wanted a confirmation.  When it didn't get one, it attempted to proceed to create a new database with the same name, but there was a collision so it would fail.
- ~~Tests have been updated (and all tests are passing)~~
- ~~The change has been documented~~
- ~~Associated OpenAPI documentation has been updated~~
> Fix UX deploy

- api/db/activity.js
- api/db/activity.test.js
- api/db/apd.js
- api/db/apd.test.js
- api/db/index.js
- api/migrations/20180313090604_add-activity-goals-and-objectives.js
- api/routes/apds/get.js
- api/routes/apds/get.test.js
- api/routes/apds/openAPI.js
- api/seeds/shared/delete-everything.js
Adds activity goals and objectives tables and data models, and hooks up the relationships.  Updates the `/apds` GET route to fetch the related data and return it all at once.
> Some more data modeling around APD activities

- api/db/activity.js
- api/db/activity.test.js
- api/routes/apds/activities/goals/put.js
- api/routes/apds/activities/goals/put.test.js
- api/routes/apds/activities/index.js
- api/routes/apds/activities/index.test.js
- api/routes/apds/activities/post.js
- api/routes/apds/activities/post.test.js
- api/routes/apds/activities/put.js
- api/routes/apds/activities/put.test.js
- api/routes/apds/index.js
- api/routes/apds/index.test.js
- api/routes/apds/put.js
- api/routes/apds/put.test.js
- api/routes/apds/utils.js
- api/routes/apds/utils.test.js
- api/seeds/test.js
- api/seeds/test/apds.js
Creates all the API-side stuff to support creating and editing APD activities, goals, and objectives.
This PR got pretty big so I'm going to split it into a few.  This one adds the API changes, the next one will add the frontend changes, and then I will create more to add the handful of things missing:
* unit tests on the frontend
* endpoint tests on the backend
* OpenAPI documentation
* logging on the backend
* POST `/apds/:apd_id/activities`
Create a new activity on the APD specified by `apd_id`.  This just creates an activity with a name, no description.  This is based on the UI section for selecting and creating new activities - it begins with just names.  Descriptions are added in a separate form.  The activity name must be unique within the APD (that is, a single APD may not have …
> Add API endpoints to create APD activities, goals, and objectives

- web/src/components/Inputs.js
There exists a `spellcheck` attribute (that's actually well supported across browsers) that we can tap into for our `textarea` inputs. And on right click, it even gives a list of suggested correct spellings! 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck
Preview:
> add basic spellcheck

- web/src/components/PoC.js
- web/src/containers/TopNav.js
- web/src/routes.js
- web/src/styles/app/layout.css
- web/src/styles/app/type.css
- web/src/styles/index.css
Starts implementation of activities add/edit mockup.
Still lots more to do; this is just the start, but you can start to see the dynamic bits.
Viewable at `/poc`
Preview:
> Start prototyping submission experience mockup

- api/middleware/apd.js
- api/middleware/auth.js
- api/middleware/cache.js
- api/middleware/cache.test.js
Fixes middleware cacheing by converting Bookshelf.js model objects into numbers.  The cache is being keyed on an array of the form `[middlewareName, model, other, stuff]` - but it is stored as a plain object with that key as the object property.  However, object properties must be strings, so internally JS is stringifying the key.  No big deal, except ***all Bookshelf.js model objects stringify to null***.
Thus, a cache keyed on `['userCanEditAPD`, APDModel]` is exactly the same as one keyed on `['userCanEditAPD', ActivityModel]`.  Blam, everything breaks - we check whether users can edit APDs based on whichever model happened to be passed in the first time the middleware was cached, and thereafter every access to the cache is a hit and returns the first instance.  (Boo.)
To get around …
> Fix middleware cacheing

- api/db/activity.js
- api/db/activity.test.js
- api/routes/apds/activities/post.js
- api/routes/apds/activities/post.test.js
Adds validation to the APD activity model, and modifies the `/apd/:id/activities` POST endpoint handler to use model validation instead of trying to do validation itself.  This fixes a bug where activity name uniqueness was not enforced when submitting multiple activities at once.
This PR will close #367.
This merges into #378.  When this and #379 are both merged, the tests on #378 should pass so it can be merged too.  :tada:
> Enforce activity name uniqueness

- api/db/activity.js
- api/endpoint-tests/activities/put.js
- api/routes/apds/activities/index.js
- api/routes/apds/activities/index.test.js
- api/routes/apds/activities/schedule/openAPI.js
- api/routes/apds/activities/schedule/put.js
- api/routes/apds/activities/schedule/put.test.js
Adds API endpoints for updating the activity schedule.  Basically a copy+paste job from activity approaches.
Endpoint tests will be in a separate PR.
> Add activity schedule endpoints

- api/db/activity.js
- api/db/activity.test.js
- api/routes/apds/activities/approaches/openAPI.js
- api/routes/apds/activities/expenses/openAPI.js
- api/routes/apds/activities/goals/openAPI.js
- api/routes/apds/activities/openAPI.js
- api/routes/apds/activities/schedule/openAPI.js
- api/routes/apds/openAPI.js
- api/routes/openAPI/index.js
- api/routes/states/openAPI.js
The activity schema was defined in several different files and they were (unsurprisingly) out of sync with each other.  This PR pulls those out into a `component` that can then be referenced elsewhere in the OpenAPI document.  Now as the activity or APD schemas change, we don't have to be careful to update the documentation freakin' everywhere - just do it in one place and it'll be correct by reference.
:tada:
> De-duplicate a bunch of OpenAPI stuff

- bin/deploy-ux-testing.sh
- bin/deploy.sh
The API URL environment variable has a trailing slash, and we use relative URLs with a leading slash.  That results in API calls that begin with a double slash, creating a 404 condition.
> Fix API URL

- bin/deploy-storybook.sh
- bin/deploy-ux-testing.sh
- bin/deploy.sh
This pull request takes the deployment target info (cloud.gov org and space) out of our deployment scripts and puts it into CI environment variables where we can easily change it later without having to modify code.
I added a deployer account and setup the "staging" environment variables in CircleCI, so hopefully this PR will get our staging environment deploying again.  Getting the other environments back into deployment should just be a matter of setting the environment variables in CircleCI.
- ~Design has …
> Fix staging deployment, setup all deploys for easier fixing/updating

- api/db/activity/activity.js
- api/db/activity/activity.test.js
- api/db/activity/contractorResource.js
- api/db/activity/contractorResource.test.js
- api/db/activity/index.js
- api/db/activity/index.test.js
- api/db/activity/statePersonnel.js
- api/db/activity/statePersonnel.test.js
- api/db/apd.js
- api/db/apd.test.js
- api/endpoint-tests/activities/put.js
- api/migrations/20180417181354_activity-personnel.js
Adds the migration and data model info for activity personnel and contractor resources.
Closes #290.
> Add state personnel and contractor resource data models

- api/migrations/0001-initial.js
- api/seeds/shared/delete-everything.js
- api/seeds/shared/roles-and-activities.js
- the new squashed migration couldn't rollback properly because it tried to delete a table that did not exist ('apd' instead of 'apds')
- the `delete-everything` shared seed was missing a couple of tables that reference the activities table, so if anything happened to be in those tables, the seed would fail with a key constraint violation
- the `roles-and-activities` shared seed (the one that's responsible for setting up roles and activities in staging, production, etc.) tried to do some fancy asynchronous logic for setting up the mapping between roles and activities, but that was breaking.  Instead, just build the mappings up and do one big insert.  This works consistently.  The old way was super silly.
- ~The experience passes a …
> Fix a couple of bugs with the database migration tooling

- web/package-lock.json
- web/package.json
- web/src/actions/activities.js
- web/src/components/Icons.js
- web/src/components/Inputs2.js
- web/src/containers/ActivityDetailDescription.js
- web/src/containers/ActivityDetailGoals.js
- web/src/containers/ActivityListEntry.js
- web/src/reducers/activities.js
* changed `updateActivity` action / reducer function to use awesome `updeep` library
* reduxed new `ActivityDetailGoals` component
* created helper components for `Input` and `Textarea` (that create input and associated labels); right now, these are in `components/Inputs2` -- once we nuke `redux-form`, we can replace the original `components/Inputs` (which have some redux-form specific structure and props)
> reduxing goals

- web/src/actions/activities.js
- web/src/components/ConfirmAlert.js
- web/src/containers/Activities.js
- web/src/containers/ActivityDetailAll.js
- web/src/containers/ActivityDetailSchedule.js
- web/src/containers/DeleteActivity.js
- web/src/reducers/activities.js
- web/src/styles/app/confirm.css
- web/src/styles/index.css
- adds ability to remove/delete an activity
- adds a confirmation modal (forked from https://github.com/GA-MO/react-confirm-alert) so that user doesn't hastily delete an activity and lose all the associated info unless they're sure.
Preview:
https://cl.ly/r7F9
Adding @lauraponce as well to get feedback on the look and feel of this
> delete activity (with confirmation)

- web/src/components/Hello.js
- web/src/components/__snapshots__/Hello.test.js.snap
- web/src/containers/Activities.js
- web/src/containers/ActivityDetailAll.js
- web/src/containers/ActivityDetailDescription.js
- web/src/containers/ActivityDetailGoals.js
- web/src/containers/ActivityDetailSchedule.js
- web/src/containers/ActivityDetailStandardsAndConditions.js
- web/src/containers/DeleteActivity.js
- web/src/containers/TopNav.js
- web/src/i18n/index.js
- web/src/i18n/index.test.js
- web/src/i18n/locales/en.json
For the reduxified "activities" section components that are currently in master, moves most (hopefully *all*) of the user-oriented text into resource files.  To make it easier on @quarterback, I also added a way to see what keys the components are looking for to get their text.
- hopefully no immediately visible changes
- in a non-production environment, add `#i18n` to the address to turn off text resolution and see the keys that the components are looking for:
> Move some text into resource files

- web/src/actions/activities.js
- web/src/components/Select.js
- web/src/containers/ActivityDetailExpenses.js
- web/src/reducers/activities.js
- changes expense id field to be `id`, to be more explicitly different than the index of an expense entry within the expenses array (which we also use to update a field within an entry).
- fixes a bug around expense deletion (we were using index instead of id)
- creates a `Select` component
- small style tweaks
> index vs id tweaks

- web/src/actions/activities.js
- web/src/containers/ActivityDetailAll.js
- web/src/containers/ActivityDetailContractorResources.js
- web/src/containers/ActivityDetailSchedule.js
- web/src/i18n/locales/en.json
- web/src/reducers/activities.js
Hooks up the contractor resources section to redux state.  There's a pretty glaring style problem where the start/end date inputs overflow and cover up part of the cost inputs.  I can bang on it and see if I can get something that makes sense, but I was hoping I could convince @brendansudol to take a look at it for me.  😬
Closes #437
- On the `/activities` page, the "contractor resources" section is now visible
> Reduxify contractor resources

- web/src/components/Inputs.js
- web/src/containers/ActivityDetailCostAllocate.js
- web/src/containers/ActivityDetailDescription.js
- web/src/i18n/index.test.js
The rich textbox exists in the several places in the code, each with its own distinct state management and configuration.  This pull request extracts that so the state management and configuration is in just one place in the code.
- no visible changes, sorry!
> Make the rich textbox into a reusable component

- web/src/actions/activities.js
- web/src/components/Collapsible.js
- web/src/components/SidebarLink.js
- web/src/containers/ActivityDetailAll.js
- web/src/containers/Sidebar.js
- web/src/reducers/activities.js
- allows for programmatic opening / closing of activity sections
- updates to `Collapsible` component so that it can be a controlled vs controlled component
- opens activity section if activity link clicked on from sidebar
> open / close activity sections via redux actions

- web/src/components/HelpText.js
- web/src/containers/ActivityDetailContractorResources.js
- web/src/containers/ActivityDetailCostAllocate.js
- web/src/containers/ActivityDetailDescription.js
- web/src/containers/ActivityDetailExpenses.js
- web/src/containers/ActivityDetailGoals.js
- web/src/containers/ActivityDetailSchedule.js
- web/src/containers/ActivityDetailStatePersonnel.js
- web/src/containers/ApdSummary.js
- web/src/i18n/locales/en.json
From Ron's content design work, add help text to the resource file and use that to populate help text in various parts of the site.
[See it here](http://cms-hitech.darkcooger.net.s3-website-us-east-1.amazonaws.com/)
Note: Several sections of the help text content doc aren't represented in the web app yet, so I left the text out for sections.
- HIE checklist
- Proposed budget
- Expenses summary
- Assurances & compliance
- Executive/overall summary
- Budget tables
- Certify and submit
- adds help and "REMEMBER!" text
> Add help text

- README.md
Configured Snyk, disabled Gemnasium, and updated the README accordingly.
Snyk will report vulnerabilities as checks in our pull requests.  :tada:
Closes #517
- on the front page of the repo, you will now see to vulnerability badges - one is for the web project, the other is for the API project
- the "code quality" badge is removed; we turned it off a long time ago and it has been a useless badge ever since (it was flagging a whole lot of things that weren't problems and was not flagging things that mattered to us) …
> Switch to Snyk

- web/src/containers/Sidebar.js
- web/src/i18n/locales/en.json
Moves sidebar text into the resource file.  There's one little quirk here for @quarterback and @brendansudol to be aware of:  there are basically two entries for the title of individual activities in the side bar:
The one for `Activity 1` references the `activity-unset` title, and is used when the activity name hasn't been set yet.  The one for `Activity 2: ...` references the `activity-set` title, and it's used then the activity name has been set.
- no immediately visible changes
- allows @quarterback to tweak sidebar text without having to deal with code
- …
> Extract text from sidebar

- web/src/components/AssurancesAndCompliance.js
- web/src/components/CertifyAndSubmit.js
- web/src/components/ExecutiveSummary.js
- web/src/components/PreviousActivities.js
- web/src/components/ProposedBudget.js
- web/src/containers/Activities.js
- web/src/containers/ApdSummary.js
- web/src/i18n/locales/en.json
Adds helper text to each section.  Right now it's an unstyled `h3`, but we can style it later.  😄
Closes #536
- Every section has some placeholder "helper" text
> add h3 for help text for each section

- .circleci/config.yml
Currently attempts to run a script that exists in our repo without first checking out the repo.  Whoops, can't run code that isn't there.  :)  This fix adds a checkout step before trying to run the script.
- the nightly CI script that prunes unneeded PR-specific deploys will run
> Fix nightly CircleCI task

- web/src/i18n/locales/en.json
This is required for all submissions, so adjusting help text to reflect this. HIE and MMIS sections are optional, so this text can remain, but it should be removed for HIT.
- HIT Overview section help text.
> Removed help text to skip HIT Narrative sections.

- api/db/activity/contractorResource.js
- api/db/activity/contractorResource.test.js
- api/db/activity/schedule.js
Following on from #556, uses the `moment` library to validate dates, and accepts/returns dates as `YYYY-MM-DD` format instead of the full date-time format.
> Fix contractor resources date strings

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/actions/auth.js
- web/src/actions/auth.test.js
- web/src/components/Inputs.js
- web/src/containers/Sidebar.js
- web/src/reducers/activities.js
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
- web/src/routes.js
https://hitech-apd-pr544.app.cloud.gov/
- makes the main page "protected" (meaning, you have to login)
- on successful login or auth check, go ahead and fetch the user's APDs and use the first one returned as the current APD
- an "auth check" happens when you first load the page - if you're already logged in, it just proceeds; otherwise it drops you at the login screen
- there's some future work indicated here: how to pick which APD the user should be looking at, maybe there's a landing page before this, etc.
- populates the application state with the data from the API
- adds a temporary save button that saves the application state to the API
Addresses #394
- can save and resume editing an APD
- ~The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text …
> Hookup APD frontend to backend

- web/package-lock.json
- web/package.json
- web/src/components/Md.js
- web/src/i18n/index.js
- web/src/util/md.js
I did a bunch of experimenting with a good way to integrate our translation strings with markdown support. Wasn't super happy with any of the component APIs I was creating, but here's something to get the conversation started. I'm very happy with alternative ideas.
This keeps the translations strings and the convert-markdown-to-html steps separate, mainly because there are times when we want both i think.
Example usage of this component:
`<Md wrapper="h3" content={t('apd.helpText')} className="regular h1" />`
The wrapper represents the enclosing html element and any additional props (i.e.,  `className`) get passed along too. Why `md.renderInline` and not `md.render`? Because `render` adds paragraph tags around the text which we probably don't want. I would like to support passing in …
> add markdown component

- web/package-lock.json
- web/package.json
- web/src/components/Inputs.js
- web/src/containers/ActivityDetailContractorResources.js
- web/src/containers/ActivityDetailCostAllocate.js
- web/src/containers/ActivityDetailExpenses.js
- web/src/containers/ActivityDetailStatePersonnel.js
- web/src/util/masks.js
- adds this nifty library (https://text-mask.github.io/text-mask/) so we can have nicely formatted inputs as users type stuff
- adds dollar and percent `MaskedInput`s to the appropriate activity form fields 
Addresses: https://github.com/18F/cms-hitech-apd/issues/515
Preview:
https://cl.ly/rdPp
> add form field masking

- .circleci/config.yml
- bin/deploy.sh
Make the built webapp available as a zip file.  It's stored as a CircleCI build artifact.  This one is for @NAretakis.  🙂
- after merges to master, the most recent webapp build will be available as a CircleCI artifact for downloading and _doing whatever you want_ with
> Zip web build on deploy

- web/src/components/AssurancesAndCompliance.js
- web/src/components/CertifyAndSubmit.js
- web/src/components/ExecutiveSummary.js
- web/src/components/HelpText.js
- web/src/components/PreviousActivities.js
- web/src/components/ProposedBudget.js
- web/src/components/Section.js
- web/src/containers/Activities.js
- web/src/containers/ActivityDetailContractorResources.js
- web/src/containers/ActivityDetailCostAllocate.js
- web/src/containers/ActivityDetailDescription.js
- web/src/containers/ActivityDetailExpenses.js
- web/src/containers/ActivityDetailGoals.js
- web/src/containers/ActivityDetailSchedule.js
- web/src/containers/ActivityDetailStandardsAndConditions.js
- web/src/containers/ActivityDetailStatePersonnel.js
- web/src/containers/ApdSummary.js
- web/src/i18n/locales/en.json
Title, subheader, and helptext are looking like they're common parts of our section/subsection structure.  This PR puts those things into the `Section` component and adds a `Subsection` component for the same purpose.
@quarterback: under activities, under the "activity description" subsection, I'm not sure what the label should be for the activity section box.  There wasn't anything in the resource file that clearly mapped to it.
- some minor changes to how the resource file is structured
- every major section supports `title`, `subheader`, and `helpText` resource strings
- every subsection (the collapsable pieces) supports `title`, `subheader`, `helpText`, and `reminder` resource strings
> Add standard text elements to sections/subsections

- web/src/styles/app/layout.css
- fixes a small bug where certain buttons on the rich text editor were appearing in front of our sticky activity header when scrolling; adding a smidge of z-index fixes it :)
> add z-index to sticky class

- web/src/i18n/locales/en.yaml
Added helptext for the new previous activities section.
> Helptext for previous activities

- web/src/actions/activities.js
- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/containers/ActivityDetailAll.js
- web/src/containers/ApdSummary.js
- web/src/containers/BudgetSummary.js
- web/src/containers/ExecutiveSummary.js
- web/src/reducers/activities.js
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
- web/src/reducers/budget.js
- web/src/util/index.js
Closes #462
Closes #630
Closes #631
Closes #632
Closes #641
- no hidden 2020 expenses!
- if you DESELECT a year for which data has been entered, that data will be lost
- need a separate issue to discuss/design the right solution - could just hide that data, or prompt the user to confirm that they want to destroy it
- if we just hide it, what happens when the APD is saved?
> Use years throughout the app based on the APD summary selection

- web/src/actions/activities.js
- web/src/reducers/activities.js
- web/src/reducers/budget.js
Also fixes a bug where you couldn't add new personnel, contractor, or expense rows.  😬
Closes #645
- deleting any of those kinds of rows will update the budget table
- deleting an activity will update the budget table
- you can add more of those kinds of rows
- ~Tests have been updated (and all tests are passing)~ Big tests overhaul coming soon, this will get wrapped up into that
> Fix: Deleting personnel, contractor, or expense rows triggers a budget table update

- api/db/activity/statePersonnel.js
- api/db/activity/statePersonnel.test.js
- web/src/actions/apd.js
- web/src/containers/ActivityDetailStatePersonnel.js
- web/src/reducers/activities.js
- web/src/reducers/budget.js
Closes #651
- adjusts the state personnel costs in the budget table according to the FTE% assigned to the row
- FTE% is not limited to 100%; however, the database currently caps it at 999.99% - we can remove/raise that cap in a separate pull request (it requires a migration and I'm not 100% sure how to do it without destroying data)
- the budget table updates when the FTE% is modified
> Fix: Adjust personnel costs according to FTE%

- api/routes/apds/activities/openAPI.js
- api/routes/apds/openAPI.js
- api/routes/auth/activities/openAPI.js
- api/routes/auth/roles/openAPI.js
- api/routes/me/openAPI.js
- api/routes/openAPI/auth.js
- api/routes/openAPI/index.js
- api/routes/states/openAPI.js
- api/routes/users/openAPI.js
This might be helpful for @NAretakis and @jeromeleecms with respect to "poking" the API.  Will follow-up in Slack with info about how this is useful after it's merged.
The short version is the API documentation is now sectioned off, and each endpoint has a nice little piece of text showing you what it is before you expand it:
- nothing visible
> Flesh out OpenAPI with more metadata to make it more navigable

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/components/temp/MiscPage.js
- web/src/containers/ActivityDetailCostAllocate.js
- web/src/containers/ActivityDetailCostAllocateFFP.js
- web/src/i18n/locales/en.yaml
- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
- web/src/reducers/budget.js
- web/src/reducers/budget.test.js
- web/src/util/index.js
- web/src/util/index.test.js
This PR reworks the cost allocation as per https://github.com/18F/cms-hitech-apd/issues/685.
In summary
* one can specify a per-activity other amount, which comes off the top before computing the federal and state amounts
* the federal / state percentages can now we only 1 of 3 things (90/10, 75/25, 50/50)
The budget summary data munging methods are adjusted to reflect this new math/logic. 
preview:
https://cl.ly/sKrg
> rework cost allocation

- web/src/containers/QuarterlyBudgetSummary.js
- web/src/i18n/locales/en.yaml
Takes user-facing text out of the code and puts it in the resource file.  Closes #678.
- text is in the resource file
> Move quarterly budget table text into resource file

- web/package-lock.json
- web/package.json
- web/src/containers/ScheduleSummary.js
- web/src/reducers/activities.js
- web/src/styles/app/table.css
Adds `react-table` and makes apd schedule summary table sortable (resolves https://github.com/18F/cms-hitech-apd/issues/688)
And I think we can utilize more of the features of `react-table` over time (filtering, editable text, etc).
> sortable table

- api/db/activity/costAllocation.js
Fixes a bug where saving the APD would fail because cost allocation column names didn't match the property names.
> Fix saving cost allocations

- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
Despite what #644 says, we were already sending the activity funding source info to the API, storing it, and returning it.  The one thing we weren't doing was reading it from the API and using that to drive the GUI.  That's fixed now.
Closes #644.
- reloading an APD will also restore activities' funding source radio buttons to the right values
> Read activity funding source from the API

- api/db/apd.js
- api/db/apd.test.js
- api/migrations/20180625133221_apd-specific-state-info.js
- api/routes/apds/openAPI.js
- api/routes/openAPI/index.js
- docker-compose.yml
- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/containers/ApdStateProfile.js
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
Adds state profile information to the APD data model and updates the code to read/write that information, as expected.  Polishes up the data handling on the frontend to hook them up.
Addresses part of #700.
- saving an APD will also save state profile information
- loading an APD will also load that APD's state profile information
> Save state profile with APD [skip deploy]

- api/db/apd.js
- api/db/apd.test.js
- api/db/apdPreviousActivityExpense.js
- api/db/apdPreviousActivityExpense.test.js
- api/db/index.js
- api/migrations/20180625174013_apd-previous-activities.js
- api/routes/openAPI/index.js
- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/containers/DeleteActivity.js
- web/src/reducers/apd.js
Closes #694 
- previous activity summary and expenses are saved to the API
- previous activity summary and expense info is loaded when APDs are loaded
> Save "previous activity" info in the API, and return it when loading an APD [skip deploy]

- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
Activities will start with 1 milestone each, instead of 3. However users will have the ability to add new milestones as needed.
> Sets default of 1 milestone for activities

- api/db/apd.js
- api/db/apd.test.js
- api/db/state.js
- api/endpoint-tests/apds/put.js
- api/middleware/synchronize.js
- api/middleware/synchronize.test.js
- api/routes/apds/openAPI.js
- api/routes/apds/post.js
- api/routes/apds/post.test.js
- api/routes/apds/put.js
- api/routes/apds/put.test.js
- api/routes/states/put.js
- api/routes/states/put.test.js
Modifies the API behavior in two ways:
- when a new APD is created, if the state already has a profile configured, the profile is copied into the APD
- when an APD is saved, if it has state profile information, the state model's profile info is updated with the info from the APD
Closes #700
Closes #701
- new APDs will have state profile information, if any is defined
> Initiate APD with state profile from state model, update state model when APD is saved with state profile

- web/src/actions/apd.test.js
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
Fixes #731 
- when you load an existing API, the previous activity expenses table will show up
> Set default previous activity expenses if none provided by the API

- web/src/actions/apd.js
- web/src/components/DeleteConfirm.js
- web/src/containers/ActivityDetailAll.js
- web/src/containers/ActivityDetailAll.test.js
- web/src/containers/ActivityListEntry.js
- web/src/containers/ApdStateProfilePointsOfContact.js
- web/src/containers/__snapshots__/ActivityDetailAll.test.js.snap
- web/src/i18n/locales/en.yaml
- web/src/reducers/apd.js
From @lauraponce's comment at https://github.com/18F/cms-hitech-apd/pull/767#issuecomment-402811352, this PR modifies the add contact button text to support different text for the case where there are currently 0 contacts, currently 1 contact, and currently more than 1 contact.
No contacts yet:
One or more contacts already:
Modifies the `DeleteActivity` component to be generic so we can reuse it, and then promptly reuses it.
- "add contact" button text changes to be more useful
- add "remove" button for contacts
> Conditional "Add Contact" button text

- web/src/components/ApdApplication.js
- web/src/components/Container.js
- web/src/components/__snapshots__/ApdApplication.test.js.snap
- web/src/components/__snapshots__/Container.test.js.snap
- web/src/styles/app/layout.css
- web/src/styles/index.css
moves away from `position:sticky` ([not supported in IE](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Browser_compatibility)) to `position:fixed` which should look the same as before and now work in IE :)
> cross browser sidebar

- web/src/actions/apd.js
- web/src/containers/QuarterlyBudgetSummary.js
- web/src/reducers/budget.js
- web/src/reducers/budget.test.js
- web/src/util/index.js
Instead of calculating the federal share in the UI component and in the APD submission process, we now calculate it along with all the other budget data in the application state reducer.  One place!
Most of the code change addition is updating the reducer tests...  :)
Closes #762
> Move quarterly federal share calculations into reducer [skip deploy]

- web/src/actions/sidebar.js
- web/src/actions/sidebar.test.js
- web/src/components/SidebarLink.js
- web/src/components/SidebarLink.test.js
- web/src/components/__snapshots__/SidebarLink.test.js.snap
- web/src/containers/Sidebar.js
- web/src/reducers/index.js
- web/src/reducers/index.test.js
- web/src/reducers/sidebar.js
- web/src/reducers/sidebar.test.js
Starts the sidebar with major sections collapsed and makes them expandable.
@lauraponce When you click on a section in the sidebar, should that section expand as well as navigate the page?  (from https://github.com/18F/cms-hitech-apd/issues/781#issuecomment-403986690)
Closes #781
- reducer and action tests
- the major sections in the sidebar are collapsed by default
- clicking the up/down arrows will expand/collapse the link section without navigating the page
> Collapsible sidebar links

- web/src/components/NoDataMsg.js
- web/src/containers/ActivityDetailContractorResources.js
- web/src/containers/ActivityDetailExpenses.js
- web/src/containers/ActivityDetailSchedule.js
- web/src/containers/ActivityDetailStatePersonnel.js
- web/src/containers/__snapshots__/ActivityDetailContractorResources.test.js.snap
- web/src/i18n/locales/en.yaml
- web/src/styles/app/table.css
adds a tasteful 'no rows/data' message if you remove all the entries from the state personnel / contractor / expenses sections (instead of showing an ugly table with just columns and no rows)
preview:
> no table data UI

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/containers/ActivityDetailCostAllocate.js
- web/src/containers/ActivityDetailCostAllocateFFP.test.js
- web/src/containers/ActivityQuarterlyBudgetSummary.js
- web/src/containers/QuarterlyBudgetSummary.js
- web/src/containers/__snapshots__/ActivityDetailCostAllocate.test.js.snap
- web/src/i18n/locales/en.yaml
- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
- web/src/reducers/budget.js
- web/src/reducers/budget.test.js
- web/webpack.config.js
Closes #756!
- removes the sliders from the federal share by FFY quarter summary table
- adds a new table to the activity cost allocation section
- this table lets the user set the federal share percentage for each quarter of each FFY, for each expense type, and live updates the dollar amounts
- updates the summary table to take into account the percentages applied to each activity instead of applying a global percentage
- content (there's a rogue `moop moop` floating around the new cost allocation table because I wasn't sure what it should be) - pinging @jeromeleecms and @quarterback for that one
- budget calculation tests
> Set federal share percentage per activity, per FFY quarter

- web/src/reducers/apd.js
- web/src/util/index.js
- web/src/util/index.test.js
this fixes a bug where we were getting console errors because controlled inputs had a value of `null` (which React doesn't like) in the State Profile section; the fix was to create a helper function that converts nulls to empty strings for objects received from API.
> bug fix (null inputs)

- web/package-lock.json
- web/package.json
- web/src/components/temp/MiscPage.js
- web/src/styles/app/editor.css
Now, we can copy and paste in sentences with bold and italics and yes, even lists, from Word or Google Docs into our rich text editors and it should now work. 🤞 
This was tricky to track down because the library we were using (https://github.com/jpuri/react-draft-wysiwyg) allows for this functionality and it works great on their demo page but it wasn't working for us. The reason: we were using the latest version of this package and they recently made some changes to fix other things that in turn broke this copy/pasting (and their demo page kept working fine because it never upgraded to the latest version). So all I had to do was revert to the version that's being used on their demo page and all is now good :)
Preview:
https://cl.ly/t0Lj
> fix rich editor copy and paste

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
Closes #804.
- When submitting an APD, the activity quarterly FFP tables are also saved
> Save activity quarterly FFP when submitting APD

- api/auth/authenticate.js
- api/auth/authenticate.test.js
- api/auth/index.js
- api/auth/index.test.js
- api/auth/serialization.js
- api/db/user.js
- api/db/user.test.js
- api/endpoint-tests/auth/login.js
- api/endpoint-tests/me/get.js
- api/routes/me/get.js
- api/routes/me/get.test.js
- api/routes/me/openAPI.js
- web/src/actions/auth.js
- web/src/actions/auth.test.js
- web/src/containers/ApdApplication.js
- web/src/reducers/user.js
- web/src/reducers/user.test.js
Sends back useful user information from the API when logging in or checking your current authentication status.  Captures that user information in the app and stores it in the user application state.  Then we can do cool stuff with it.
- the state name and graphic displayed in the sidebar will match the state associated with your user account
> Fix place display [skip deploy]

- .circleci/config.yml
- api/package-lock.json
- bin/deploy.sh
- web/package-lock.json
- web/package.json
The Snyk web tool ignores `package-lock.json` and instead inspects our dependencies based on the _highest version_ of a library that our `package.json` says is acceptable.  This leads to false negatives.
The Snyk CLI tool scans what is actually installed.  Because we install explicitly from `package-lock.json` in our CircleCI config (and our deploy as well), the CLI tool will scan against the versions of libraries that we actually use.
- no visible changes to the product
- should start seeing some failing tests
> Switch vulnerability scan to CLI instead of web tool [skip deploy]

- .circleci/config.yml
- api/docker-compose.endpoint-tests.yml
- api/endpoint-tests/activities/put.js
- api/endpoint-tests/files/download.txt
- api/endpoint-tests/files/get.js
- api/routes/files/get.js
- api/routes/files/get.test.js
- api/routes/files/openAPI.js
- api/routes/index.js
- api/routes/index.test.js
- api/routes/openAPI/index.js
- api/seeds/shared/delete-everything.js
- api/seeds/test.js
- api/seeds/test/apds.js
- api/seeds/test/files.js
Adds an API endpoint at `GET /files/:key` for downloading files.  The authorization logic goes like this:
1. does the file exist in the database?
2. does the file exist in the file store?
3. does the file belong to an APD that the user has access to?
- a file belongs to an APD if the file is associated with an activity in the APD, OR if the file is associated with a contractor that is associated with an activity in the APD
Also associated with #735
Endpoint tests and OpenAPI documentation
> Add file download endpoint to the API

- web/src/components/HelpText.js
- web/src/components/__snapshots__/HelpText.test.js.snap
- web/src/i18n/locales/en.yaml
- web/src/styles/app/alert.css
- web/src/util/md.js
Addresses and closes https://github.com/18F/cms-hitech-apd/issues/830
The reminder field now also supports using markdown or html in our big yaml file. for example:
`foo: This has something **bolded**.`
> new help text stylez

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/reducers/activities.js
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
- web/src/util/serialization/activities.js
- web/src/util/serialization/activities.test.js
- web/src/util/serialization/apd.js
- web/src/util/serialization/apd.test.js
When you click the "create an APD" button, it is created and then opened.  Just one click!
Also removes a lot of APD initialization and defaulting code since the API generates a valid APD now.  There's no need for the frontend code to do it.
Closes #876 
- click the "create an APD" button, get taken to your fancy-pants 👖 new APD
> Automatically open new APDs + some frontend cleanup

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/components/Icons.js
- web/src/containers/ApdApplication.js
- web/src/containers/Landing.js
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
Reloading previous APD:
- if you browse to the `/apd` page AND
- your browser supports local storage AND
- your local storage contains the ID of the last APD you looked at THEN
- select your previous APD once APDs are loaded from the API
Storing previous APD
- if you're on the `/` page AND
- you select an APD from the list AND
- your browser supports local storage THEN
- the APD ID is written to local storage so we can reload it next time
Closes #802 
- if you're looking at an APD and you reload the page, you'll end up right back at that APD
- the `/` page gets a "loading" spinner so you know it's fetching your APDs
> Reload previous APD where the makes sense

- api/routes/apds/post.data.js
- api/routes/apds/post.data.test.js
- web/src/components/Label.js
- web/src/containers/activity/ContractorResources.js
- web/src/containers/activity/Expenses.js
- web/src/containers/activity/StatePersonnel.js
- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
brings personnel section in line with the new structure / style of contractor and expense sections.
(now that stuff is not in a table, i don't think we need to prefill 3 blank entries, hence the switch to 1)
> state personnel refine

- web/src/containers/activity/Expenses.js
- web/src/styles/app/misc.css
related to https://github.com/18F/cms-hitech-apd/issues/938, adds clickable list entries for expenses so you can see the relevant info at a glance and/or edit when needed.
> add list row entries for expenses

- web/package-lock.json
- web/package.json
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
there was a bug where if you added a year to your APD, the app blew up (because we weren't initializing incentive payment data for this new year). This PR resolves that.
> fix apd year change bug

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- web/src/reducers/budget.js
- web/src/reducers/budget.test.js
The budget state has a prop called `quarterly` that's leftover from an earlier version of computing quarterly budget - it's now activity based instead, but this tidbit was never cleaned up.  This PR yanks it out.
This is a piece of #883
> Remove an unused budget prop [skip deploy]

- .gitattributes
- web/package-lock.json
As described in [Managing generated files in Github](https://medium.com/@clarkbw/managing-generated-files-in-github-1f1989c09dfd), we can setup our `.gitattributes` to automatically collapse generated files in diff view, as well as suppress them in `git diff` view and have `git merge` just plow over them, which feels like exactly what we want.
:hat-tip: to @randyhart for the article and the inspiration
> ignore generated files [skip deploy]

- web/.eslintrc.json
- web/src/reducers/budget.js
- web/src/reducers/budget.test.js
- web/src/util/index.js
Refactors the budget reducer to be more straightforward (🤞).  The sequence of computing all the budget data is now almost linear, making it hopefully easier to track where things happen.  Also, lots of comments to explain what's going on.
Closes #883 
> Refactor budget reducer [skip deploy]

- web/src/containers/activity/ContractorResources.js
- web/src/containers/activity/ContractorResources.test.js
- web/src/containers/activity/Expenses.js
- web/src/containers/activity/StatePersonnel.js
- web/src/containers/activity/__snapshots__/ContractorResources.test.js.snap
Completes and closes: https://github.com/18F/cms-hitech-apd/issues/938
This adds entries for contractor section. There is now a bit of duplicate code around toggling and editing these entries across these three sections (contractors, personnel, expenses), but that's probably fine for now and refactoring to a higher level component might make it too confusing...
> add entries atop contractor section

- web/src/components/DatePickerWrapper.js
as @jeromeleecms discovered, the app was crashing if a date was edited via the keyboard - the reason for this: while a date is being edited and before it's a valid date, it's actually stored as null in our redux store, which our reducer didn't like; making this an empty string instead fixes this (and is equivalent to what the date field is on initiation anyway)
> hotfix: fix app crashing when date becomes null

- api/db/file.js
- api/db/file.test.js
- api/db/index.js
- api/endpoint-tests/activities/put.js
- api/package-lock.json
- api/package.json
- api/routes/files/delete.js
- api/routes/files/delete.test.js
- api/routes/files/get.test.js
- api/routes/files/index.js
- api/routes/files/index.test.js
- api/routes/files/openAPI.js
- api/routes/files/post.js
- api/routes/files/post.test.js
- api/routes/index.js
- api/routes/openAPI/index.js
- api/seeds/test/files.js
- api/store.js
- web/src/actions/activities.js
- web/src/actions/activities.test.js
- web/src/actions/apd.js
- web/src/containers/activity/ContractorResources.js
- web/src/containers/activity/ContractorResources.test.js
- web/src/containers/activity/__snapshots__/ContractorResources.test.js.snap
- web/src/util/serialization/activities.js
- web/src/util/serialization/activities.test.js
Skipping deploy because it won't work until the API is also deployed, and the PR-based deploys only do the frontend, not the backend.
Closes #839
- when you create a new contractor, the APD is saved - that way the contractor exists in the database, so we can attach files to it later
- when you select a file to add to a contractor, the file is uploaded immediately and then attached to the contractor
> Upload file contracts [skip deploy]

- api/routes/apds/versions/post.js
- api/routes/apds/versions/post.test.js
- web/src/components/Icons.js
- web/src/containers/CertifyAndSubmit.js
- web/src/i18n/locales/en.yaml
- web/src/reducers/apd.js
Addresses #833
The button is disabled until they've typed something into the box.
I left the date/time out for now because there's not a mechanism for getting that information from the API.  It shouldn't be a big lift to add it, just need to do it.
- updates the layout of the certify/submit section
- adds a separate certify/submit layout for when the APD has already been submitted
> Update certify/submit UI

- web/src/i18n/locales/en.yaml
Adjusts the quarterly tables within activities and summary to reflect In-House and Private Contractor naming. Closes #783
> Bugfix - quarterly table row naming match

- web/src/i18n/locales/en.yaml
For both #1001 (yaml reversion) & #1005 (key personnel)
- help text changes reverts reminder text to help text, with additional changes.
- wrote reminder text for key personnel section
> Key personnel reminder text & help text reversions

- api/routes/apds/post.data.js
- api/routes/apds/post.data.test.js
The API had 2018, 2019, and 2020 hard-coded into newly-created APDs.  This PR updates the API so that it calculates the current FFY and uses that as the basis for everything date-related in the new APD.
Closes #1048 
- when you create an APD, its first FFY should be the current FFY, not 2018, unless you have a time machine
> Fix the federal fiscal years on newly-created APDs

- web/src/i18n/locales/en/activities/overview.yaml
Digging through an old en.yaml file, this adds back in the text that was missing from the standard helptext activity overview. If this works, this should close #1024.
Note: Also using this as a learning experience to see how to edit the YAML files. 
@jameshupp Feel free to edit the language. I took a look at #1056 and this change does not overlap with your proposed changes.
- Adds text "Include as much detail necessary to explain the activity." to the helpText in the overview section
> Restores missing helpText to the Standard Activity Overview section

- bin/cleanup-pr-deploys.sh
Adds three bytes to the codebase.
(The `apt-get install` step includes a confirmation prompt.  In CircleCI, there's no one there to say yes, so it times out and fails.  Add the `-y` option to make it just accept whatever we told it.)
- no visible changes, but maybe this time it'll actually work
> Another epically large pull request, this one even bigger than the last.  I am going for a record.

- api/routes/apds/index.js
- api/routes/apds/index.test.js
- api/routes/apds/openAPI.js
- api/routes/apds/submitted/get.js
- api/routes/apds/submitted/get.test.js
The endpoint requires the `submit-federal-response` activity permission and returns all APDs whose status is not `draft`.
Closes #1092
> Add an API endpoint to allow CMS analysts to fetch all submitted APDs

- api/routes/apds/index.js
- api/routes/apds/index.test.js
- api/routes/apds/openAPI.js
- api/routes/apds/status/put.js
- api/routes/apds/status/put.test.js
Just what it says on the tin.  A couple of notes:
- the endpoint returns an error if an analyst tries to set an APD's status and the APD is currently in draft (i.e., CMS analysts are not allowed to change an APD's status until a state has submitted it)
- the endpoint returns an error if an analyst tries to set an invalid status; valid statuses are (currently):
- `in review`
- `state response`
- `in clearance`
- `approved`
- `denied`
(this list is pending the discussion in #1029)
- no visual changes
> Add endpoint for CMS analysts to set APD status

- web/src/styles/app/table.css
For some reason, IE doesn't hide the borders on the spacer cells. Ugh.
- hide right border
> Fix for scrolly tables in IE

- web/src/containers/StateDashboardCurrentDocuments.js
- web/src/containers/__snapshots__/StateDashboardCurrentDocuments.test.js.snap
Just what it says on the tin.  Those things are confusing and shouldn't be there - they were only ever meant to demo what the various status/progress things might look like.  Now that we've moved on from that, they're just noise!
- state dashboard should only show active APDs in the "Current Statuses" section
> Remove "example" document items from the state dashboard

- api/package-lock.json
- Through a several-layers-deep dependency (`nodemon` ➡️ `pstree.remy` ➡️ `ps-tree`), we were bringing in a [vulnerability in the `event-stream` library](https://github.com/dominictarr/event-stream/issues/116).  The things we actually depend on have been updated and `event-stream` no longer appears in our dependencies at all.
- Via the [`request`]() library, we have a dependency on `har-validator`.  The author of `har-validator` introduced a breaking change in version 5.1.2 that only affected some users - not us.  However, when the author was notified, rather than simply issue a version 5.1.3 that reverted the breaking change, they [removed version 5.1.2 altogether](https://github.com/ahmadnassri/node-har-validator/issues/112).  Unfortunately, while 5.1.2 was still active, our …
> Update dependencies - one vulnerability, one mismanaged

- web/package.json
Work doesn't continue without our CMS COR. I would like to add Eg to our list of contributors, but would be OK if we created a "Special Thanks" somewhere in the app as an alternative.
- No visible changes. Only updates contributors.
> Adding the CMS COR

- bin/deploy-pr.sh
- web/src/util/formats.js
- web/src/util/formats.test.js
Fixes #1225
- Dollar amounts in the billions or quadrillions will now display the correct suffixes
- `$1.23G` becomes `$1.23T`
> Convert SI prefixes on currency to thousands-scale prefixes

- bin/cascade-delete-apd.js
This script will let you generate the SQL statements for a complete APD deletion, either for a single APD by ID or all APDs for a given state.  (To delete ***all*** APDs, just truncate the table with cascade.)  You can pipe the SQL into the psql terminal of your choice, or paste them into something else, or print them and frame them on the wall or whatever, really!
- stops me from losing this script all the time
> Enshrine this stupid script in the repo so I stop losing it

- web/src/i18n/locales/en/proposedBudget.yaml
Addresses #1164.
I went back and forth on this for a bit, trying to figure out how to say `EH Payments` differently in the table, but I think it works way better to change the instruction copy. Now it explains those words more clearly; the words are unchanged. (This has the bonus benefit of not requiring any code, which changing table headers would have required. I don't really like that setup fwiw.) I also got a bit more specific about "calculate"; the previous wording made it seem like `payments` may mean amount per payment.
No need for an accessibility audit, as this only changes text that was confusing in the first place.
> Clarify what Payment and Count are

- web/package.json
I removed the part of our deploy that copied the Staticfile configuration into our distributable package.  For some reason I thought we weren't using it anymore, but that's not right.  😬  This PR puts it back.
- locations other than `/` will work again
> Fix 404 on routes other than /

- docker-compose.yml
Use delegated volumes for improved performance on macOS:  https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
You should only need to bounce everything to get the new settings:
```
docker-compose down
docker-compose up
```
> Update docker-compose config

- api/routes/me/__snapshots__/put.endpoint.js.snap
- api/routes/me/openAPI.js
- api/routes/me/put.endpoint.js
- api/routes/me/put.js
- api/routes/me/put.test.js
- api/routes/openAPI/__snapshots__/get.endpoint.js.snap
Closes #1360
- updates the `PUT /me` route to ignore email addresses
> Don't allow users to update their own email address

- web/src/components/Collapsible.js
- web/src/components/Section.js
- web/src/components/__snapshots__/Collapsible.test.js.snap
- web/src/components/__snapshots__/ProposedBudget.test.js.snap
- web/src/components/__snapshots__/Section.test.js.snap
- web/src/containers/__snapshots__/ApdSummary.test.js.snap
- web/src/containers/__snapshots__/AssurancesAndCompliance.test.js.snap
- web/src/containers/__snapshots__/ExecutiveSummary.test.js.snap
- web/src/containers/__snapshots__/PreviousActivities.test.js.snap
- web/src/containers/__snapshots__/ScheduleSummary.test.js.snap
- web/src/containers/activity/EntryDetails.js
- web/src/containers/activity/__snapshots__/ContractorResources.test.js.snap
- web/src/containers/activity/__snapshots__/CostAllocate.test.js.snap
- web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap
- web/src/styles/app/editor.css
- web/src/styles/scss/section.scss
Closes #1344. No more accordions in sections, yay! I believe the only place the `Collapsible` element is used now is in the Activity section, to collapse activities down to a readable list. 
There is a little weirdness in those Activity sections: the `Collapsible` component passes its children to `Subsection` for reasons I don't entirely understand (I feel like it probably doesn't actually need to, but I'd like to look at this with @mgwalker). Because of this, the headings in those subsections need to be `h4` instead of `h3`. There's a little bit of repetitive code to make this work (by checking whether the subsection has a `nested` property.
- Removes the `Collapsible` component from `Subsection`.
- Applies the correct heading to `Subsection` titles (including taking into account whether …
> Un-collapse subsection accordions

- .circleci/config.yml
- README.md
- api/package.json
- docker-compose.yml
- docs/docker.md
- web/Dockerfile
- web/package.json
This PR gives our web and API Docker images names and tags.  The names are `cms-eapd/web` and `cms-eapd/api`, respectively, and the tags are the MD5 hashes of their respective `package-lock.json` files.  Running `npm install` in either the web or API directories will automatically update the `docker-compose.yml` file with new tags.
Why?
By having named and tagged images, we will be able to more easily switch between branches with different dependencies.  Instead of destroying and rebuilding images every time you switch, you'll be able to switch and just run `docker-compose up` again to switch images.  If the image tag doesn't exist yet, it'll be built and then switched in, but if you already have it, it'll speed things up considerably.
Caveat: to update the tags, you'll need to run `npm …
> Create names/tags for our Docker images based on dependencies

- web/src/containers/ApdStateProfileMedicaidOffice.js
- web/src/containers/__snapshots__/ApdStateProfileMedicaidOffice.test.js.snap
- web/src/styles/index.scss
- web/src/styles/scss/forms.scss
**Note: This PR is against #1397, not `master`**
I started off making suggested changes in the original PR, but realized it was going to be easier to follow my logic if I just opened a patch PR. Feel free to take or leave as much of this as necessary! Essentially, I tried to make this implementation as vanilla as possible so that we can figure out where we need to deviate from the design system. This means that it doesn't match the mocks exactly, but that's actually okay in this case!
- Removes the `h4`s in favor of using the `fieldset` (both are equally semantic in this case), which also removes the need to make the `fieldset` only visible to screen readers
- Adds default styling for `fieldset` and `legend` instead of applying design system utility classes -- this means that when we …
> Patch for #1397

- api/package.json
- web/package.json
Deploy fails because the postinstall step can't find `../docker-compose.yml`.  This hotfix doesn't change that, but instead of failing, it just...  `true`s.
- deploys will work
> Postinstall hotfix

- web/src/i18n/locales/en/apd/stateProfile.yaml
- web/src/i18n/locales/en/executiveSummary.yaml
- web/src/i18n/locales/en/previousActivities.yaml
- web/src/i18n/locales/en/proposedBudget.yaml
* shortens some titles, which should be reflected in the nav
* add an `Export` section. Until that experience is settled, there’s not much point in creating a yaml for the content.
* rename the profile info yaml file to more closely reflect the new title. Probably fine, but at some point it might be worth auditing the yaml itself for this, too
> shorter nav headers

- web/src/components/ConsentBanner.js
- web/src/components/ConsentBanner.test.js
- web/src/components/__snapshots__/ConsentBanner.test.js.snap
- web/src/containers/Login.js
- web/src/containers/Login.test.js
- web/src/containers/__snapshots__/Login.test.js.snap
- adds a government IS consent banner before allowing access to the web app
- Once a user logs in, we store a cookie in their browser that's valid for 3 days and won't show them the consent banner again as long as the cookie is valid.  The cookie expiration is extended when the user logs in again, but not every time they visit the app.
- closes #1424
> Login consent screen

- web/src/containers/activity/EntryDetails.js
- web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap
The helper function that builds up activity names for display expects a whole activity object, but we were only sending it the activity name so it failed and just returned the default name.
- passes the whole activity object so activity names for display are built correctly
- Fixes #1410
> Fix activity names in list headers

- web/src/components/Header.js
Since Github comments don't support multi-line suggestions, I'll do this one as a PR.  It modifies the header so that it only adds a global document event handler when the dropdown is expanded.
> Suggestion: minor performance tweak [skip deploy]

- web/src/components/Header.js
The current `ref` implementation was deprecated for :waves_hands: reasons.  This suggestion updates to the current recommended pattern, which is different because :waves_hands: reasons.
> Suggestion: new ref pattern [skip deploy]

- docker-compose.yml
- web/.snyk
- web/package-lock.json
- web/package.json
I forked the [react-draft-wysiwyg repo](https://github.com/jpuri/react-draft-wysiwyg) repo and made changes to how it handles click events:
https://github.com/18F/react-draft-wysiwyg/commit/2d89041dc5503bd02f73f1b438949175c552a044
In summary:
- components set their own state on click instead of waiting for a global click event to propagate back to them
- components only subscribe to global click events when necessary, and unsubscribe as soon as possible
- all rich text editor instances share a single global click event instead of each having their own
In dev, this resulted in about a 12x speedup for certain actions.
- switches to 18F build of rich text editor
- closes #1466
> Switch to 18F build of rich text editor

- web/src/components/Dollars.js
- web/src/components/Dollars.test.js
- web/src/components/__snapshots__/Dollars.test.js.snap
- web/src/containers/ExecutiveSummary.js
- web/src/containers/ExecutiveSummary.test.js
- web/src/containers/__snapshots__/ApdPreviousActivityTable.test.js.snap
- web/src/containers/__snapshots__/ApdPreviousActivityTableMMIS.test.js.snap
- web/src/containers/__snapshots__/ApdPreviousActivityTableTotal.test.js.snap
- web/src/containers/__snapshots__/BudgetSummary.test.js.snap
- web/src/containers/__snapshots__/ExecutiveSummary.test.js.snap
- web/src/containers/__snapshots__/ExecutiveSummaryBudget.test.js.snap
- web/src/containers/__snapshots__/IncentivePayments.test.js.snap
- web/src/containers/__snapshots__/QuarterlyBudgetSummary.test.js.snap
- web/src/containers/activity/__snapshots__/CostAllocateFFP.test.js.snap
- web/src/reducers/budget.selectors.js
- web/src/styles/scss/overrides.scss
This PR does not update the executive summary budget table, only the activity summary view, as designed in #1491.
- closes #1491
> Update section 8 (executive summary), activity summary with design system

- bin/preview-deploy/aws.cleanup.sh
- bin/prod-deploy/aws.sh
- bin/prod-deploy/aws.user-data.sh
The database migration wasn't happening. This moves the migration step into PM2 to make sure the environment is setup correctly, instead of having a separate command and environment injection and all that.  (I suspect there was a problem with escaping, and this should fix that.)
- database migrates correctly
- configures AWS region for the cleanup script
> Move AWS DB migration step into PM2

- api/audit.js
- api/env.js
- api/logger.js
- api/main.js
- api/routes/me/put.js
- api/routes/users/delete.js
- api/routes/users/post.js
- api/routes/users/post.test.js
- api/routes/users/put.js
- bin/prod-deploy/aws.sh
- web/.snyk
#1507 says we need to audit account creation, modification, enabling, disabling, and deleting.  This PR should satisfy that requirement.  We don't have a distinct method for enabling or disabling accounts, but we can effectively disable account by removing its authorization role and re-enable it by adding a role back to it.  That would be captured by the account modification audit.  There is no auditing for account enable/disable since that't not an explicit action.
- adds an auditor helper
- updates account creation, update, and delete API routes to use auditing
- updates logger to add `audit` log level that cannot be disabled
- closes #1507
- probably need to put a note about this in the controls spreadsheet?
> Audit account management actions

- web/src/components/CollapsibleList.js
- Switch `CollapsibleList` toggly things from `<header>` to `<div>` as a quick fix. The whole `CollapsibleList` component will hopefully go away relatively soon.
- fixes #1515
> Fix legacy collapsible list headers

- api/auth/session.js
- api/auth/session.test.js
- api/main.js
- api/routes/apds/get.js
- api/routes/auth/activities/index.js
- api/routes/auth/activities/index.test.js
- api/routes/auth/roles/get.js
- api/routes/auth/roles/get.test.js
- api/routes/users/get.js
- api/routes/users/get.test.js
- explicitly overwrites cookies; this shouldn't affect anything but let's just be safe
- tightens up logging so there's less trash in the console, should make reading the `silly` logs a lot easier
- adds a `/heartbeat` endpoint that does nothing, terminates immediately, and precedes all other endpoint processing (so it doesn't log anything or trigger authentication processing); perfect for a health check, which AWS triggers every 30 seconds and is seriously polluting the logs 😜
> Some API cleanup

- .circleci/config.yml
- bin/prod-deploy/aws.sh
Currently, the production deployment will only successfully cleanup instances that have completed their deployments (i.e., they've been created and added to the load balancer).  However, in the case that a deployment begins while a previous deployment is still ongoing, the latter deployment may fail to clean up the former and we could end up with two active deployments.  This could cause unpredictable behavior if the API changed, as different versions of the API are responding to requests.
- cleans up all previously-existing production instances when the new instance is ready, regardless of their status
> Update production deploy cleanup

- .circleci/config.yml
Frontend production deployment is broken. The script does a `git` status check to verify that the frontend has changed before deploying it, but it doesn't actually checkout the code first (the deployment step previously only relied on the built frontend which is cached earlier in the CI process, so deployment didn't need the source code).
- checks out the code on frontend deployments so the git status check will work
> HOTFIX - Frontend production deployment

- api/seeds/development/apds.js
- web/src/actions/activities.js
- web/src/actions/activities.test.js
- web/src/components/Section.js
- web/src/containers/activity/Goals.js
- web/src/containers/activity/Goals.test.js
- web/src/containers/activity/__snapshots__/Goals.test.js.snap
- web/src/i18n/locales/en/activities/goals.yaml
- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
- web/src/styles/index.scss
- web/src/util/serialization/activities.js
- web/src/util/serialization/activities.test.js
- updates activity goals section
- goals can be removed as long as there is more than one in the list
- users are prompted for confirmation before goals are deleted
- new goals are expanded by default
- updates dev seed to remove HTML formatting from goal name and benchmark text
- closes #1453
> update activity goals section

- api/routes/openAPI/__snapshots__/get.endpoint.js.snap
- api/routes/users/openAPI.js
- bin/cascade-delete-apd.js
- web/src/containers/BudgetSummary.js
- web/src/containers/__snapshots__/BudgetSummary.test.js.snap
- web/src/containers/__snapshots__/ExecutiveSummaryBudget.test.js.snap
- web/src/i18n/locales/en/activities/costAllocate.yaml
- web/src/i18n/locales/en/apd/apd.yaml
- web/src/i18n/locales/en/apd/stateProfile.yaml
- web/src/i18n/locales/en/certifyAndSubmit.yaml
- web/src/i18n/locales/en/executiveSummary.yaml
Closes #1599
Might close #1177, depends on someone’s interpretation, I’ll leave that to the rest of the team.
- This addresses a number of minor typos and stylistic errors I noticed while I was updating the content style guide per #1180.
- This also adds information about Key Personnel being 90-10 HIT expenses for #1177.
This is ready to merge when nothing breaks and product says the content is clearer than it was before on key personnel. It can certainly use additional work but I want it to be more clear rather than less.
> lots of little adjustments to copy

- .circleci/config.yml
Before deploying, we check to see what changed and only deploy the components that need it. E.g., if nothing in the `/api` directory changed, we don't deploy the backend. The problem is that it did a `git diff` against master...  from the master branch. Surprising no one, it always said there were no diffs.
🤦‍♂
This changes it to `git diff HEAD~1` which will compare against the previous commit. This step only ever runs on the master branch, so each commit is a merge commit, and `HEAD~1` will point to the state of the code before the most recent merge.
- took out some dumb, replaced with some common sense
> Fix pre-deployment "did it change" check

- .circleci/config.yml
CircleCI immediately fails a build if any command during any step exits with a nonzero code. Our build relies on the output of `git diff --exit-code` to determine which parts of the app have changed in order to know which parts to deploy.  A nonzero exit code indicates that a path has changed and should be deployed, but CircleCI was immediately failing the build.
- runs `set +e` before the `git diff`, indicating to continue running in spite of nonzero exit codes
- run `set -e` after the `git diff` to restore CircleCI's normal behavior
> Deploy error fix

- web/src/containers/Sidebar.js
I don't understand why, but moving the sticky to the `<aside>` instead of the `<div>` inside the `aside` made it work again.
- made the sidebar's `<aside>` element sticky instead of the `<div>` inside of the `aside`
- flabbergasted about how CSS works
- closes #1560
> Re-re-stick sidebar

- web/src/containers/BudgetSummary.js
- web/src/containers/BudgetSummary.test.js
- web/src/containers/__snapshots__/BudgetSummary.test.js.snap
The table header described in #1607 is the total across FFYs in the "Summary Budget Table" in the "Proposed Budget" section.  The header was being computed based on the year, but for the total across FFYs, the year field is `total`.  Thus, the header was displaying as `FFY total`.
The fix is to make the header text conditional so that if the year field is `total`, it will display something else.  Because `FFY Total` doesn't really make sense (it isn't a total of a single FFY and there is no FFY called "total"), I changed it to just `Total`.
Since @quarterback is back (:tada:), I'd love feedback on the decision to change `FFY total` to just `total`.  It makes sense to *me*, but who am I but a lowly, humble dev? 😄
- closes #1607
> fix summary budget table 'total' header

- web/src/styles/scss/print.scss
Review components look like they have double lines because those lines are supposed to be around a button. That we're hiding in print. Fix it.
> Get rid of double lines

- web/src/styles/scss/print.scss
Don't break inside fieldsets.
Legends should be 100% width.
> Tweaks for legends and fieldsets in print

- api/db/activity/activity.js
- api/db/activity/activity.test.js
- api/db/activity/contractorResource.js
- api/db/activity/contractorResource.test.js
- api/db/activity/quarterlyFFP.js
- api/db/activity/quarterlyFFP.test.js
- api/db/activity/statePersonnel.js
- api/db/activity/statePersonnel.test.js
Until the frontend can properly report on save failures, the backend should be very liberal about what it accepts. This PR removes some validations to make the API more accepting.
- removes validation that enforces that activity names are at least one character and are unique within the APD
- removes validation that enforces that activity contractor resource years are after 2010 and before 3000
- removes validation that enforces that activity state personnel FTE is not negative
- removes validation that enforces that activity state personnel years are after 2010 and before 3000
- removes validation that enforces that activity quarterly FFP is reported for at least one year
- closes #1659
This PR leaves date validation in place. The date validation just ensures that dates are valid before …
> Remove more backend data validations, to reduce save errors

- web/src/containers/activity/Schedule.js
- web/src/containers/activity/__snapshots__/Schedule.test.js.snap
Replaces date fields in activity list with this in print:
> Show dates as text instead of inputs

- web/src/styles/scss/print.scss
Remove the radio/check `:before` element, which relies on a white SVG on a colored background. Just show the label. Looks like:
> Better print display for radios and checkboxes

- web/src/components/Dollars.js
- web/src/components/__snapshots__/Dollars.test.js.snap
- web/src/containers/ExecutiveSummary.test.js
- web/src/containers/ScheduleSummary.js
- web/src/containers/ScheduleSummary.test.js
- web/src/containers/__snapshots__/ScheduleSummary.test.js.snap
- web/src/containers/activity/ContractorResource/ContractorResourceReview.js
- web/src/containers/activity/ContractorResource/ContractorResourceReview.test.js
- web/src/containers/activity/ContractorResource/__snapshots__/ContractorResourceReview.test.js.snap
- web/src/containers/activity/Milestone/MilestoneReview.js
- web/src/containers/activity/Milestone/__snapshots__/MilestoneReview.test.js.snap
- web/src/containers/activity/Schedule.js
- web/src/containers/activity/__snapshots__/Schedule.test.js.snap
- web/src/reducers/activities.selectors.js
- web/src/reducers/budget.selectors.js
- web/src/util/index.js
- web/src/util/index.test.js
- empty/invalid dollar values are displayed as `$0` instead of `--`
- empty/invalid single dates are displayed as `Date not specified`
- empty/invalid date ranges are displayed as `Dates not specified`
- several components updated to use util date methods, so we can make sure everything is consistent
- closes #1658
> Handle empty/invalid dollar and date values

- web/src/actions/apd.js
- web/src/actions/apd.test.js
- prompt the user with a confirmation dialog before deleting APD key personnel
- closes #1647
- skipping design and product review because the behavior is the same as other delete confirmations
> Prompt before deleing APD key personnel

- web/src/components/ConsentBanner.js
- web/src/components/ConsentBanner.test.js
- web/src/components/__snapshots__/ConsentBanner.test.js.snap
Change the consent banner so that it can only be expanded, not collapsed
- when the consent banner is expanded, keeps the "Agree and Continue" button available
- removes the "Hide details" button when the banner is expanded
- removes the "Read more details" button when the banner is expanded
- tabbing to the "Read more details" button, pressing space, and tabbing again will take you to the "Agree and Continue" button as expected (I think that's expected?)
- closes #1677
> Don't collapse the consent banner

- CHANGELOG.md
- web/src/containers/activity/Overview.js
- web/src/styles/scss/forms.scss
- adds a `ds-c-label--full-width` class to design system `FormLabel` components that appear immediately before rich textboxes in the activity overview section
- sets the `max-width` to `initial` for the `ds-c-label--full-width` class
- closes #1640
> Extend labels before activity overview rich textboxes to full width

- CHANGELOG.md
- web/src/components/Header.js
- web/src/components/Header.test.js
- web/src/components/__snapshots__/Header.test.js.snap
- instead of the "logout" link being a button, make it an actual link like the "manage account" link; now they are the same!
- closes #1655
> Make logout link text the same size as the manage account link text

- CHANGELOG.md
- web/src/containers/ApdStateProfileMedicaidOffice.js
- web/src/containers/__snapshots__/ApdStateProfileMedicaidOffice.test.js.snap
- adds spacing to the headers/legends before the Medicaid director and office address forms:
- Before:
- After:
- closes #1646
> Add spacing to Medicaid director and office headers/legends

- CHANGELOG.md
- web/src/containers/StateDashboard.js
- adds 40px to the bottom of the state dashboard
- closes #1601
> Add whitespace to the bottom of the dashboard

- CHANGELOG.md
- web/src/containers/Sidebar.js
- web/src/containers/Sidebar.test.js
- web/src/containers/__snapshots__/Sidebar.test.js.snap
- for American Samoa, Guam, Northern Mariana Islands, and U.S. Virgin Islands, don't display the state/territory outline in the sidebar because we don't have those outlines (thanks for the idea @hbillings!)
- addresses #1423
- up to product whether this closes the issue and open a new one later about adding those outline images, but...
The outlines we have now are SVGs generated from TopoJSON files. The original source of the TopoJSON files is murky but [Bren used a minor modification](https://github.com/18F/cms-hitech-apd/pull/353#discussion_r177516462) of [a script by Mike Bostock](https://gist.github.com/mbostock/9821217#file-makefile) to pull data from the USGS and do some magic massaging on it to turn it into nice little blobs that fit into a 64x64 square, which works great for the …
> For the 4 territories we don't have images for, don't try to display images

- CHANGELOG.md
- web/src/containers/ApdKeyPerson/ApdKeyPersonReview.js
- web/src/containers/ApdKeyPerson/__snapshots__/ApdKeyPersonReview.test.js.snap
- instead of only showing the total, also show the cost per year (following the same format as the activity contractor costs)
- closes #1747
> Show costs by year for APD key personnel in review

- CHANGELOG.md
- web/src/components/CardForm.js
- web/src/components/Wrapper.js
- web/src/components/__snapshots__/CardForm.test.js.snap
- web/src/components/__snapshots__/Wrapper.test.js.snap
- web/src/containers/ApdApplication.js
- web/src/containers/StateDashboard.js
- web/src/containers/__snapshots__/ApdApplication.test.js.snap
- web/src/styles/scss/layout.scss
- adds a link at the top of the page, only visible when focused (e.g., if the user tabs to it), that lets the user skip the navigation and go directly to the main content
- closes #1304
> Add a link to skip navigation and go straight to the main content

- CHANGELOG.md
- web/src/components/DollarField.js
- web/src/components/NumberField.js
- web/src/components/NumberField.test.js
- web/src/components/__snapshots__/DollarField.test.js.snap
- web/src/components/__snapshots__/NumberField.test.js.snap
- web/src/containers/ApdKeyPerson/ApdKeyPersonForm.js
- web/src/containers/ApdKeyPerson/__snapshots__/ApdKeyPersonForm.test.js.snap
- web/src/containers/IncentivePayments.js
- web/src/containers/__snapshots__/IncentivePayments.test.js.snap
- web/src/containers/activity/ContractorResource/ContractorResourceForm.js
- web/src/containers/activity/ContractorResource/__snapshots__/ContractorResourceForm.test.js.snap
- web/src/containers/activity/CostAllocateFFP.js
- web/src/containers/activity/CostAllocateFFP.test.js
- web/src/containers/activity/CostAllocateFFPQuarterly.js
- web/src/containers/activity/StatePerson/StatePersonForm.js
- web/src/containers/activity/StatePerson/StatePersonForm.test.js
- web/src/containers/activity/StatePerson/__snapshots__/StatePersonForm.test.js.snap
- web/src/containers/activity/__snapshots__/CostAllocateFFP.test.js.snap
Number fields whose current value is zero will have their contents selected when the form field is focused. That way when a user clicks in that field, they can just begin typing and overwrite the zero that's already there.
- added `NumberField` component
- updated `DollarField` to be a `NumberField`
- updated APD key personnel, incentive payments, state personnel, contractor resources, and cost allocation forms to use the `NumberField` component
- updated cost allocation form to use `DollarField` component for "other funding" (see #1754); incidental - in order to fix #1736 across the app, #1754 needed to be fixed too... so I went ahead and did it
- closes #1736
- closes #1754
> Select numeric field content on focus if the current value is 0

- web/src/components/Choice.js
- web/src/components/Choice.test.js
- web/src/components/PasswordWithMeter.js
- web/src/components/PasswordWithMeter.test.js
- web/src/components/__snapshots__/Choice.test.js.snap
- web/src/components/__snapshots__/PasswordWithMeter.test.js.snap
- web/src/containers/ApdKeyPerson/ApdKeyPersonForm.js
- web/src/containers/ApdKeyPerson/ApdKeyPersonForm.test.js
- web/src/containers/ApdKeyPerson/__snapshots__/ApdKeyPersonForm.test.js.snap
- web/src/containers/ApdSummary.js
- web/src/containers/ApdSummary.test.js
- web/src/containers/AssurancesAndCompliance.js
- web/src/containers/AssurancesAndCompliance.test.js
- web/src/containers/__snapshots__/ApdSummary.test.js.snap
- web/src/containers/__snapshots__/AssurancesAndCompliance.test.js.snap
- web/src/containers/activity/ContractorResource/ContractorResourceForm.js
- web/src/containers/activity/ContractorResource/__snapshots__/ContractorResourceForm.test.js.snap
In the final ARIA announcement saga episode, we create a wrapper around the design system's Choice component that brute-force removes the `aria-live`, `aria-atomic`, and `aria-relevant` attributes.
**TODO** Open a ticket with the design system folks asking them to make the aria region optional via a component flag.
- ☝️
> Make a copy of the Choice component to remove the aria-live attribute

- CHANGELOG.md
- web/src/containers/activity/CostAllocateFFP.js
- web/src/containers/activity/CostAllocateFFPQuarterly.js
- web/src/containers/activity/CostAllocateFFPYearTotal.js
- web/src/containers/activity/CostAllocateFFPYearTotal.test.js
- web/src/containers/activity/__snapshots__/CostAllocateFFP.test.js.snap
- web/src/containers/activity/__snapshots__/CostAllocateFFPYearTotal.test.js.snap
Moves the cost allocation yearly totals table into a separate component, and out of the quarterly tables component.
- closes #1574
> Refactor activity cost allocation quarterly tables

- CHANGELOG.md
- api/auth/session.js
- api/auth/session.test.js
- Sets the cookie's `maxAge` equal to the session lifetime, which results in it getting an expiration. Verified by checking the cookie in the browser dev tools.
- closes #1756
> Set the auth session cookie to expire at the same time the session will expire

- web/src/styles/scss/editor.scss
We had rounded borders applied to some parts of the rich text editor, but those borders were based on a radius variable that was set in the legacy CSS index file. When that file went away, the variables were no longer defined, so Sass would give us a warning. Since nobody seemed to notice or mind that the borders were no longer rounded, I opted to just remove them rather than put the variable back.
- removes references to `--border-radius` variable in scss
- closes #1774
- ~Changelog is updated as appropriate~ Not necessary. This is part of removing the old styles, which is already in the changelog
> Fix Sass warnings

- CHANGELOG.md
- web/src/components/NumberField.js
- web/src/components/PercentField.js
- web/src/components/PercentField.test.js
- web/src/components/__snapshots__/DollarField.test.js.snap
- web/src/components/__snapshots__/NumberField.test.js.snap
- web/src/components/__snapshots__/PercentField.test.js.snap
- web/src/containers/ApdKeyPerson/ApdKeyPersonForm.js
- web/src/containers/ApdKeyPerson/__snapshots__/ApdKeyPersonForm.test.js.snap
- web/src/containers/__snapshots__/IncentivePayments.test.js.snap
- web/src/containers/activity/ContractorResource/__snapshots__/ContractorResourceForm.test.js.snap
- web/src/containers/activity/CostAllocateFFPQuarterly.js
- web/src/containers/activity/StatePerson/__snapshots__/StatePersonForm.test.js.snap
- web/src/styles/scss/forms.scss
Adds a `<PercentField>` component that does DOM jujitsu to insert a percent sign into number input fields. I had to use gymnastics here because we're using design system components, and they render the `<input>` deep inside some other stuff. That doesn't seem like a problem though, right? We can target that input with CSS!
Well, yes we can, but did you know that input elements don't have `:before` or `:after` pseudoelements? So you can't put a percent sign next to them that way, which is the most obvious way.
Okay, but we could target the container and put the percent sign on that! Sure, that's possible. But the container is the full content width and the input element is not. If we want the percent sign to be nestled against the right side of the input element...  well, tough luck, …
> Add Percent field, switch APD key personnel and quarterly FFP share inputs to Percent field

- CHANGELOG.md
- web/src/components/Header.js
- web/src/components/__snapshots__/Header.test.js.snap
- sets a more descriptive ARIA label for screen readers: "You are logged in as [account]. Click to manage account."
- Do we need the "click" part? The `aria-haspopup` attribute will indicate that it has a popup, but it doesn't give any clue as to what's hidden in the popup.
- sets `aria-haspopup="true"` so screen readers know the button controls a popup
- moves `aria-expanded` to the button instead of the containing UL, so the reader will announce the expand/collapse state when the button gets focus
- closes #1681
> Add ARIA attributes to the account management button to make it more accessible

- docker-compose.yml
- web/package-lock.json
- web/package.json
- web/src/containers/ApdApplication.js
- web/src/containers/Sidebar.js
- web/src/containers/__snapshots__/ApdApplication.test.js.snap
- web/src/containers/__snapshots__/Sidebar.test.js.snap
- web/src/styles/scss/layout.scss
A whole bunch of our sidebar woes are due to us trying to use the built-in design system columns, which are flexbox-based, for that page. Flexbox and `position: sticky` work okay together, but flexbox and `position: fixed` do not. Since we don't really need or want the sidebar to flex in size and we need to support older browsers, let's just use the oldschool way of doing this: set a fixed width on the sidebar, set it to `position: fixed` in all browsers, and set a margin of the sidebar width + padding on the main content.
The one downside of this is that the sidebar is fixed slightly low on the screen, to account for the navbar in the initial position. This seems like a better tradeoff than the current sizing issue, though, and is something we can Javascript our way out of.
- Removes …
> Patch for inconsistent sidebar

- CHANGELOG.md
- web/src/containers/ApdApplication.js
- web/src/containers/ApdApplication.test.js
- web/src/reducers/apd.js
- updates the APD title to show the year range instead of just the first year
- closes #1820
> Show year range at APD title

- docker-compose.yml
- web/package-lock.json
- web/package.json
- web/src/actions/editApd.js
- web/src/actions/editApd.test.js
- web/src/containers/ApdStateProfileMedicaidOffice.js
- web/src/containers/ApdStateProfileMedicaidOffice.test.js
- web/src/containers/__snapshots__/ApdStateProfileMedicaidOffice.test.js.snap
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
- web/src/reducers/index.js
- web/src/reducers/index.test.js
- web/src/reducers/patch.js
- web/src/reducers/patch.test.js
To prepare for the glorious future in which saves are done via JSON patches, this PR does the work of capturing user edits as a JSON patchset.
My first thought was to just make a new `patch` reducer that captures all the existing edit actions. Good news! The edit actions are sending along nested objects which we'd need to extract the keys from in order to build a property path. E.g.:
```js
{
stateProfile: {
medicaidDirector: {
name: "Bob"
}
}
}
```
...would get converted into this path:
```js
"stateProfile/medicaidDirector/name"
```
And it turns out, that's actually kinda tricky, mainly around knowing when to stop traversing the object for keys. For example, what if the value itself is an object? How do you know you've reached the actual value?
So... I decided our current actions are kind …
> Compute JSON patchset of APD edits in the state Medicaid director and office section

- web/src/actions/editApd.js
- web/src/actions/editApd.test.js
- web/src/containers/ApdStateKeyPersonnel.test.js
- web/src/reducers/apd.js
- web/src/reducers/apd.test.js
- web/src/reducers/patch.js
- web/src/reducers/patch.test.js
#1860 switched over the APD key personnel section to patches, but completely forgot to actually compute the patches for the `patch` reducer, meaning that adding/removing key personnel would never have been saved. 😬
- fixes ☝️ that
> JSON patch bug

- CHANGELOG.md
Adds the latest release info to the changelog and prepares it for the next release.
A question: should we keep the complete change history in the changelog, or would we rather only track changes for *upcoming* releases in the changelog? Once we do a release, we'll have the change history on the [releases page](https://github.com/18F/cms-hitech-apd/releases), so having the complete history in the changelog seems redundant. 🤷‍♂
> Prepare changelog for next release

- web/src/containers/activity/ActivityContext.js
- web/src/containers/activity/ContractorResource/ContractorResourceForm.js
- web/src/containers/activity/ContractorResource/ContractorResourceForm.test.js
- web/src/containers/activity/ContractorResources.js
- web/src/containers/activity/EntryDetails.js
- web/src/containers/activity/Goal/GoalForm.js
- web/src/containers/activity/Goal/GoalForm.test.js
- web/src/containers/activity/Goals.js
- web/src/containers/activity/Milestone/MilestoneForm.js
- web/src/containers/activity/Milestone/MilestoneForm.test.js
- web/src/containers/activity/Milestone/__snapshots__/MilestoneForm.test.js.snap
- web/src/containers/activity/Schedule.js
- web/src/containers/activity/__snapshots__/ContractorResources.test.js.snap
- web/src/containers/activity/__snapshots__/EntryDetails.test.js.snap
- web/src/containers/activity/__snapshots__/Goals.test.js.snap
- web/src/containers/activity/__snapshots__/Schedule.test.js.snap
I added a React context provider to the `EntryDetails` component to give descendant components access to the activity index, but it's a little confusing to use and we don't really need it. Every component along the way needs the activity index anyway, so we're never passing it just to pass it.
- remove `useContext` from everywhere
- removes activity index context
- removes context provider wrapper
> Remove React context

- api/migrations/20190729185138_document-model.js
The document model migration makes use of Bookshelf to pull relational APDs as single objects (rather than writing complex queries in SQL to do it manually) and then writes those objects into the new `document` column for APDs. This is basically the conversion step from relational model to document model.
However, Bookshelf creates an instance of knex _in addition to_ the instance of knex being used to run the migrations. knex instances don't close until the process exits, and the open connection actually causes a process to stay alive - so a process must be manually killed in order to disconnect knex. This isn't necessarily a problem.  If you are running ***ONLY*** the document model migration (or if it is the last one in a list of migrations), it works fine - when the migration is …
> Fix document model migration

- api/migrations/20191004161449_harmonize-models.js
- api/routes/apds/__snapshots__/post.endpoint.js.snap
- api/routes/apds/post.data.js
- api/routes/apds/post.data.test.js
- api/routes/apds/post.js
- api/routes/apds/post.test.js
- api/routes/openAPI/__snapshots__/get.endpoint.js.snap
- api/routes/openAPI/index.js
- api/schemas/apd.json
- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
- fixes an interim migration to change `apd.activities[].contractorResources[].desc` to `apd.activities[].contractorResources[].description` (this was changed elsewhere already, but it got missed in the data migrations)
- updates the `POST /apds` endpoint to no longer use the relational model to build APDs and instead now goes directly to the document model
- closes #1800
> Update API POST endpoint to only create document model APD

- api/docker-compose.endpoint-tests.yml
- api/package-lock.json
- api/package.json
- docker-compose.yml
- web/package-lock.json
- web/package.json
I thought we had prettier configuration in the app, but it turns out _nope_ - I had a little bit of configuration in my VS Code settings, which is a bad place for them, and we were otherwise relying on defaults. This PR moves the config into the project space.
Alternatively, we can leave this configuration out and revert to double quotes over time. I have no strong feelings. My vote is for single quotes, but @hbillings if you feel strongly, feel free to merge or close this PR accordingly.
- adds prettier config to prefer use single quotes
> Add prettier config

- CHANGELOG.md
- web/package-lock.json
- web/package.json
- web/src/containers/Sidebar.js
- web/src/styles/scss/layout.scss
Closes #1948 and essentially reverts #1830. Since we've decided IE11 is a yellow support browser, we can ignore the jumpiness of the sidebar in favor of making the experience great for green support browsers.
- re-adds stickybits
> Re-add stickybits to sidebar

- api/auth/session.js
- api/auth/session.test.js
- api/package-lock.json
- api/package.json
- api/routes/auth/logout.endpoint.js
We won't be 100% sure this works until we push it out to staging... 😬
- explicitly sets the auth cookie domain to `.cms.gov` in production environments so that it can be sent from `eapd.cms.gov` to `eapd-api.cms.gov` with a strict `SameSite`
- set the cookie `SameSite` to `strict` in every case
- set the cookie to secure in production environments; don't worry about it otherwise
- closes #1955
- ~Associated OpenAPI documentation has been updated~ N/A
> Update domain, samesite, and secure properties on auth cookies

- .circleci/config.yml
When a frontend or backend deployment to staging or production fails, send a message to Slack so we'll know about it. Relies on the `SLACK_WEBHOOK_URL` environment variable in CircleCI, which is currently set to a channel in the 18F/TTS Slack.
Note for CMS of the future: once you've got a webhook URL for a channel in your Slack, you can update the CircleCI environment variable and then you'll be done!
Note for 18F of the future: we can disable the webhook in Slack settings, so if the CircleCI environment variable doesn't get updated, it's okay, we don't have to worry about notifications going into an empty channel and being missed.
- makes it so we know when deploys are failing
> Send Slack notice when deploy fails

- api/auth/session.js
- api/auth/session.test.js
Instead of explicitly setting the cookie domain, let the browser infer it. Another staging fix...
- does not set the cookie domain
> Remove domain from cookie

- CHANGELOG.md
- api/db/users.js
- api/db/users.test.js
- api/routes/users/__snapshots__/put.endpoint.js.snap
- api/routes/users/put.endpoint.js
- api/routes/users/put.js
- api/routes/users/put.test.js
- web/src/containers/admin/EditAccount.js
Our user validation function optionally accepts a user ID. When it checks it the email address being validated already exists in the database, it will also check the passed-in user ID. That way, if the user being edited has the same email address, it won't fail.
The user update endpoint was not sending the user ID into the validator, so the validation always failed. Furthermore, the database user update function calls the validator and also was not passing along the user ID. Both instances have been fixed.
Also fixed a bug where the admin had to change the user's state, too. This is because the user object in the application store has a full object for `state` rather than just a two-letter ID. The EditAccount component set the user's state to the value from the application store when a …
> Fix a bug that prevents admins from changing a user's account without also changing the user's email address

- .circleci/config.yml
- dependency vulnerability scans run daily at midnight UTC
- closes #1974 (hopefully; won't know for certain until after the midnight after it's merged)
> Add nightly dependency vulnerability scanning

- CHANGELOG.md
- web/.eslintrc.json
- web/package-lock.json
- web/package.json
- web/src/components/ConsentBanner.js
- web/src/components/ConsentBanner.test.js
- web/src/components/PasswordWithMeter.js
- web/src/components/UpgradeBrowser.js
- web/src/containers/Login.js
- web/src/containers/SaveButton.js
- web/src/containers/activity/CostAllocateFFP.js
- web/src/containers/admin/CreateAccount.js
- web/src/containers/admin/EditAccount.js
- web/src/containers/admin/MyAccount.js
- web/src/containers/admin/MyAccount.test.js
- web/src/containers/viewOnly/ApdSummary.js
- web/src/containers/viewOnly/PreviousActivities.js
- web/src/containers/viewOnly/activities/Activity.js
- web/src/stories/FrozenTableStory.js
- web/src/stories/content/Instruction.js
Updates to the most recent version of the airbnb eslint rules, and tweaks the code accordingly
- The rules now require that component state initialization happen in a constructor. Added constructors where necessary, and converted to functional components where possible
- The Airbnb rules require using `<>` instead of `<Fragment>`. Inverted the rule so that we require `<Fragment>` instead of `<>`
- The rules forbid using prop spreads in components like `<Component ...props>`. However, we use that pattern a lot for wrapper components so we can just blindly pass properties along. Disabled this rule.
- Added local disables for the `no-dangerous` rule that warns about using `dangerouslySetInnerHTML` since we aware of those and they're intentional. We'll still get warnings about new ones, which …
> Update to latest airbnb eslint rules

- CHANGELOG.md
- web/package-lock.json
- web/package.json
- web/src/css-loader.test.js
- web/webpack.config.js
The [`css-loader`](https://npm.im/css-loader) module changed in 3.3.0 and it now doesn't handle some of our font imports correctly. As a result, it was loading the wrong font files for various font definitions. This mostly manifested as the Open Sans Italic font file being loaded for the open-sans regular definition, so the whole site was in italics.
Opened [1039](https://github.com/webpack-contrib/css-loader/issues/1039) on the css-loader repo to track the issue. When that's resolved, we can update again.
- reverts `css-loader` to 3.2.1
- closes #1998
> Make it so all the words aren't crooked

- .circleci/config.yml
- web/audit-resolve.json
The `npm audit` command fails if there are *any* security vulnerabilities, even low-level ones, and does not provide a way to temporarily ignore a vulnerability. Since many of the vulnerabilities that pop up in our dependencies are in our development dependencies (and thus not a production concern), this becomes problematic. If a dev dependency has a low-severity vulnerability, we just can't merge a PR until it is fixed upstream, even though we really aren't concerned about it.
This PR switches from using `npm audit` directly to using `npm-audit-resolver`, which introduces the ability to ignore vulnerabilities for a period of time (similar to what Snyk allowed). That way when there are vulnerabilities without fixes or vulnerabilities that we don't care about and would require a lot of …
> Tweak how we scan dependencies

- web/src/components/PasswordWithMeter.js
- web/src/components/__snapshots__/PasswordWithMeter.test.js.snap
- web/src/containers/Login.js
- web/src/containers/__snapshots__/Login.test.js.snap
- web/src/containers/admin/__snapshots__/MyAccount.test.js.snap
On any form with a password, toggling the "show password" checkbox would replace anything the user had entered into the password field with the literal text "Show password". This PR fixes that.
- toggling the "show password" checkbox doesn't affect the contents of the password text box
- closes #2023
> Fix a bug where toggling the "show password" checkbox would change the user's entered password to "show password"

- CHANGELOG.md
- web/src/containers/activity/EntryDetailsDialog.js
- web/src/containers/activity/Milestones.js
- web/src/containers/activity/Milestones.test.js
- web/src/containers/activity/Schedule.js
- web/src/containers/activity/Schedule.test.js
- web/src/containers/activity/__snapshots__/EntryDetailsDialog.test.js.snap
- web/src/containers/activity/__snapshots__/Milestones.test.js.snap
- web/src/containers/activity/__snapshots__/Schedule.test.js.snap
- web/src/i18n/locales/en/activities/index.js
- web/src/i18n/locales/en/activities/milestones.yaml
- web/src/i18n/locales/en/activities/schedule.yaml
This only splits these two items into separate components. It does not rearrange them in the modal or in the tabs.
- makes the activity schedule and milestones components separate
- closes #2005
- ~Associated OpenAPI documentation has been updated~ N/A
> Split activity schedule from milestones

- web/src/components/RichText.js
All of the rich text editors are given the same ID, which results in only the first one ever loading. If the ID is not provided, our wrapper creates a random one, but React `defaultProps` are only evaluated once so you can't use those for dynamic/random properties per instance. Instead, move that logic into our wrapper's constructor to ensure each instance gets a unique ID.
- fixes RTE DOM IDs so all the editors can load
> Fix a bug where the rich text editor does not load correctly in the modal

- web/src/reducers/budget.js
The full redux state has circular references and cannot be cloned. When attempting to clone it, there is an exception in the budget reducer, causing the page to fail to load.
- only clone the part of the state we actually use instead of everything
- fixes #2055
- N/A - bug was introduced in this sprint ~Changelog is updated as appropriate~
> For budget calculations, only clone the necessary part of the state

- web/src/containers/activity/CostAllocateFFP.js
- web/src/containers/activity/CostAllocateFFPYearTotal.js
- web/src/containers/activity/__snapshots__/CostAllocateFFPYearTotal.test.js.snap
- The text "Medicaid share" was missing in the print view for the cost allocation/FFP section. This puts it back.
- N/A - Given the simplicity of the fix, willing to forego code review on this one ~This code has been reviewed by someone other than the original author~
- N/A - Bug was introduced before production ~Changelog is updated as appropriate~
> Fix a bug where text was missing in viewonly/print mode

- CHANGELOG.md
- web/src/i18n/locales/en/activities/costAllocate.yaml
- fixes the typo
- closes #2036
> Update the cost allocation instructions

- api/auth/session.js
- api/auth/session.test.js
- api/docker-compose.endpoint-tests.yml
- bin/preview-deploy/aws.user-data.sh
- docker-compose.yml
Chrome pushed some changes recently that breaks our auth cookies in dev/preview environments. Opened #2100 to capture the need to eventually move away from cookies altogether.
- disables the `samesite` and `secure` flags in dev/preview environments
- In the preview environment, SSL is terminated at an nginx proxy; from the proxy to the API is over plain HTTP, so we need to disable the `secure` flag.
- updates Docker configuration to set appropriate environment variables
> Auth cookie fix

- web/src/components/ConsentBanner.js
- web/src/components/Header.js
- web/src/components/Header.test.js
- web/src/components/Icons.js
- web/src/components/__snapshots__/ConsentBanner.test.js.snap
- web/src/components/__snapshots__/Header.test.js.snap
- web/src/containers/Login.js
- web/src/containers/Sidebar.js
- web/src/containers/StateDashboard.js
- web/src/containers/__snapshots__/Login.test.js.snap
- web/src/reducers/index.js
- web/src/reducers/index.test.js
- web/src/reducers/saving.js
- web/src/reducers/saving.test.js
- web/src/styles/scss/footer.scss
- web/src/styles/scss/header.scss
- web/src/styles/scss/layout.scss
Changes the header so that it stays at the top of the page at all times, and updates the sidebar so that it is sticky to both the top and bottom instead of only the top. Displays autosave status in the header.
- closes #2087
- closes #2090 
- N/A N/A ~Associated OpenAPI documentation has been updated~
> Give the header and sidebar fixed positions

- web/package-lock.json
- web/package.json
- web/webpack.config.js
We used two different Webpack plugins to inject CSS tags into our HTML. One of these added a content hash query parameter to bust the cache, but the other did not. Unfortunately, because of the ordering, the non-hashed one would load first and override the hashed one. This PR removes the plugin that added the hashed version and instead configures the other to also add a hash, as it probably should have been in the first place.
- fixes CSS cache-busting
- closes #2118 
- n/a ~Tests have been updated (and all tests are passing)~
- n/a ~Changelog is updated as appropriate~
> Fix css cache busting

- web/src/styles/scss/layout.scss
There was a bunch of extra whitespace at the top of the page. This gets rid of that.
- content top margin was applied twice, now just once
- closes #2119
- n/a ~Tests have been updated (and all tests are passing)~
- n/a ~This code has been reviewed by someone other than the original author~
- n/a/ ~Changelog is updated as appropriate~
> Remove extraneous whitespace from the top of the APD page

- bin/prod-deploy/aws.sh
We dynamically pick the AWS machine image (AMI) that we use as the basis for our deployments. We do that so that we can stay up to date with the most recent gold image published by CMS (previously we were tied to a specific AMI ID, but AMIs are retired after 4 months, so we regularly had to manually go update the build).
The problem is that the filter I wrote to pick the image wasn't specific enough. It asked for the most recent image that began with the text `EAST-RH`. CMS publishes two RedHat gold images: 6.x and 7.x Furthermore, it publishes PV and HVM variations (this refers to the level of virtualization) of each one. We've been plain old lucky up to this point: the 7.x HVM image was always published last, a few seconds to a minute after the others, so that was the one we always got. …
> Change the AMI query

- CHANGELOG.md
- api/routes/apds/__snapshots__/post.endpoint.js.snap
- api/routes/apds/post.data.js
- api/routes/apds/post.data.test.js
- api/routes/apds/post.test.js
- api/schemas/apd.json
- web/src/reducers/activities.js
- web/src/reducers/activities.test.js
- web/src/reducers/apd.test.js
When creating a new activity, we will no longer create default state personnel, non-personnel, or contractor resource expenses with it. Same story with new APDs.
Also fixes a bug introduced in #2080 where APDs could not save after a new activity was created because the API required all activities to have a program type/funding source but new activities did not. A related bug (to be fixed in #2128) prevented any furthers saves after an initial error, so the practical upshot was that it became impossible to save an APD if you added an activity to it. Fixed in this PR because a) it was hampering my testing and b) it was super duper easy.
- new APDs and activities do not have default costs
- adding an activity doesn't break the APD for all eternity
- closes #2129
- n/a ~The experience passes …
> Remove default costs from new activities and APDs

- CHANGELOG.md
- web/src/i18n/locales/en/activities/costAllocate.yaml
- adds detail and help text to the quarterly FFP table
- closes #2110
> Add quarterly FFP table help text

- bin/preview-deploy/aws.user-data.sh
- docker-compose.yml
The session secret key is used to encrypt the authorization token. For the dev and preview environments, the key has been hard-coded into the docker-compose and build configuration scripts (respectively). From a security standpoint, this is fine because it can't be used to reveal any real data or access any real systems. However, GSA's bug bounty partner found these secret keys and raised them as a possible security concern (as they should, since they don't have the above context). To prevent them from raising the issue repeatedly, we can remove the secret key - our app will automatically generate random ones if none is provided, which should be fine for dev and preview.
- restarting the API in dev environments will now require logging in again because the existing session token can not …
> Remove session secret keys from dev/preview environments

- bin/prod-deploy/aws.user-data.sh
CircleCI will be changing how it handles build artifacts soon. We rely on build artifacts for staging and production deployments and will be impacted by this change. 
Adds the "-L" flag to the curl statement pulling artifacts from CircleCI
> Added flag to support redircts for CircleCI artifacts

- bin/prod-deploy/aws.user-data.sh
It appears the `-L` flag must come immediately before the URL that you're fetching, else it throws an error. That would prevent the backend code from being fetched and started up in staging/production.
- moves the `-L` flag to right before the URL
- n/a ~Tests have been updated (and all tests are passing)~
- n/a/ ~The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented~
- n/a ~Changelog is updated as appropriate~
> Hotfix curl

- CHANGELOG.md
- web/src/styles/scss/layout.scss
added min-height to css for main content div because short pages cause menu to push up under the header
- css update for main content div
- closes #2187 
> Left side navigation should not get stuck under the header

- CHANGELOG.md
- web/audit-resolve.json
- web/package-lock.json
- web/package.json
- web/src/util/browser.js
- web/src/util/browser.test.js
Set Minimum Green Browser Support for Chrome to Version 78
- sets minimum green browser support for Chrome to version 78 (was 80)
- closes #2216 
> updated chrome green version (also added dependency vulnerability fix)

- CHANGELOG.md
- web/src/contexts/LinksContextProvider.test.js
- web/src/contexts/__snapshots__/LinksContextProvider.test.js.snap
The links context provider tests currently misses the code path for returning the list of links when an activity (top level) or the activity list is selected
- added a test case for when an top level activity is selected
- added a test case for when the activity list is selected
- closes #2179 
> [Tech debt] Add one more test case for the links context provider

- CHANGELOG.md
- web/src/reducers/budget.js
- web/src/reducers/budget.test.js
- captures how much of the activity's other funding is attributed to each cost category
- closes #2169
> Captures activity other funding as attributable to each cost category

- CHANGELOG.md
- api/db/auth.js
- api/db/auth.test.js
- api/db/users.js
- api/db/users.test.js
- api/migrations/20200601145842_add-auth-roles-active-col.js
- api/routes/auth/roles/__snapshots__/get.endpoint.js.snap
- api/routes/auth/roles/__snapshots__/post.endpoint.js.snap
- api/routes/auth/roles/__snapshots__/put.endpoint.js.snap
- api/routes/auth/roles/get.js
- api/routes/auth/roles/get.test.js
- api/routes/auth/roles/post.endpoint.js
- api/routes/auth/roles/post.js
- api/routes/auth/roles/post.test.js
- api/routes/auth/roles/put.endpoint.js
- api/routes/auth/roles/put.js
- api/routes/auth/roles/put.test.js
- api/routes/users/put.endpoint.js
- api/routes/users/validate.js
- api/seeds/shared/roles-and-activities.js
- api/seeds/test/roles.js
The approach we decided on to avoid the condition is to hide the roles which don't have create permission.  Rather than removing the roles from the database and having to remember what they were when we want to add them back, we added an active column to the roles table.
- an isActive column was added to the roles table
- only active roles (admin, state coordinator) are displayed when adding or updating a user
- closes #2198 
~~- [ ] Design has approved the experience~~
> Hide Create New APD button for users who don't have create permission

- bin/preview-deploy/aws.cleanup.sh
Fixes an issue where the recurring hourly "cleanup" CI/CD task would attempt to delete an AWS EC2 instance with ID `""` if there were no preview deployments available. This causes the script to fail and results in an unhelpful message being posted to Slack.
- fixes ☝️ that
- n/a ~Tests have been updated (and all tests are passing)~
- n/a ~Changelog is updated as appropriate~
> Don't try to delete preview deployments that don't exist

- CHANGELOG.md
- web/src/constants.js
- web/src/containers/ApdPreviousActivityTable.js
- web/src/containers/ApdPreviousActivityTableMMIS.js
- web/src/containers/ApdPreviousActivityTableTotal.js
- web/src/containers/__snapshots__/ApdPreviousActivityTable.test.js.snap
- web/src/containers/__snapshots__/ApdPreviousActivityTableMMIS.test.js.snap
- web/src/containers/__snapshots__/ApdPreviousActivityTableTotal.test.js.snap
- web/src/containers/viewOnly/PreviousActivities.js
- web/src/contexts/__snapshots__/LinksContextProvider.test.js.snap
- web/src/i18n/locales/en/previousActivities.yaml
change page according to before/after screenshots in #2291.  Closes #2291
- Change from "costs" to expenditures, add expenditures to Actual on table
- Aligned headers in table
- Header of tables changed to "Actual Expenditures"
> Update Actual Costs page to use "Actual Expenditures"

- CHANGELOG.md
- web/src/containers/ExecutiveSummary.js
- web/src/containers/__snapshots__/ExecutiveSummary.test.js.snap
- web/src/containers/activity/ContractorResource/ContractorResourceForm.js
- web/src/containers/activity/ContractorResource/ContractorResourceForm.test.js
- web/src/containers/activity/ContractorResource/__snapshots__/ContractorResourceForm.test.js.snap
- web/src/containers/activity/Schedule.js
- web/src/containers/activity/__snapshots__/Schedule.test.js.snap
- web/src/containers/viewOnly/ExecutiveSummary.js
- web/src/containers/viewOnly/activities/Activity.js
- web/src/i18n/locales/en/scheduleSummary.yaml
Resolves #2251 
- Schedule
- ContractorResourceForm
- ExecutiveSummary
> Use 'Start date' and 'End date' consistently for date ranges

- .circleci/config.yml
- bin/preview-deploy/aws.cleanup.sh
- bin/preview-deploy/github-comment.sh
Github is [deprecating basic authentication](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/), which is how the @cms-eapd-bot posts preview URLs today. Instead, they recommend using a personal access token via header authentication. We had previously switched to using the access token, but did not switch to header authentication. This PR makes the switch complete so that Github will stop complaining to me. 😄
- updates the script that posts and updates the Github message as new preview deploys are released
- updates the script that updates the Github message when a preview deploy is removed
- need @NAretakis or @jeromeleecms to have their email addresses associated with the bot so that CMS can fully own it and get Github notifications when there is a problem. …
> Switch to token auth

- terraform/main.tf
- terraform/modules/instances/eapd_jumpbox.tf
- terraform/modules/instances/variables.tf
- terraform/providers.tf
- terraform/variables.tf
This PR adds the initial IaC base to our GitHub repo. It is not currently a part of our CircleCI workflow and needs to be run manually. I am writing up the documentation on how to run this code currently.
- Nothing impacting the current code
- Running the terraform in will create/destroy the eAPD Jumpbox instance.
> Initial IaC

- CHANGELOG.md
- web/src/containers/viewOnly/activities/Activity.js
> Match private contractor costs section on export view to builder

- CHANGELOG.md
- web/src/containers/viewOnly/activities/Activity.js
> Standards and conditions is in the wrong area on export view

- CHANGELOG.md
- web/src/containers/activity/CostAllocateFFP.js
- web/src/containers/activity/CostAllocateFFP.test.js
- web/src/containers/activity/__snapshots__/CostAllocateFFP.test.js.snap
- web/src/reducers/activities.selectors.js
- web/src/reducers/activities.selectors.test.js
Added other funding amount to the Activity {X} Budget for FFY {XX} so that it matches the Summary Budget by Activity
resolves #2306 
- added other funding amount to the Activity {X} Budget for FFY {XX}
> Replace the “Cost Allocation and Budget for FFY 2020” table with part of the new "Summary Budget by Activity” table

- bin/prod-deploy/aws.user-data.sh
Added different installation method for staging/prod since it is different than preview
- Installation method of the CloudWatch Agent
> Staging is different than preview and requires additional changes

- CHANGELOG.md
- api/auth/mockedOktaAuth.js
- api/db/affiliations.js
- api/db/index.js
- api/routes/affiliations/get.endpoint.js
- api/routes/affiliations/get.js
- api/routes/affiliations/get.test.js
- api/routes/affiliations/openAPI.js
- api/routes/affiliations/patch.endpoint.js
- api/routes/affiliations/post.endpoint.js
- api/routes/openAPI/__snapshots__/get.endpoint.js.snap
- api/seeds/development.js
- api/seeds/test.js
- api/seeds/test/affiliations.js
- api/util/states.js
Updated the /states/stateId/affiliations endpoint to have a filter option for pending, active, and inactive affiliations
- updated the get endpoint for affiliations to have a query param called status
- updated endpoint tests and openapi to match new param
> updated affiliation endpoint to take in status and filter returns

- api/util/roles.js
There was a typo in the roles-activities mapping
- change eAPD State Contactor to eAPD State Contractor
> fixed typo

- CHANGELOG.md
- api/seeds/test.js
- web/src/actions/auth.js
- web/src/actions/auth.test.js
- web/src/containers/SessionEndingAlert.js
- web/src/containers/SessionEndingAlert.test.js
- web/src/reducers/auth.js
- web/src/reducers/auth.test.js
- a modal should pop up and the user should not be able to escape or click outside of it to close it
- clicking the X button should close the modal and continue the session
- clicking Continue should continue the session
- clicking Sign out should sign the user out of the session and return them to the login screen
> ends the timeout and closes the alert if the user does performs an action

- web/package-lock.json
- web/package.json
- web/src/actions/auth.js
- web/src/components/ConsentBanner.js
- web/src/util/auth.js
There has been a change in how Okta is handling getting token. Currently they aren't returning state in the response, so we can't compare it to what was sent in. I tested it against my dev instance of Okta too, so it's not just an issue with our CMS set up. I have created an issue with okta-auth-js.
This change should be invisible to the end user.
> work around for issue with logging in

- CHANGELOG.md
- web/src/containers/StateDashboard.js
- web/src/containers/StateDashboard.test.js
Resolves #2776 
- Updates state dashboard landing with eAPD logo per design
> updates state dashboard with eAPD logo

- bin/preview-deploy/aws.sh
- bin/preview-deploy/aws.user-data.sh
- bin/prod-deploy/aws.user-data.sh
This Pull Request should add the splunk user to the ec2-usger group so that it can access application logs and logs stored in /home/ec2-user
- Adds the splunk user to the ec2-user group
- Allows the splunk user to access the logs in /home/ec2-user and all of the logs provided to the Splunk team via spreadsheet
> Adding splunk user to ec2-user group to read /home/ec2-user logs

- bin/preview-deploy/aws.sh
- bin/preview-deploy/aws.user-data.sh
- bin/prod-deploy/aws.user-data.sh
Add the watch option to our pm2 setup so that if the api goes down it should be restarted automatically.
- pm2 is watching the api process
- Killing pm2 api pid will result in pm2 restarting api
> Add Watch Option to PM2

- bin/preview-deploy/aws.user-data.sh
- bin/prod-deploy/aws.sh
Changing from command flag to configuration for pm2 watch
- pm2 watches the api backend process and restarts it if it fails
> PM2 Watch as Configuration

- bin/preview-deploy/aws.user-data.sh
- bin/prod-deploy/aws.sh
PenTesting will be ongoing for an additional week and the watch option currently results in deployments that fail to come up healthy and require manual intervention.
- Watch option is removed from ecosystem file
- API/Backened comes up healthy upon provision
> Removed watch option from pm2 ecosystem file

- terraform/main.tf
- terraform/outputs.tf
Prod and Impl/Staging AWS CloudWatch Alarms will go to the eAPD Slack notifications channel.
- Prod AWS CloudWatch 5XX Alarm posts to eAPD Slack notification channel
- Impl AWS CloudWatch 5XX Alarm posts to eAPD Slack notification channel
> AWS CloudWatch Alarms to Slack

- bin/prod-deploy/aws.sh
Removed the backend health check for Staging/Prod, because AWS is already doing a health check on the /heartbeat endpoint and the curl tests were reporting that the backend isn't up, while the AWS health test was passing.
- Removes redundant healthcheck on /heartbeat
> Remove Curl Backend Test for Staging/Prod

- bin/preview-deploy/aws.sh
- bin/prod-deploy/aws.sh
This PR adds tags to our instances that require web access so that they are not flagged in a security compliance scan. I have manually added the tags on or more persistent resources; Production, Staging, and Load Balancers, Security Groups, and this will address any new instances that are provisioned.
- Newly provisioned instances will receive the appropriate tags
> Adding Exemption Tags for Web Access

- bin/prod-deploy/aws.user-data.sh
The database migrations were not being run in Staging and Production. After some investigation, I determined that it was because the OKTA environment variables were not available when the migrations were run.
- exported OKTA variables when ec2-user logs in
1. This cannot be verified until it's in Staging and Prod, after it's been merged I can test it by looking at the logs in AWS.
> making OKTA environment variables available when the ec2-user logs in

- bin/prod-deploy/aws.sh
- bin/prod-deploy/aws.user-data.sh
The database migrations were not being run in Staging and Production. After some investigation, I determined that it was because the OKTA environment variables were not available when the migrations were run.
- exported OKTA variables when ec2-user logs in
1. This cannot be verified until it's in Staging and Prod, after it's been merged I can test it by looking at the logs in AWS.
> switched how I was passing in the environment variables

- CHANGELOG.md
- web/src/containers/viewOnly/ApdStateProfile.js
- web/src/containers/viewOnly/ApdStateProfile.test.js
Resolves #3159 
-  Updates Key Personnel section to show a "No response was provided" message when no information is provided
1. Login with any account able to create an APD
2. Crete a new APD
3. Go to export view and verify that the "No response was provided" is there under Key State Personnel
4. Compare with the proposed design
5. Enter information for that section and verify it appears on the export view
> Tbolt/3159  Updates Key Personnel section to show a message when no information is provided

- CHANGELOG.md
- web/src/containers/activity/CostAllocateFFP.js
- web/src/containers/activity/__snapshots__/CostAllocateFFP.test.js.snap
- web/src/containers/viewOnly/activities/Activity.js
resolves #3147 
Updates the export view in the budget and ffp section to match proposed design
- Removes extra "Budget and FFP" heading, renames existing heading
1. Login with any account that can create an APD
2. Navigate to export view
3. Verify that under an Activities Budget and FFP sections the headings have been updated to match proposed design
> Tbolt/3147 Remove extra header in budget and ffp export view

- CHANGELOG.md
- web/src/containers/UnexpectedError.js
- web/src/containers/__snapshots__/UnexpectedError.test.js.snap
resolves #
updated error modal with the left warning class and added a warning icon to the header.
- the unexpected error dialog to match the mock ups.
- none.  This was a CSS and minor text change only.
- Logged in
- opened an APD
- stopped docker containers
- edited APD
- got the warning message and confirmed it matched the mock up.
1. see above
> Updating modal when unable to save

- CHANGELOG.md
- api/routes/me/get.js
- api/routes/me/get.test.js
Replacing code that went missing.  This is not at all new code, but rather code that got squashed in a merge conflict previously.
resolves #3242
- adds in a request for data from Okta to the /me endpoint
none. This is all code that has been previously approved, it just seems to have disappeared in a merge conflict.
- select * from okta_users to see what data exists for users in the DB
- alter data as you see fit
- log in and see if the data appears, or if it was altered is changed back
1. okta_user data is displayed on the affiliation request approval screen.  If a user …
> fixing storing of Okta data on login

- .gitignore
- CHANGELOG.md
- api/seeds/development/base-users.js
- api/seeds/shared/issueTokens.js
- api/seeds/shared/set-up-users.js
resolves #3128
Adds a process to the seed method that produces a file called tokens.json that contains a long lived token for every seeded user.  This will allow the automated tests to use a current and valid token for auth which should greatly increase our confidence that tests are testing the right things.
- creates app/api/seeds/test/tokens.json when the seed process is run
- nothibg else.  This does not touch code that runs except during the seed process
- ran seed process
- opened tokens.json and verified them at jwt.io
1. execute the seed process
2. confirm tokens.json exists
3. validate tokens at …
> creating tokens for testing

- CHANGELOG.md
- web/src/components/SecondaryNav.js
- web/src/components/SecondaryNav.test.js
resolves #3334 
- Fixes an issue where the add activity button (the one that was at the bottom of the last activity) was hard-coded to take you to the APD with ID = 1
- no side-effects noted
- test using the add activity button with an existing APD
- test using the add activity button with a newly created APD
1. Login with an account that can view/edit APDs
2. Navigate to the last activity on the Budget and FFP page
3. Click Add activity
4. Verify that it takes you to the Activities Dashboard and creates a new Activity
> tbolt/3334 Fixes issue where add activity would take you to another apd

- CHANGELOG.md
- web/src/containers/ExecutiveSummary.js
- web/src/containers/__snapshots__/ExecutiveSummary.test.js.snap
resolves #3338 
- Updates the Activity Summary on the Executive Summary page to properly render HTML
- No side effects expected
- Add richly-formatted text (bold text, image, etc...) to any Activity Summary
- Verify that when viewing the previously entered activity summary on the executive summary page it's rendering properly and not displaying html tags (such as `<p>` or `<strong>`)
1. Login with any user that can view APDs
2. Navigate to an activities activity overview page
3. Enter some richly-formatted text such as **bold**
4. Verify that in the executive summary it is rendering properly and not displaying html tags
> tbolt/3338 Fix bug with activity summary

- web/src/components/SecondaryNav.js
- web/src/containers/activity/All.js
- web/src/containers/activity/ContractorResources.js
- web/src/containers/activity/Outcomes.js
- web/src/containers/activity/__snapshots__/All.test.js.snap
- web/src/containers/activity/__snapshots__/ContractorResources.test.js.snap
- web/src/containers/activity/__snapshots__/Milestones.test.js.snap
- web/src/containers/activity/__snapshots__/NonPersonnelCosts.test.js.snap
- web/src/containers/activity/__snapshots__/Outcomes.test.js.snap
- web/src/containers/activity/__snapshots__/StatePersonnel.test.js.snap
- web/src/i18n/locales/en/activities/expenses.yaml
- web/src/i18n/locales/en/activities/milestones.yaml
- web/src/i18n/locales/en/activities/statePersonnel.yaml
- web/src/i18n/locales/en/apd/stateProfile.yaml
resolves #3009 
Removes the word 'additional' from button label text from buttons in the key personnel and activities pages when editing an APD.
- Removes the word 'another' from button label text in:
- Activities dashboard
- Pages for editing activities
- Outcomes and milestones
- State staff and expenses
- Private contractor costs
- Budget and FFP
- May affect tests done for the activities/key personnel pages if tests look for specific text for the buttons
- Going to the pages containing the button with edited text and verifying that the word 'another' is no longer present
1. Log in and access APD
2. …
> Removed extraneous instances of 'another' from button text

- integrationTests/cypress/integration/apd/07-default-executive-summary.spec.js
- integrationTests/cypress/integration/apd/08-activities-default-activity.spec.js
- integrationTests/cypress/integration/apd/15-activities-fill-out-budget-and-FFP.spec.js
- integrationTests/cypress/page-objects/export-page.js
Resolves #
This fixes some small things that have changed causing the cypress tests to fail.
how some elements are located in the cypres tests
none, it is just test code.
- cypress tests should succeed
1. Run the cypress tests
> fixing some small issues with the cypress tests due to code changes.

- .circleci/config.yml
Resolves # CircleCI using old node version (14)
Updates node images that Circle uses and the node version that nvm uses
- CircleCI uses node 16.13.2 images
- nvm uses node 16 and sets it to default
> Updated Circle to use node 16

- api/api.js
- api/package.json
Resolves #3815 
added two new heartbeat endpoints:
/heartbeat-db for postgres
/heartbeat-mongo for mongo
The endpoints will return 204 if they are connected and 503 if they aren't.
> added endpoints for health checks for postgres and mongo

- bin/prod-deploy/aws.sh
Resolves # Broken Health Check
Our certs are expired and so the health check won't pass, this temporarily allows insecure TLS so that the health checks will pass
1.
2.
3.
> Temp insecure certs on health check

- .circleci/config.yml
- bin/prod-deploy/aws.sh
Resolves # Removes temporary -k curl flags
I added -k (allow insecure) to the health checks for our site when our certificates expired. We have new certs installed, so we should remove the -k flag. This removes the temporary -k curl flags.
1.
2.
3.
> Removed insecure flag from curl commands

- .circleci/config.yml
Resolves # 4070 [#4070](https://github.com/CMSgov/eAPD/pull/4070)
Adds missing var to preview AMI builds
It's a change to CircleCI config file, so potential to impact builds. It is a part of the weekly ami build, so it could impact that as well.
None
1. Ran the change as "on push" and it successfully built a new Preview AMI
> Adding missing var and updating trigger for testing

- .circleci/config.yml
Resolves # Snyk opening a load of PRs all the time.
Snyk loves to open PRs, each PR creates infrastructure, this will allow Snyk to continue to open PRs without provisioning infrastructure
1.
2.
3.
> Disables automatic building of infrastructure for Snyk PRs

- common/schemas/apdNew.js
- web/src/pages/apd/new/ApdNew.js
- web/src/pages/apd/new/ApdNew.test.js
Resolves #4514 
The new APD form should require the APD name have a value
| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| a user is creating an APD | the name field hasn't been touched | the Create new APD button should be disabled | jest |
| a user is creating an APD | the name field is empty and has been touched | the error message displays below the field and the Create new APD button should be disabled | jest |
| a user is creating an APD | the name field is filled out and the rest of the form is valid | the Create new APD button is enabled | jest |
1.  Go to create a new APD
2. Select APD name field and go off, ensure error message shows
3. You can only create an APD if a name is supplied
screenreader, text …
> NZ/4514 - APD name should be required in the new APD form

- terraform/legacy/prod/modules/buckets.tf
- terraform/legacy/prod/modules/mongo.tf
- terraform/legacy/prod/modules/securityGroups.tf
Resolves # Request from Nathan ODonnell
Adds security groups to eAPD Mongo and PostGres databases to allow scanning for DBProtect.
If Terraform is run globally it would require the re-provisioning of resources, including the Mongo databases. To mitigate this I created the SGs and updated the Mongo instance Terraform code to include the SGs, but only used Terraform to provision the new SGs and manually updated the existing Mongo instances manually.
| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
1.
2.
3.
> Adding SGs for DataProtect to reach eAPD DBs

- api/files/s3.js
- api/files/s3.test.js
- docker-compose.yml
Resolves issue with opening docs and uploading images
The S3 set up changed, this fixes the issues.
1. Verify that clicking How to Get Started opens the correct PDF
2. Verify that clicking How to Access the eAPD opens the correct PDF
3. Verify that clicking State Administrator Authorization Form opens the correct PDF
4. Log in
5. Open an APD
6. Upload an image to a RichText field
7. Verify that there is no error and the image is added
8. Navigate back to the dashboard and then back to the APD
9. Verify that the image is still displaying correctly
> updated S3 set up
